### ISSUE TITLE
GraphQL issues with process reference list and search

### ISSUE THREAD

**Issue by bpascuitoenovacom** [hapifhir/org.hl7.fhir.core#1005]
It's impossible to use search like this :

```
{
  PatientList (familyCaver: "o'connell601"){
     id
    ObservationList (_reference: subject){
      id
    }
  }
}
```
because when it's processed, "subject" is replaced for example by "Patient/Patient/xyz" instead of "Patient/xyz".

The problem appear in GraphQLEngine.processReverseReferenceList() and GraphQLEngine.processReverseReferenceSearch() where i think it will be better to replace :

`arg.addValue(new StringValue(source.fhirType() + "/" + source.getId()));`

by 

`arg.addValue(new StringValue(source.getId()));`

Note : This problem have impact in HAPI FHIR 6.2.0.

**Comment by grahamegrieve** [comment]
I don't think that this is correct. The current code uses .getIdPart() instead of getId() - please test that

**Comment by bpascuitoenovacom** [comment]
Thank you for the response. Effectively you are right for the method "processReverseReferenceList()" but not for the method "processReverseReferenceSearch()" in the master branch who it's refer again to "getId()"
