### ISSUE TITLE
Either make XML writing automatically recognize system specific line separation, or add a explicit git settings for Linux separators 

### ISSUE THREAD

**Issue by dotasek** [hapifhir/org.hl7.fhir.core#1060]
When loading this project from GIT, Windows introduces CR characters in some files (see https://github.com/hapifhir/org.hl7.fhir.core/pull/1059) 

Though we can code around this in a few places, like in the XML writing code, a `.gitattributes` file could indicate that all resource xml files should be LF only instead of CRLF.

**Comment by grahamegrieve** [comment]
both!
