### ISSUE TITLE
Lack of focus parameter in FHIPathEngine.IEvaluationContext#executeFunction for DSTU3 version

### ISSUE THREAD

**Issue by graugaard** [hapifhir/org.hl7.fhir.core#1126]
While working with fhirpath in an r4 and r5 context, custom functions can work with underlying input collection using the focus parameter. This is not currently possible when working in DSTU3.

This can be worked around, but it would be nice to have this functionality.

**Comment by grahamegrieve** [comment]
Hmm. not many people working with DSTU3 still, so I'm not sure how much attention this will get; in principle this is simple: synchronise the DSTU3 FHIRPath engine with the R4 one, but there's a long piece of string to chase there, all the little stuff that's been value added all over the place to the models and the utilities...
