### ISSUE TITLE
FHIRPathEngine.evaluate does not raise exception for invalid path

### ISSUE THREAD

**Issue by omarismail94** [hapifhir/org.hl7.fhir.core#1158]
When evaluating an expression against a resource, the FHIRPathEngine should raise an error if the expression is invalid, as per the spec: [If the identifier cannot be resolved, the evaluation will end and signal an error to the calling environment.](https://build.fhir.org/ig/HL7/FHIRPath/#path-selection). 

To reproduce the issue, run the following:

```
  fun `show that fhirPathEngine evaluates if the fhir expression is wrong when it shouldnt`() {

    val fhirPathEngine =  with(FhirContext.forCached(FhirVersionEnum.R4)) {
      FHIRPathEngine(HapiWorkerContext(this, this.validationSupport))
    }
    val resource =
      Patient().apply {
        addName(
          HumanName().apply {
            this.family = "Doe"
            this.addGiven("John")
          }
        )
      }

    fhirPathEngine.evaluate(resource, "this.should.not.work")
}
```

In the Android FHIR SDK, we have a [use-case](https://github.com/google/android-fhir/issues/1658)  where we want to distinguish between a invalid expression, and an expression that is valid but does not return anything. 

The expected behavious is that the `evaluate` function throws an error as opposed to returning an empty list

**Comment by omarismail94** [comment]
CC: @jingtang @brynrhodes

**Comment by omarismail94** [comment]
I've been poking around in the code, and Im curious why the "checkValid" flag [here](https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.r4/src/main/java/org/hl7/fhir/r4/utils/FHIRPathEngine.java#L437) is set to false:

```
    Base[] list = item.listChildrenByName(name, false);
```

shouldn't it be true, or a flag that users can set?

**Comment by jingtang10** [comment]
@tadgh

**Comment by tadgh** [comment]
Hey sorry, I am off for the month of march (back in April) , but I can ping @KevinDougan-SmileCDR or @markiantorno to have a look

**Comment by jingtang10** [comment]
thanks gary for tagging.

kevin/mark/dotasek - if you can guide us to fix this it would be great! thanks!

**Comment by grahamegrieve** [comment]
what I don't understand is why you think that "this.should.not.work" is not a valid expression. It looks fine to me

**Comment by omarismail94** [comment]
I see that `this.should.not.work` has valid syntax, but when evaluated against a resource that does not have that field in its definition, should it not throw an error as per the spec, i.e. the lexer should mark the expression as valid, but when evaluated against a resource that does not contain the field, it should throw an error?

**Comment by grahamegrieve** [comment]
Discussion here: https://chat.fhir.org/#narrow/stream/179266-fhirpath/topic/unknown.20elements

The opinion of the engine maintainers is that this is a mistake in the specification, and I'm certainly not going to change the default behaviour - there's a great deal of stuff in production that relies on how it works now.

But have you looked at check()? That does do what you, and checks the expression very deeply against the specified context

**Comment by omarismail94** [comment]
@grahamegrieve thanks for suggesting using `check`! I did try it, but I haven't gotten it to work. This is what I am doing right now:

```
 val resource =
      Patient().apply {
        gender = Enumerations.AdministrativeGender.MALE
        addName(
          HumanName().apply {
            this.family = "Doe"
            this.addGiven("John")
          }
        )
      }


fhirPathEngine.check(resource,
                         "Patient",
                         "Patient",
                         "Patient.gender" )
```

but it throws:

```
java.lang.NullPointerException: Cannot invoke "org.hl7.fhir.r4.model.StructureDefinition.getUrl()" because "sd" is null
```

I based how to pass in the variables via the example in FHIRPathTests [here](https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.r4/src/test/java/org/hl7/fhir/r4/test/FHIRPathTests.java#L194)

**Comment by grahamegrieve** [comment]
it does require you to load the base FHIR package for the version you are using into the context provided to the engine. I don't know how that would be done in your environment

**Comment by omarismail94** [comment]
Thanks @grahamegrieve ! I got the base FHIR package to load. Pasting here in case anyone runs into similar issues:

```
val myContext =
      SimpleWorkerContext.fromPackage(
        FilesystemPackageCacheManager(true).loadPackage("hl7.fhir.r4.core", "4.0.1")
      )

    val fhirPathEngine =
      FHIRPathEngine(myContext).apply { hostServices = FHIRPathEngineHostServices }

    val resource =
      Patient().apply {
        gender = Enumerations.AdministrativeGender.MALE
        addName(
          HumanName().apply {
            this.family = "Doe"
            this.addGiven("John")
          }
        )
      }

    fhirPathEngine.check(
      resource,
      resource.resourceType.name,
      resource.resourceType.name,
      "Patient.gender"
    )
```

**Comment by grahamegrieve** [comment]
ok great.
