### ISSUE TITLE
[Bug] Params.java version comparison is broken (`-version 4.0.1 -ig hl7.fhir.r4.core#4.0.1` throws exception)

### ISSUE THREAD

**Issue by david-simons** [hapifhir/org.hl7.fhir.core#1169]
does `org.hl7.fhir.validation\src\main\java\org\hl7\fhir\validation\cli\utils\Params.java` have a bug introduced in a recent release, likely line 312 ?
(perhaps with https://github.com/hapifhir/org.hl7.fhir.core/commit/2bd73c650ee7ea6458687d662a680b21db0b65e9 ?)

The version comparison seems broken, @grahamegrieve 
> **Parameters are inconsistent: specified version is 4.0.1 but -ig parameter hl7.fhir.r4.core#4.0.1 implies a different version**

both are 4.0.1, right? perhaps a string-comparison issue?

```
FHIR Validation tool Version 5.6.109 (Git# f48d4136905b). Built 2023-03-13T05:16:38.646Z (35 hours old)
  Java:   17.0.6 from /usr/lib/jvm/java-17-openjdk on amd64 (64bit). 1926MB available
Exception in thread "main" java.lang.Error: Parameters are inconsistent: specified version is 4.0.1 but -ig parameter hl7.fhir.r4.core#4.0.1 implies a different version
	at org.hl7.fhir.validation.cli.utils.Params.loadCliContext(Params.java:313)
	at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:124)
Error: Process completed with exit code 1.
```

**Comment by david-simons** [comment]
PS also a typo in line 315 (differetion)

**Comment by hvamstel** [comment]
The versions of us core are not the same as FHIR. When I look at the list of published verison of us core I can not find a version 4.0.1 as is mentioned in the if parameter. See: http://hl7.org/fhir/us/core/history.html. Should it not be hl7.fhir.r4.core#5.0.1 as that is the latest IG for us core targeting FHIR 4.0.1

**Comment by david-simons** [comment]
Did some debugging:

Seems like it uses `4.0` instead of `4.0.1` for the IG package version, which then fails to match the `-version 4.0.1`

```
PS C:\Users\nlv09099\Source\Repos\FHIR> java -jar C:\Users\nlv09099\Source\Repos\org.hl7.fhir.core\org.hl7.fhir.validation.cli\target\org.hl7.fhir.validation.cli-5.6.111-SNAPSHOT.jar -jurisdiction uv -version 4.0.1 -ig hl7.fhir.r4.core#4.0.1
FHIR Validation tool Version 5.6.111-SNAPSHOT (Git# 2e36c8147ab5). Built 2023-03-15T12:28:49.800+01:00 (56 mins old)
  Java:   17 from C:\Program Files\jdk-17 on amd64 (64bit). 2018MB available
Exception in thread "main" java.lang.Error: Parameters are inconsistent: specified version is 4.0.1 but -ig parameter hl7.fhir.r4.core#4.0.1 implies a different version (4.0)
        at org.hl7.fhir.validation.cli.utils.Params.loadCliContext(Params.java:313)
        at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:124)
```

**Comment by david-simons** [comment]
perhaps `getVersionFromIGName` should return the actualValue - when specified (e.g. `4.0.1`) - instead of always the default value (`4.0`)

**Comment by david-simons** [comment]
we are retrieving the `-version 4.0.1` and the `-ig hl7.fhir.r4.core"#4.0.1` arguments from our package.json:

```
  "fhirVersions": [
    "4.0.1"
  ],
  "dependencies": {
    "hl7.fhir.r4.core": "4.0.1"
  }
```

<https://confluence.hl7.org/display/FHIR/NPM+Package+Specification#NPMPackageSpecification-Versions>

**Comment by david-simons** [comment]
As a workaround, we now no longer provide a `-version` argument, and solely rely on the `-ig hl7.fhir.r4.core#4.0.1` argument to have the fhirVersion default to `4.0` during validation.
