### ISSUE TITLE
Utilities.path now throws with illegal chars

### ISSUE THREAD

**Issue by mrinnetmaki** [hapifhir/org.hl7.fhir.core#1208]
I ran into this problem with the [IG Publisher](https://github.com/HL7/fhir-ig-publisher) when compiling a FHIR IG that uses a GitHub based template, when compiling on a Windows machine.

The IG publisher [creates the path](https://github.com/HL7/fhir-ig-publisher/blob/master/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/templates/TemplateManager.java#L254) with `Utilities.path`. In this case the path is something like `C:\GitHub\finnish-base-profiles\https://github.com/fhir-fi/ig-template-fhir-fi` or `C:\GitHub\dk-core\https://github.com/hl7dk/dk-ig-template`. And the IG publisher is just trying it out and seeing whether a file named like that exists. The `PathBuilder.checkPathIsChildOfTarget` then [creates](https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.utilities/src/main/java/org/hl7/fhir/utilities/PathBuilder.java#L141) the `Path` and does not catch the 

> java.nio.file.InvalidPathException: Illegal char <:> at index 38: C:\GitHub\finnish-base-profiles\https:\\github.com\fhir-fi\ig-template-fhir-fi

thrown by `Path.of`.

**This makes all builds of IG's that use a template published in Github fail on Windows computers.**

This could of course be fixed in the IG Publisher too, but I decided to report this here, as there may be many other projects too that use `Utilizes.path` and are affected.

This behavior changed with commit https://github.com/hapifhir/org.hl7.fhir.core/commit/0ae4aa9a0f34f27f028b5d5b26b5255acfa435ef.

**Comment by mrinnetmaki** [comment]
(Ping @marvasuo who first reported this.)

**Comment by dotasek** [comment]
This is the intended behaviour for Utilities.path. It is in fact catching a path invalid on Windows.

The fix belongs in IG publisher, and I have implemented it here:  https://github.com/HL7/fhir-ig-publisher/pull/669

**I will close this issue after the above PR is merged.**

Utilities.path now does several checks to ensure that paths are valid, and that they do not access areas of the filesystem that could present a security issue (root directories, paths that are not children of the first entry, etc).

https://github.com/hapifhir/org.hl7.fhir.core/security/advisories/GHSA-9654-pr4f-gh6m
