### ISSUE TITLE
SubscriptionTopic and SubscriptionStatus converters for VersionConvertorFactory_43_50

### ISSUE THREAD

**Issue by dotasek** [hapifhir/org.hl7.fhir.core#1212]
There are no SubscriptionTopic or SubscriptionStatus converter available for VersionConvertorFactory_43_50. These should be added.

This was requested by @fil512 to make life easier in HAPI-FHIR

**Comment by fil512** [comment]
Examples:

```
{
  "resourceType": "SubscriptionTopic",
  "id": "1",
  "meta": {
    "versionId": "1",
    "lastUpdated": "2023-04-13T19:11:45.601-04:00"
  },
  "url": "http://example.com/topic/test",
  "status": "active",
  "resourceTrigger": [ {
    "resource": "Encounter",
    "supportedInteraction": [ "create" ],
    "queryCriteria": {
      "previous": "Encounter?status=planned",
      "current": "Encounter?status=finished",
      "requireBoth": true
    }
  } ]
}
```
{
  "resourceType": "SubscriptionStatus",
  "status": "active",
  "type": "event-notification",
  "eventsSinceSubscriptionStart": "1",
  "notificationEvent": [ {
    "eventNumber": "1",
    "focus": {
      "reference": "Encounter/3"
    }
  } ],
  "subscription": {
    "reference": "Subscription/2"
  },
  "topic": "http://example.com/topic/test"
}
```

```

**Comment by fil512** [comment]
Those are both R4B if it matters

**Comment by fil512** [comment]
I guess you can tell from the eventNumber

**Comment by dotasek** [comment]
Implemented in: 
https://github.com/hapifhir/org.hl7.fhir.core/pull/1226
https://github.com/hapifhir/org.hl7.fhir.core/pull/1243
