### ISSUE TITLE
Return text content preferentially when composing HumanName.getNameAsSingleString()

### ISSUE THREAD

**Issue by dotasek** [hapifhir/org.hl7.fhir.core#1214]
After some discussion, the construction of the return value for getNameAsSingleString() in HumanName is not necessarily ideal. 

Since human name construction varies considerably depending on locale and culture, it is preferential to return the content of getTextElement() when it is available, as it is assumed that this content will be formatted correctly vs. the construction currently implemented by getNameAsSingleString().

**Comment by grahamegrieve** [comment]
So is this sorted now?

**Comment by dotasek** [comment]
@grahamegrieve It isn't sorted.

The merged commit solves for another issue. Just to confirm before I implement this, the following change would take place:

Current:

```java
  /** 
   * Returns all of the components of the name (prefix, given, family, suffix) as a single string with a single spaced 
   * string separating each part. 
   * <p> 
   * If none of the parts are populated, returns the {@link #getTextElement() text} element value instead. 
   * </p> 
   */ 
  public String getNameAsSingleString() { ... 
```

New:

```java
  /** 
   * Returns the {@link #getTextElement() text} element value if it is not null.
   
   * If the {@link #getTextElement() text} element value is null, returns all of the components of the name (prefix, 
   * given, family, suffix) as a single string with a single spaced string separating each part. 
   * 
   */ 
  public String getNameAsSingleString() { ... 
```

**Comment by grahamegrieve** [comment]
that looks good to me
