### ISSUE TITLE
problem with "empty is type" operator evaluation

### ISSUE THREAD

**Issue by CarthageKing** [hapifhir/org.hl7.fhir.core#122]
This originally came from: https://chat.fhir.org/#narrow/stream/179266-fhirpath/topic/Confused.20about.20is.20operator

Let's say I have an Observation like the one below:
```
Observation
  id: xyz
```
I then run a FHIRPath expression against it
```
issued is instant
```
From my understanding of http://hl7.org/fhirpath/2018Sep/index.html#is-type-specifier, since `issued` is empty, then this whole expression will evaluate to an empty collection.
Is my understanding correct?
The reason I ask is when I try this with the HAPI FHIRPath engine, it results in false

**Comment by grahamegrieve** [comment]
I added a unit test Observation.issued is instant and specified that the outcome is an empty collection, and that passes. So it sounds like the problem is not in the engine. how are you running it?

**Comment by CarthageKing** [comment]
[sample-fhirpath-test.zip](https://github.com/hapifhir/org.hl7.fhir.core/files/4174159/sample-fhirpath-test.zip)
I attached a Java Maven project. I'm using HAPI FHIR 4.1.0 and the R5 validator.

When I run the ObservationTest class, I get [BooleanType[false]] instead of just [] for the 'issued is instant' expression.

**Comment by CarthageKing** [comment]
We updated to HAPI FHIR 4.2.0 and the problem does not occur there. So closing this issue.
