### ISSUE TITLE
Validator should flag profiles with optional slice discriminators

### ISSUE THREAD

**Issue by ElliotSilver** [hapifhir/org.hl7.fhir.core#1239]
See https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/How.20to.20interpret.20a.20slice.

In that conversation I think @lmckenzi is suggesting that the element(s) in `slice.discriminator.path` must have a min cardinality of 1 in the slice (or be given an effective min cardinality of 1?) unless the discriminator.type is "exists".

**Comment by grahamegrieve** [comment]
I don't understand this - it has a minimum cardinality of 1
