### ISSUE TITLE
Add ignored extensions to Domain Resource conversion

### ISSUE THREAD

**Issue by dotasek** [hapifhir/org.hl7.fhir.core#1245]
Element conversion can be provided with ignorable extensions:

https://github.com/hapifhir/org.hl7.fhir.core/blob/d43d9bbdd8822e9d0ee7f6e6c5417a5e3ee09ac8/org.hl7.fhir.convertors/src/main/java/org/hl7/fhir/convertors/conv43_50/datatypes43_50/Element43_50.java#L39

However, for resources, copying extensions follows less obvious pattern:

https://github.com/hapifhir/org.hl7.fhir.core/blob/7fd5bba25936e9f60a8a3054a8e5cdff162dc5b4/org.hl7.fhir.convertors/src/main/java/org/hl7/fhir/convertors/conv43_50/resources43_50/Resource43_50.java#LL515C23-L515C23

This requires Resource specific ignores to be added in places like this:

https://github.com/hapifhir/org.hl7.fhir.core/pull/1226/files#diff-a720168db1111d7e60f721c75d845bd361e8d962a09b675ce6e81f1b7e3fe95c

Conversion for resources should follow the same pattern as elements, allowing a vararg to define ignorable extension urls.

**Comment by grahamegrieve** [comment]
This is done now, right?

**Comment by dotasek** [comment]
This was done in https://github.com/hapifhir/org.hl7.fhir.core/pull/1256
