### ISSUE TITLE
Buggy stringValue

### ISSUE THREAD

**Issue by jkiddo** [hapifhir/org.hl7.fhir.core#1262]
following up on this (https://chat.fhir.org/#narrow/stream/179167-hapi/topic/syntax):

```
this:

 this.getIdElement().toUnqualifiedVersionless().asStringValue();
vs.

 this.getIdElement().toUnqualifiedVersionless().getValueAsString();
one returns null whereas the other returns the string ...
```
most likely around 
https://github.com/hapifhir/org.hl7.fhir.core/blob/110f695e9c4adcf59a46beb5d59fe833c35832bc/org.hl7.fhir.r4/src/main/java/org/hl7/fhir/r4/model/IdType.java#L672

**Comment by grahamegrieve** [comment]
@jamesagnew this one for you
