### ISSUE TITLE
R5 Bundle.getLink(String) does not work because String is compared to an enum

### ISSUE THREAD

**Issue by pnewhook** [hapifhir/org.hl7.fhir.core#1266]
The R5 version of [`Bundle.getLink(String)`](https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.core.generator/configuration/Bundle.java#L16) always returns null. It looks like the problem is `BundleLinkComponent.getRelation()` used to return a `String`, but now returns a `Bundle.LinkRelationTypes` enum value, so the string comparison will always fail. I believe the comparison needs to be made against `next.getRelation().toCode()` as is done in `BundleEntryComponent`.

**Comment by grahamegrieve** [comment]
fixed (will be PRed soon)
