### ISSUE TITLE
Option to Run Transformation without Terminology Server

### ISSUE THREAD

**Issue by KMCGit** [hapifhir/org.hl7.fhir.core#1286]
Would it be possible to add functionality to be able to run transformations without the dependency on the terminology server? (run Transformation with '-tx n/a')

I am able to run the Compile commands using '-tx n/a' and remove the dependency on the terminology server. However, attempting to do so for the Transform command returns a message that a Transform cannot be performed without the connection to the Terminology server. (Even when instructing to add '-tx n/a' to the command, upon failure of the Transform command)

Is this something that could be added or would this not be a possibility? 

( Error 1: 
Terminology server http://tx.fhir.orgException in thread "main" org.hl7.fhir.exceptions.FHIRException: Unable to connect to terminology server. Use parameter '-tx n/a' to run without using terminology services to validate LOINC, SNOMED, ICD-X etc. Error = Error fetching the server's capability statement: Connect timed out

Error 2: 
Exception in thread "main" java.lang.Exception: Must provide a terminology server when doing a transform)

**Comment by grahamegrieve** [comment]
I don't think it's possible, in fact. The conversion depends on the server
