### ISSUE TITLE
Local conversion package build failure on SubscriptionTopic40_50Test.java due to hardcoded output stream paths

### ISSUE THREAD

**Issue by rettema** [hapifhir/org.hl7.fhir.core#1301]
A local maven build of the conversion package / project fails on the SubscriptionTopic40_50Test.java class due to hard coded output stream paths.

```
    org.hl7.fhir.r5.formats.JsonParser r5_parser = new org.hl7.fhir.r5.formats.JsonParser();
    r5_parser.setOutputStyle(OutputStyle.PRETTY).compose(new FileOutputStream("/tmp/source.json"), r5_actual);
    r5_parser.setOutputStyle(OutputStyle.PRETTY).compose(new FileOutputStream("/tmp/output.json"), r5_conv);
```

This appears to be additional, local logic not found in any of the other conversion package test classes and should be removed.

**Comment by dotasek** [comment]
Fixed here: https://github.com/hapifhir/org.hl7.fhir.core/commit/d2c873336c97d0cadf97e58cb964e8e8a662ef50
