### ISSUE TITLE
Exception occurs with maven build in module "org.hl7.fhir.utilities"

### ISSUE THREAD

**Issue by MikeKurtze** [hapifhir/org.hl7.fhir.core#1307]
When i build the pom "_org.hl7.fhir.core_" with maven i get the following exception: "**Execution downstream of goal org.codehaus.mojo:buildnumber-maven-3.0.0 Nullpointer Exception...**". If i add in artifact "_org.hl7.fhir.utilities_" in plugin "_org.codehaus.mojo_" (artifact "_buildnumber-maven-plugin_") in "<**configuration**>" the following entry `<revisionOnScmFailure>UNKNOWN</revisionOnScmFailure>` then the problem seems to be solved.

**Comment by dotasek** [comment]
I have yet to see this error, either locally or on the pipelines. What version of maven are you using?

Could you include the console logging you see when this happens?

**Comment by dotasek** [comment]
Closing due to no feedback.
