### ISSUE TITLE
Fhir R5 Generate optional fields in addition to required fields according to a profile

### ISSUE THREAD

**Issue by bschaffh** [hapifhir/org.hl7.fhir.core#1335]
Hello, 

I am currently using the org.hl7.fhir.r5 packet to generate classes according to their StructureDefinition defined in a profile (for example in a JSON from Simplifier).

I am  using the classes from r5/profileModel and I saw the PETests.java class that shows an example of how to use these classes.

I've used it for the profiles I want,  but it only generates the fields with a cardinality of 1 minimum. How could I generate the optionnal fields too? This would save me from developping these fields manually.

Thanks ! 

![Example](https://github.com/hapifhir/org.hl7.fhir.core/assets/42124355/02c446f3-cac0-4427-9f9f-3940df74b4b9)
(Here the fields generated are only those with a minimum cardinality >= 1, and I would like to generate the optionals too)

**Comment by grahamegrieve** [comment]
perhaps you should show your code so we can be clear about what you are doing?

**Comment by bschaffh** [comment]
`private IWorkerContext ctxt;
    public void Load() throws IOException {
        if (ctxt == null) {
            ctxt = TestingUtilities.getSharedWorkerContext();
            FilesystemPackageCacheManager pc = new FilesystemPackageCacheManager(true);
            NpmPackage npm = pc.loadPackage("hl7.fhir.us.core", "5.0.0");
            ctxt.loadFromPackage(npm, new TestPackageLoader(Utilities.strings(SimpleWorkerContext.defaultTypesToLoad().stream().toArray(String[]::new))));

            ctxt.cacheResource(new JsonParser().parse(TestingUtilities.loadTestResource("r5", "profiles", "pe-extension-simple.json")));
            ctxt.cacheResource(new JsonParser().parse(TestingUtilities.loadTestResource("r5", "profiles", "pe-extension-complex.json")));
            ctxt.cacheResource(new JsonParser().parse(TestingUtilities.loadTestResource("r5", "profiles", "pe-profile2.json")));
            ctxt.cacheResource(new JsonParser().parse(TestingUtilities.loadTestResource("r5", "profiles", "pe-profile1.json")));
        }
    }

     public void GenerateObservationFromProfile() throws IOException {
         Load();

         String profileURL = "http://hl7.org/fhir/test/StructureDefinition/pe-profile1";
         Observation res = (Observation) new PEBuilder(ctxt, PEBuilder.PEElementPropertiesPolicy.NONE, false).createResource(profileURL, true);

         String json = new JsonParser().setOutputStyle(IParser.OutputStyle.PRETTY).composeString(res);
         System.out.println(json);
    }`

Here is an example of the generation. I take the profile definitions from us.core npm package, and the call of GenerateObservationFromProfile() generates the output from above. However, the output only contains fields with cardinality of at least 1, and I would like to generate those with a cardinality of 0..1 or 0..* too.

**Comment by grahamegrieve** [comment]
You didn't provide any values, so how can it generate them?
