### ISSUE TITLE
Botched warning message when display value is unknown

### ISSUE THREAD

**Issue by pieter-edelman-nictiz** [hapifhir/org.hl7.fhir.core#1386]
Hi,

I'm trying to validate a resource that uses a code system which the terminology server doesn't know, and I get a bit of a botched warning message for the display value:

> No valid Display Names found for urn:oid:2.16.840.1.113883.2.4.3.11.22.472#24 in the languages Wettelijke vertegenwoordiger for 'urn:oid:2.16.840.1.113883.2.4.3.11.22.472#24'

"Wettelijke vertegenwoordiger" is the actual display value in the resource I'm validating.

I used the following command for the validator from the root of [this repo](https://github.com/Nictiz/Nictiz-R4-zib2020/) (I'm not quite sure what's needed to provide a minimal working example in terms of additional profiles and ValueSets, so I'm just linking the full repo here): 

> java -jar validator_cli.jar -version 4.0 -ig resources/ -recurse examples/nl-core-AdvanceDirective-01-RelatedPerson-01.xml

I also tried to add `-language nl`, but the warning message stays the same.

**Comment by grahamegrieve** [comment]
I think this is fixed next release (a little hard for me to check)

**Comment by pieter-edelman-nictiz** [comment]
Issue seems to be fixed, thanks!
