### ISSUE TITLE
R4/R4B FHIRPathEngine code includes System.out.println

### ISSUE THREAD

**Issue by Boereck** [hapifhir/org.hl7.fhir.core#1415]
Hi,

The current Versions of [`org.hl7.fhir.r4.utils.FHIRPathEngine`](https://github.com/hapifhir/org.hl7.fhir.core/blob/904898315592f89519f6422fdcada89b1fbf229c/org.hl7.fhir.r4/src/main/java/org/hl7/fhir/r4/utils/FHIRPathEngine.java#L6495) and [`org.hl7.fhir.r4b.utils.FHIRPathEngine`](https://github.com/hapifhir/org.hl7.fhir.core/blob/904898315592f89519f6422fdcada89b1fbf229c/org.hl7.fhir.r4b/src/main/java/org/hl7/fhir/r4b/utils/FHIRPathEngine.java#L6492) contain a call to `System.out.println`, which leads to pretty annoying console output. 

I guess this is a leftover from a debugging session and can be either commented out or removed.

Best regards,
Max

**Comment by dotasek** [comment]
@Boereck can you check to see that this is resolved?

If not, could you give examples of the output you're seeing?

**Comment by Boereck** [comment]
Hey @dotasek, I've built the latest hapi and org.hl7.fhir.core versions and ran our app with it the built snapshots. I don't see any outputs on stdout anymore. Thank you very much for the change!
