### ISSUE TITLE
Enhancement - RequirementsRender should render Requirements.statement.key as anchor link

### ISSUE THREAD

**Issue by rettema** [hapifhir/org.hl7.fhir.core#1430]
To facilitate cross referencing from other testing resources like TestPlan the RequirementRenderer should render the Requirements.statement.key as an anchor link.

Example:
<h2>Statements</h2>
<table class="grid">
<tr>
<td><b><a href="#us-core-req-capstmt-responder-01">us-core-req-capstmt-responder-01</a></b></td>
<td><a href="http://hl7.org/fhir/R5/codesystem-conformance-expectation.html#conformance-expectation-SHALL">SHALL</a></td>
<td><div><p>The US Core Responder <strong>SHALL</strong> support the secured HTTP (https) protocol and the use of TLS 1.2 or higher when returning the responder's CapabilityStatement.</p></div></td>
</tr>
</table/>

**Comment by grahamegrieve** [comment]
I'm confused by this. It does already do that

**Comment by rettema** [comment]
Really? I must be looking at an slightly older version of the RequirementsRenderer. Let me update my local repo and I'll reply back.

Thanks.

**Comment by grahamegrieve** [comment]
````
     XhtmlNode td = tr.td();
      td.b().an(stmt.getKey());
      td.tx(lbl);
````

**Comment by rettema** [comment]
Yes. I was expecting this to be prefixed with '#". That would make it a reference that could be used on other pages.

Something like:

     XhtmlNode td = tr.td();
      td.b().an("#"+stmt.getKey());
      td.tx(lbl);

**Comment by grahamegrieve** [comment]
That's not how references work. The # is appended to identify the named link in the page. The named link (an()) doesn't have the #

**Comment by rettema** [comment]
Hmm. OK. Let me re-think this. Closing this issue for now.

Thanks!
