### ISSUE TITLE
conformsToProfile returns false even if the error is unrelated to profile conformance

### ISSUE THREAD

**Issue by TahaAttari** [hapifhir/org.hl7.fhir.core#1468]
https://github.com/hapifhir/org.hl7.fhir.core/blob/1534a5b6eb8883b9241b3d779b0e5e2d99b0332a/org.hl7.fhir.validation/src/main/java/org/hl7/fhir/validation/instance/InstanceValidator.java#L402-L409

`conformsToProfile` returns `ok  = false` for any validation errors in the resource / element being checked, but should really only return false for profile conformance failure.

**Comment by grahamegrieve** [comment]
Any validation error is a failure against the profile. And I don't know if I can differentiate in any useful way. Further discussion if you think there's something that should be done here: https://chat.fhir.org/#narrow/stream/179177-conformance
