### ISSUE TITLE
Empty java files in repo

### ISSUE THREAD

**Issue by llowinge** [hapifhir/org.hl7.fhir.core#1472]
List
* https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.core.generator/configuration/CapabilityStatement.java
* https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.core.generator/configuration/ImplementationGuideDefinitionResourceComponent.java
* https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.core.generator/configuration/ManifestResourceComponent.java

Can be those files removed or its content was deleted by accident ? Thank you

**Comment by grahamegrieve** [comment]
is it a problem that they're empty, is it?

**Comment by llowinge** [comment]
I don't know. I've only raised concern as it looks like a mistake, but maybe i'm mistaken. Are you against removing them (if not needed) ?

**Comment by grahamegrieve** [comment]
Done

**Comment by llowinge** [comment]
Thank you @grahamegrieve for your effort.
