### ISSUE TITLE
org.hl7.fhir.r4.model.UuidType is not annotated

### ISSUE THREAD

**Issue by CarthageKing** [hapifhir/org.hl7.fhir.core#148]
The `org.hl7.fhir.r4.model.UuidType` is not annotated with `@DatatypeDef(name = "uuid", profileOf = UriType.class)`. This prevents it from being used as a valid data type for R4.

For example, create a Task resource with Task.output.value set to a UuidType, then try to convert to JSON/XML. HAPI FHIR will output an error.

uuid is one of the valid data types in R4.

**Comment by jamesagnew** [comment]
FIxed in 53ef98198fcfae3ac89d40f848e78503e8af0c92
