### ISSUE TITLE
Custom Extensions

### ISSUE THREAD

**Issue by LandonReilly** [hapifhir/org.hl7.fhir.core#1492]
Does this validator support the pass through of custom extensions? For example: Only for reference purposes. 

{
    "resourceType": "Appointment",
    "id": "appointment-id",
    "extension": [
        {
            "url": "http://example.org/fhir/StructureDefinition/preferred-language",
            "valueCode": "en-US"
          }
    ],
}

**Comment by grahamegrieve** [comment]
what does 'pass through' mean?

**Comment by ComandoLando** [comment]
It throws an error. Code system not valid. When included. Pass through means more no error thrown for custom extensions.

**Comment by LandonReilly** [comment]
Here is an example of the error and Json. I would probably expect a warning not an error maybe. I've tested this on us-core and au-core. But please let me know if i am missing something :)  

`Error: *FAILURE*: 2 errors, 1 warnings, 0 notes
  Error @ Appointment.extension[0].url (line 6, col84): Example URLs are not allowed in this context (http://example.org/fhir/StructureDefinition/preferred-language)
  Error @ Appointment.extension[0] (line 5, col12): The extension http://example.org/fhir/StructureDefinition/preferred-language is unknown, and not allowed here
  Warning @ Appointment (line 1, col2): Constraint failed: dom-6: 'A resource should have narrative for robust management' (defined in http://hl7.org/fhir/StructureDefinition/DomainResource) (Best Practice Recommendation)`

`{
    "resourceType": "Appointment",
    "id": "appointment-id",
    "extension": [
        {
            "url": "http://example.org/fhir/StructureDefinition/preferred-language",
            "valueCode": "en-US"
          }
    ],
    "status": "booked",
    "appointmentType": {
        "coding": [
            {
                "system": "http://bps/fhir/CodeSystem/appointment-type",
                "code": "56",
                "display": "Routine Check-Up"
            }
        ],
        "text": "Routine Check-Up"
    },
    "reasonCode": [
        {
            "text": "One Time check-up"
        }
    ],
    "priority": 1,
    "start": "2023-11-15T09:00:00+00:00",
    "end": "2023-11-15T10:00:00+00:00",
    "minutesDuration": 60,
    "created": "2023-11-13T06:14:52.831Z",
    "comment": "Patient should bring previous medication records.",
    "participant": [
        {
            "actor": {
                "reference": "Practitioner/2",
                "type": "Practitioner",
                "display": "Dr. Jane Smith"
            },
            "status": "accepted"
        },
        {
            "actor": {
                "reference": "Patient/56",
                "type": "Patient",
                "display": "John Doe"
            },
            "status": "accepted"
        },
        {
            "actor": {
                "reference": "Location/1",
                "type": "Location",
                "display": "Clinic Room 1"
            },
            "status": "accepted"
        },
        {
            "actor": {
                "reference": "RelatedPerson/45",
                "type": "RelatedPerson",
                "display": "John Doe"
            },
            "status": "accepted"
        }
    ]
}`

**Comment by grahamegrieve** [comment]
you get a pair of errors around example content. By default, the validator doesn't allow example URLs or extensions. This is configurable: see https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator#UsingtheFHIRValidator-Extensions and https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator#UsingtheFHIRValidator-ExampleURLs.

These messages are the errors working as defined
