### ISSUE TITLE
`xpp3` no longer optional in `dstu2016may`

### ISSUE THREAD

**Issue by jamesnetherton** [hapifhir/org.hl7.fhir.core#1506]
Since the `xpp3` groupId switch from `xpp3` to `org.ogce`, `<optional>true</optional>` was removed from the dependency declaration in `ca.uhn.hapi.fhir:org.hl7.fhir.dstu2016may`:

https://github.com/hapifhir/org.hl7.fhir.core/commit/490e57fa7cabd114c8b3401c388f3e8c957322dc#diff-01401616945b253c0ca2df7d195b2a75f6f65d5ace5f6f7412bed091eb88f9a4

It causes some classloading issues for me due to `xpp3` bundling its own `QName` class. It's simple enough to resolve by excluding `xpp3`. I just wondered whether it should be declared as an optional dependency like it was in the past.

**Comment by grahamegrieve** [comment]
@dotasek ?

**Comment by dotasek** [comment]
@jamesnetherton it looks to me like the omission of `optional` was made in error. It's not consistent with the other modules. I will test to see if adding it back in impacts anything, and likely make it `optional` again.
