### ISSUE TITLE
Reopen https://github.com/hapifhir/org.hl7.fhir.core/issues/1524

### ISSUE THREAD

**Issue by bdc-ehealth** [hapifhir/org.hl7.fhir.core#1660]
The stale bot closed https://github.com/hapifhir/org.hl7.fhir.core/issues/1524 . Has there been any progress on this issue?

**Comment by grahamegrieve** [comment]
I don’t think it’s still a problem. If it is still a problem, what’s a
test case that reproduces the problem?

**Comment by bdc-ehealth** [comment]
@grahamegrieve ,

I tested the problem again using: https://build.fhir.org/ig/hl7-be/mycarenet/branches/issue-93/ . It seems indeed to be solved. Thank you for the feedback!
