### ISSUE TITLE
The `div` field is missing in `Narrative.listChildren` for some versions.

### ISSUE THREAD

**Issue by bashir2** [hapifhir/org.hl7.fhir.core#1678]
The R5 implementation of the `Narrative` type returns the `div` element  in `listChildren` ([here](https://github.com/hapifhir/org.hl7.fhir.core/blob/115074ee601f1975e8dcdf924e513ad0c759ff7f/org.hl7.fhir.r5/src/main/java/org/hl7/fhir/r5/model/Narrative.java#L290)), which is expected. But the R4 ([here](https://github.com/hapifhir/org.hl7.fhir.core/blob/115074ee601f1975e8dcdf924e513ad0c759ff7f/org.hl7.fhir.r4/src/main/java/org/hl7/fhir/r4/model/Narrative.java#L336)) and STU3 ([here](https://github.com/hapifhir/org.hl7.fhir.core/blob/115074ee601f1975e8dcdf924e513ad0c759ff7f/org.hl7.fhir.dstu3/src/main/java/org/hl7/fhir/dstu3/model/Narrative.java#L280)) versions exclude `div`; is this a bug? If not, what is the rationale behind this?

**Comment by grahamegrieve** [comment]
It is a bug, and I fixed it in R5 early in the R5 life cycle. I'm not so keen to 'fix' this in older versions - could be a breaking change for users. Open to discussion (@jamesagnew)

**Comment by bashir2** [comment]
Thanks @grahamegrieve for confirming (and the fix in R5). It would be nice if this can be fixed in older versions too as we rely on this function returning all child elements.

BTW, out of curiosity, I assumed these libraries are somewhat auto-generated from `StructureDefinition` resources, isn't that the case?

**Comment by grahamegrieve** [comment]
@jamesagnew do you have an opinion on fixing older versions? 

Yes, they are code generated from structure definitions

**Comment by jamesagnew** [comment]
Nothing in HAPI-FHIR relies on this method (we rely on the annotations to supply structure information) so this certainly shouldn't break things for any HAPI FHIR users who aren't doing something pretty niche. If they're relying on `listChildren` for structures, presumably they'd be happy for it to return a more complete response.. So I'd say go for it.

As an aside, I notice a typo ("he actual..") in the R4 one:

```java
        children.add(new Property("div", "xhtml", "he actual narrative content, a stripped down version of XHTML", 0, 1, new XhtmlType(this))); 
```

**Comment by bashir2** [comment]
Thanks @grahamegrieve for fixing this. I was trying to upgrade to the new version to be able to use this in our code. But our build failed and it seems that the root cause is that `XhtmlType` is not a `PrimitiveType` ([link](https://github.com/hapifhir/org.hl7.fhir.core/blob/c06051838f9bcd5fc0b552df960f5bf2fcf2dbb4/org.hl7.fhir.r4/src/main/java/org/hl7/fhir/r4/model/XhtmlType.java#L40)). This is in R4 (and earlier?) but not R5 where `XhtmlType` is actually a `PrimitiveType` ([link](https://github.com/hapifhir/org.hl7.fhir.core/blob/c06051838f9bcd5fc0b552df960f5bf2fcf2dbb4/org.hl7.fhir.r5/src/main/java/org/hl7/fhir/r5/model/XhtmlType.java#L43)). Is this a bug or intentional?

ICYW when traversing the StructureDefinition, we get a [`RuntimePrimitiveDatatypeXhtmlHl7OrgDefinition`](https://github.com/hapifhir/hapi-fhir/blob/a52578e798c0f32eafb9804719bb705394029260/hapi-fhir-base/src/main/java/ca/uhn/fhir/context/RuntimePrimitiveDatatypeXhtmlHl7OrgDefinition.java#L27) for `xhtml` elements and that's why we expect an `IPrimitiveType` for `XhtmlType`.

If this is a bug and you want me to open a new issue, please let me know.

**Comment by grahamegrieve** [comment]
I’m not sure whether it’s a hug or why it’s different but make an issue so we have a right place to discuss it

**Comment by bashir2** [comment]
Okay, created #1800.
