### ISSUE TITLE
Validator CLI - Loading of profiles via local file doesn't appear to work

### ISSUE THREAD

**Issue by dotasek** [hapifhir/org.hl7.fhir.core#1686]
When validating a resource using the Validator CLI, including a profile as a local file doesn't work as expected.

For example, I expect the following should work:

```
java -jar validator_cli.jar ./SMILE-6954/Task-task-example-1-dmuylwyk.json -version 4.0.1 -profile /Users/me/IN/2024-07-1-local-profile/SMILE-6954/StructureDefinition-profile-example-task-input-no-slice.json
```

However, it interprets `-profile` arg as the canonical URL instead of the actual URL from within that structure definition. This means that it attempts to find `/Users/me/IN/2024-07-1-local-profile/SMILE-6954/StructureDefinition-profile-example-task-input-no-slice.json` in the context instead of whatever was in the URL field of the structure definition. 

In the [documentation](https://confluence.hl7.org/pages/viewpage.action?pageId=35718580#UsingtheFHIRValidator-Whattovalidateagainst), it's clear that the expected path is to load a full IG first. However, this greatly slows simple reproduction, as then IG packaging must get involved instead of simply validating against a single local file.

Can we put some effort into local file resolution for the `-profile` param?

**Comment by dotasek** [comment]
@dmuylwyk

**Comment by grahamegrieve** [comment]
no, the -profile is always a canonical URL. You use -ig {source} to load the local file
