### ISSUE TITLE
Dstu2 to Dstu3 Conversion

### ISSUE THREAD

**Issue by RokshanJ** [hapifhir/org.hl7.fhir.core#171]
Hi @jamesagnew  I am trying to do some dstu2 to dstu3 conversion. Can you please refer which I can I use?

**Comment by jamesagnew** [comment]
Hi @RokshanJ - Please see this wiki poage, which has lots of good information on how to get help with HAPI FHIR: https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help
