### ISSUE TITLE
ConceptMapValidator uses fetcher without null check

### ISSUE THREAD

**Issue by Boereck** [hapifhir/org.hl7.fhir.core#1724]
Hello,

The method `ConceptMapValidator#validateGroup` uses the `fetcher` field without checking it for `null` first. This causes `NullPointerExceptions` to be raised, when validating ConceptMaps without a configured `fetcher`.
I saw, that a few days ago commit da33791a2311d65ec88aaf790b57e6f2e14eb087 fixed a similar issue in the `ValueSetValidator`.

Best regards,
Max

**Comment by dotasek** [comment]
Null check added, thanks for spotting this.

**Comment by Boereck** [comment]
Well, thanks for fixing it so fast 😎
