### ISSUE TITLE
We probably shouldn't have hard coded directories in the methods to find the FHIR_HOME dir.

### ISSUE THREAD

**Issue by markiantorno** [hapifhir/org.hl7.fhir.core#175]

**Comment by markiantorno** [comment]
In TestUtilities, there is a method to get the home directory:

```
  public static String home() {
    if (fixedpath != null)
     return fixedpath;
    String s = System.getenv("FHIR_HOME");
    if (!Utilities.noString(s))
      return s;
    s = "C:\\work\\org.hl7.fhir\\build";
    if (new File(s).exists())
      return s;
    throw new Error("FHIR Home directory not configured");
  }
```

Having a hard coded C: path here isn't the right approach. We need to accommodate different OS.

I'll fix this, I am just putting it here to remember, because I have the memory of a goldfish.

**Comment by grahamegrieve** [comment]
But how are we going to fix this?

**Comment by markiantorno** [comment]
I fixed this as part of https://github.com/hapifhir/org.hl7.fhir.core/pull/179
