### ISSUE TITLE
Was the fix for XML parsing complete?

### ISSUE THREAD

**Issue by allonsyintensely** [hapifhir/org.hl7.fhir.core#1762]
Looking at #1571, I was wondering if the use of DocumentBuilderFactory.newDocumentBuilder (for example, in

https://github.com/hapifhir/org.hl7.fhir.core/blob/60470b1a28155df059d30ce7754aec568efe4b30/org.hl7.fhir.utilities/src/main/java/org/hl7/fhir/utilities/xml/XMLUtil.java#L440-L443
)
was also vulnerable to XXE attacks. I am curious about why TransformerFactory was fixed, but not DocumentBuilderFactory. I can also provide a PR.

Like in #1571, see https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html#jaxp-documentbuilderfactory-saxparserfactory-and-dom4j.

**Comment by dotasek** [comment]
Could you please open a security advisory in which to discuss the resolution?

https://github.com/hapifhir/org.hl7.fhir.core/security/advisories/new

**Comment by allonsyintensely** [comment]
Absolutely, I've submitted one. Many thanks for fixing this issue.
