### ISSUE TITLE
fhir-test-cases failing: DateTimeUtilTests.testToHumanDisplayLocalTimezone

### ISSUE THREAD

**Issue by oliveregger** [hapifhir/org.hl7.fhir.core#1789]
mvn clean install returns the following error on master:

[INFO] Reactor Summary for HL7 Core Artifacts 6.4.1-SNAPSHOT:

```
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s -- in org.hl7.fhir.utilities.tests.execution.DummyJUnit4Test
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   DateTimeUtilTests.testToHumanDisplayLocalTimezone:76 expected: <04-Feb-2002 00:00:00> but was: <4 Feb 2002, 00:00:00>
[ERROR]   DateTimeUtilTests.testToHumanDisplayLocalTimezone:76 expected: <04-Feb-2002 00:00:00> but was: <4 Feb 2002, 00:00:00>
[ERROR]   DateTimeUtilTests.testToHumanDisplayLocalTimezone:76 expected: <04-Feb-2002 00:00:00> but was: <4 Feb 2002, 00:00:00>
[INFO] 
[ERROR] Tests run: 724, Failures: 3, Errors: 0, Skipped: 5
[INFO] 

```

**Comment by oliveregger** [comment]
[INFO] org.hl7.fhir.r4b ................................... FAILURE [01:03 min]

Follow up error, when removing the above:

[ERROR] Failures: 
[ERROR]   NarrativeGeneratorTests.testDateTimeRendering4:113->checkDateTimeRendering:82 Actual = 19/11/21, 2:13 pm, expected one of ['19/11/21, 2:13 pm' | '19/11/21 2:13 PM'] ==> expected: <true> but was: <false>

**Comment by oliveregger** [comment]
org.hl7.fhir.r5

```
[ERROR] Failures: 
[ERROR]   NarrativeGenerationTests.test:283 Output does not match expected: Text differs at /html/body/div/div/div/div/div/div/p
Expected:": (base64 data - 173,424 base64 chars)" for ex-bin
Actual  :": (base64 data - 173’424 base64 chars)" ==> expected: <true> but was: <false>
[ERROR]   NarrativeGeneratorTests.testDateTimeRendering4:106->checkDateTimeRendering:79 Actual = 19/11/21, 2:13 pm, expected one of ['19/11/21, 2:13 pm' | '19/11/21 2:13 PM']
```

**Comment by grahamegrieve** [comment]
These are because JVMs do not consistently implement date time formats. These tests pass on the JVM used on the ci-build, but not for me locally, and I don't know how to test that functionality without using jvm dependent code

**Comment by oliveregger** [comment]
what jvm is used on the ci-build infrastructure? if i know that I can run it with the same.

**Comment by oliveregger** [comment]
up to jdk17 is used currently, see:

https://github.com/hapifhir/org.hl7.fhir.core/blob/master/pull-request-pipeline.yml
