### ISSUE TITLE
If cache version in packages.ini is not current, new cache version does not get saved.

### ISSUE THREAD

**Issue by jnmeijer** [hapifhir/org.hl7.fhir.core#187]
https://github.com/hapifhir/org.hl7.fhir.core/blob/60947cb7f4829cbe0fbfd61bc33da5e036232ab9/org.hl7.fhir.utilities/src/main/java/org/hl7/fhir/utilities/cache/PackageCacheManager.java#L264

If, in packages.ini, version is not current, the cache is emptied and rebuilt.  However, since the new version number is never saved to packages.ini, the cache is rebuilt (packages are redownloaded) every time.

Suggesting we add ini.save() somewhere in there.

**Comment by grahamegrieve** [comment]
fixed
