### ISSUE TITLE
Validator: Questionnaire error messages

### ISSUE THREAD

**Issue by patrick-werner** [hapifhir/org.hl7.fhir.core#189]
When Validating Questionnaires the reason of an error should always be clear to the implementer.
Current Errors which should be improved:

- que-2:The link ids for groups and questions must be unique within the questionnaire [descendants().linkId.isDistinct()]
_linkId should be visible_
- Error @ Questionnaire.item[10].item[0] : Unable to find target "{0}" for this question enableWhen
_probably a MessageFormatBug_

**Comment by grahamegrieve** [comment]
que-2 is a specification issue.

**Comment by grahamegrieve** [comment]
fix the enableWhen message
