### ISSUE TITLE
add -no-preferred-binding-infos option to Validator

### ISSUE THREAD

**Issue by patrick-werner** [hapifhir/org.hl7.fhir.core#192]
Right now the Validator returns infos like this: 

> Information @ DocumentReference.type (line 7, col8) : None of the codes provided are in the value set http://hl7.org/fhir/ValueSet/c80-doc-typecodes (http://hl7.org/fhir/ValueSet/c80-doc-typecodes), and a code is recommended to come from this value set)

This is irritating to some Implementers if their profile has a required binding to a specific other VS, they are still getting this info.
As a simple workaround this option should suppress all preferred binding infos.

**Comment by grahamegrieve** [comment]
Marking this as closed - use -no-extensible-binding-warnings
