### ISSUE TITLE
Null Pointer Errors in NarrativeGenerator.renderLeaf()

### ISSUE THREAD

**Issue by keithboone** [hapifhir/org.hl7.fhir.core#194]
} else if (e instanceof BooleanType)
      x.addText(((BooleanType) e).getValue().toString());
    else if (e instanceof CodeableConcept) {
      renderCodeableConcept((CodeableConcept) e, x, showCodeDetails);
    } else if (e instanceof Coding) {
      renderCoding((Coding) e, x, showCodeDetails);
    } else if (e instanceof Annotation) {
      renderAnnotation((Annotation) e, x);
    } else if (e instanceof Identifier) {
      renderIdentifier((Identifier) e, x);
    } else if (e instanceof org.hl7.fhir.r5.model.IntegerType) {
      x.addText(Integer.toString(((org.hl7.fhir.r5.model.IntegerType) e).getValue()));
    } else if (e instanceof org.hl7.fhir.r5.model.DecimalType) {
      x.addText(((org.hl7.fhir.r5.model.DecimalType) e).getValue().toString());
    } else if (e instanceof HumanName) {

Should be:
    } else if (e instanceof BooleanType)
      x.addText(((BooleanType) e).getValue());
    else if (e instanceof CodeableConcept) {
      renderCodeableConcept((CodeableConcept) e, x, showCodeDetails);
    } else if (e instanceof Coding) {
      renderCoding((Coding) e, x, showCodeDetails);
    } else if (e instanceof Annotation) {
      renderAnnotation((Annotation) e, x);
    } else if (e instanceof Identifier) {
      renderIdentifier((Identifier) e, x);
    } else if (e instanceof org.hl7.fhir.r5.model.IntegerType) {
      x.addText((org.hl7.fhir.r5.model.IntegerType) e);
    } else if (e instanceof org.hl7.fhir.r5.model.DecimalType) {
      x.addText((org.hl7.fhir.r5.model.DecimalType) e).getValue());
    } else if (e instanceof HumanName) {

And then, to XhtmlNode, add the method:

   public XhtmlNode addText(Object obj) {
      return addText(obj == null ? "" : obj.toString());
   }

If I could have figured out how to build and test this beast, this would have been a pull request, but for some reason, I couldn't get it to find all of the dependencies.

**Comment by grahamegrieve** [comment]
did you load it as a maven project?

**Comment by grahamegrieve** [comment]
can you just confirm - this is when the renderer tries to render something like 

  <status>
    <extension url="blah"> 
     <valueCode value="something else/>
   </extension
  </status>

instead of the usual 

  <status value="code"/>

**Comment by keithboone** [comment]
IntegerType with data-absent-reason extension, but no value, DecimalType with same.

**Comment by grahamegrieve** [comment]
thx. I'm thinking about it. I don't like your proposed fix for style reasons, but we'll have to fix it somehow (also, the code is in the middle of being refactored - moving to org.hl7.fhir.r5.renderers)

**Comment by grahamegrieve** [comment]
I believe that this is fixed now - please check
