### ISSUE TITLE
Fhir Validator is not working with Proxy Settings with username and Password

### ISSUE THREAD

**Issue by revavenky** [hapifhir/org.hl7.fhir.core#204]
Fhir Validator is not working with Proxy Settings having username and Password.
It only supports Proxy without username Password.

I get following error when i use this command in Windows

> java -jar org.hl7.fhir.validator.jar pat.xml -version 4.0.0  -Proxy=http://usr:name@proxy:port

`
.. FHIR Version 4.0, definitions from hl7.fhir.r4.core#4.0.1
.. connect to tx server @ http://tx.fhir.org
Error connecting to build server - running without build (Connection refused: connect)
Exception in thread "main" org.hl7.fhir.exceptions.FHIRException: Unable to resolve package id hl7.fhir.r4.core#4.0.1
    at org.hl7.fhir.utilities.cache.PackageCacheManager.fetchTheOldWay(PackageCacheManager.java:852)
    at org.hl7.fhir.utilities.cache.PackageCacheManager.loadFromPackageServer(PackageCacheManager.java:397)
    at org.hl7.fhir.utilities.cache.PackageCacheManager.loadPackage(PackageCacheManager.java:681)
    at org.hl7.fhir.validation.ValidationEngine.resolvePackage(ValidationEngine.java:649)
    at org.hl7.fhir.validation.ValidationEngine.fetchByPackage(ValidationEngine.java:643)
    at org.hl7.fhir.validation.ValidationEngine.loadIgSource(ValidationEngine.java:477)
    at org.hl7.fhir.validation.ValidationEngine.loadCoreDefinitions(ValidationEngine.java:356)
    at org.hl7.fhir.validation.ValidationEngine.<init>(ValidationEngine.java:337)
    at org.hl7.fhir.validation.cli.services.ValidationService.getValidator(ValidationService.java:169)
    at org.hl7.fhir.validation.Validator.main(Validator.java:175)
`
 
Please look into this issue.

**Comment by CHFJr** [comment]
I am experiencing proxy problems when the Validator accesses http://tx.fhir.org. I am able to download the definitions for hl7.fhir.r4.core#4.0.1, but not the terminology. I use only -Dhttp.proxyHost and -Dhttp.proxyPort settings and the definitions download negotiates with the proxy server to use NTLM for the Proxy-Authorization type.

This is a pretty critical problem for us.

**Comment by CHFJr** [comment]
I swear I left a comment on this earlier this week ... anyway

I am experiencing the same problem running the validator behind a proxy server. When I include -Dhttp.proxyHost and -Dhttp.proxyPort option I am able to access packages (hl7.fhir.r4.core#4.0.1) but not the terminology server. Using WireShark I was able to see the negation between the Validator's JVM and the proxy server; they settled on NTLM. However, when accessing the terminology server, no negotiation occurs. 

Given how new we to all this, we'd really like to be able to valid against the terminology server too. 

Thanks ... Charlie

**Comment by markiantorno** [comment]
I will look into this next week. Sorry for the delay.

**Comment by CHFJr** [comment]
No worries. Thanks for your help with this.

Charlie Filkins | Software Architect
Technology Architecture & Innovation (TAI)
p 860.273.6899
151 Farmington Ave, Hartford, CT, 06156
[CVS]
CONFIDENTIALITY NOTICE: This communication and any attachments may contain confidential and/or privileged information for the use of the designated recipients named above. If you are not the intended recipient, you are hereby notified that you have received this communication in error and that any review, disclosure, dissemination, distribution or copying of it or its contents is prohibited. If you have received this communication in error, please notify the sender immediately by email or telephone and destroy all copies of this communication and any attachments.

**Comment by CHFJr** [comment]
Has this issue been addressed in any of the recent releases to the Validator? I don't see any comments on it.

**Comment by markiantorno** [comment]
It has not been addressed yet. This comment will be updated once a change has been pushed.

**Comment by CHFJr** [comment]
Great. Thank you!

**Comment by markiantorno** [comment]
@CHFJr I submitted a pull request on this: https://github.com/hapifhir/org.hl7.fhir.core/pull/378

Once reviewed and merged, I would appreciate your assistance in ensuring that it meets your needs. I tested locally using basic auth with https://github.com/mitmproxy/mitmproxy, so your milage may vary, depending on your local setup.

**Comment by CHFJr** [comment]
Mark,

I’m happy to help. However, I’m not sure exactly what I need to do. Please send along any instructions.

Thanks … Charlie

Charlie Filkins | Software Architect
Technology Architecture & Innovation (TAI)
p 860.273.6899
151 Farmington Ave, Hartford, CT, 06156
[CVS]
CONFIDENTIALITY NOTICE: This communication and any attachments may contain confidential and/or privileged information for the use of the designated recipients named above. If you are not the intended recipient, you are hereby notified that you have received this communication in error and that any review, disclosure, dissemination, distribution or copying of it or its contents is prohibited. If you have received this communication in error, please notify the sender immediately by email or telephone and destroy all copies of this communication and any attachments.

**Comment by markiantorno** [comment]
Once it's merged and a release is cut (I'll message you to let you know), all you would need to do it use the new validator as you normally would, with the proxy, and then just let me know if everything is working.

So, you don't need to do anything yet. I'll send you a message when everything is merged. I just wanted to give you a heads up.

**Comment by markiantorno** [comment]
Fixed in 5.2.1, please verify.
https://github.com/hapifhir/org.hl7.fhir.core/releases/tag/5.2.1

**Comment by CHFJr** [comment]
@markiantorno Is this the appropriate channel for questions and comments on the 5.2.1 version of the validator? I've started testing and have some questions and concerns.

Thanks ... Charlie

**Comment by markiantorno** [comment]
Any questions can be addressed on Stackoverflow. For bugs and issues, please file them here on Github.
