### ISSUE TITLE
Unable to successfully run mvn install on downloaded or git cloned project

### ISSUE THREAD

**Issue by debashish-github** [hapifhir/org.hl7.fhir.core#212]
Hi,
   I am trying to build the project locally both by using git clone / downloading as zip.
When I try to run mvn install  I get the following error :
[INFO] Scanning for projects...
[WARNING] The POM for org.apache.felix:maven-bundle-plugin:jar:3.5.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[ERROR] Invalid extension descriptor for org.apache.felix:maven-bundle-plugin:3.5.0: zip END header not found
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unknown packaging: bundle @ line 13, column 16
[ERROR] Unknown packaging: bundle @ line 13, column 16
[ERROR] Unknown packaging: bundle @ line 13, column 16
[ERROR] Unknown packaging: bundle @ line 13, column 16
[ERROR] Unknown packaging: bundle @ line 13, column 13
[ERROR] Unknown packaging: bundle @ line 13, column 13
[ERROR] Unknown packaging: bundle @ line 13, column 16
[ERROR] Unknown packaging: bundle @ line 13, column 16
[ERROR] Unknown packaging: bundle @ line 16, column 16
 @
[ERROR] The build could not read 9 projects -> [Help 1]
[ERROR]
[ERROR]   The project ca.uhn.hapi.fhir:org.hl7.fhir.utilities:5.0.6-SNAPSHOT (C:\fhir\org.hl7.fhir.core-master\org.hl7.fhir.utilities\pom.xml) has 1 error
[ERROR]     Unknown packaging: bundle @ line 13, column 16
[ERROR]
[ERROR]   The project ca.uhn.hapi.fhir:org.hl7.fhir.dstu2:5.0.6-SNAPSHOT (C:\fhir\org.hl7.fhir.core-master\org.hl7.fhir.dstu2\pom.xml) has 1 error
[ERROR]     Unknown packaging: bundle @ line 13, column 16
[ERROR]
[ERROR]   The project ca.uhn.hapi.fhir:org.hl7.fhir.dstu2016may:5.0.6-SNAPSHOT (C:\fhir\org.hl7.fhir.core-master\org.hl7.fhir.dstu2016may\pom.xml) has 1 error
[ERROR]     Unknown packaging: bundle @ line 13, column 16
[ERROR]
[ERROR]   The project ca.uhn.hapi.fhir:org.hl7.fhir.dstu3:5.0.6-SNAPSHOT (C:\fhir\org.hl7.fhir.core-master\org.hl7.fhir.dstu3\pom.xml) has 1 error
[ERROR]     Unknown packaging: bundle @ line 13, column 16
[ERROR]
[ERROR]   The project ca.uhn.hapi.fhir:org.hl7.fhir.r4:5.0.6-SNAPSHOT (C:\fhir\org.hl7.fhir.core-master\org.hl7.fhir.r4\pom.xml) has 1 error
[ERROR]     Unknown packaging: bundle @ line 13, column 13
[ERROR]
[ERROR]   The project ca.uhn.hapi.fhir:org.hl7.fhir.r5:5.0.6-SNAPSHOT (C:\fhir\org.hl7.fhir.core-master\org.hl7.fhir.r5\pom.xml) has 1 error
[ERROR]     Unknown packaging: bundle @ line 13, column 13
[ERROR]
[ERROR]   The project ca.uhn.hapi.fhir:org.hl7.fhir.convertors:5.0.6-SNAPSHOT (C:\fhir\org.hl7.fhir.core-master\org.hl7.fhir.convertors\pom.xml) has 1 error
[ERROR]     Unknown packaging: bundle @ line 13, column 16
[ERROR]
[ERROR]   The project ca.uhn.hapi.fhir:org.hl7.fhir.validation:5.0.6-SNAPSHOT (C:\fhir\org.hl7.fhir.core-master\org.hl7.fhir.validation\pom.xml) has 1 error
[ERROR]     Unknown packaging: bundle @ line 13, column 16
[ERROR]
[ERROR]   The project ca.uhn.hapi.fhir:org.hl7.fhir.report:5.0.6-SNAPSHOT (C:\fhir\org.hl7.fhir.core-master\org.hl7.fhir.report\pom.xml) has 1 error
[ERROR]     Unknown packaging: bundle @ line 16, column 16
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

Any help on this is greatly appreciated !

Thanks
Debashish

**Comment by jamesagnew** [comment]
That looks to me like a corrupted ZIP file has snuck into your local Maven
repo.

Try deleting your [home]/.m2 directory and trying again.

If that fails, have a look at of the erroring files (e.g.
C:\fhir\org.hl7.fhir.core-master\org.hl7.fhir.utilities\pom.xml ) and see
if the contents offer any hints.

**Comment by debashish-github** [comment]
Nope I tried crearing out .m2 .. Also tried in a different m/c .. same error . The jar maven-bundle-plugin-3.5.0 seems to be corrupted . I tried opening it and it kept giving the error that it is corrupted. I also tried another version 4.2.1 and it kept giving the same error and that jar too is corrupted. I am using maven 3.6.3  and my JDK is 11.0.3 .. Is there anything else that I have to have ?

Thanks

**Comment by jamesagnew** [comment]
What does the maven-bundle-plugin-3.5.0.jar actually contain? (i.e. how big
is it? how does it look if you open it with a text editor?)

**Comment by debashish-github** [comment]
There definitely seems to be some problem in the way it is downloaded. I only see it about 2 KB . I have attached the textual content .
[maven-bundle-contents.txt](https://github.com/hapifhir/org.hl7.fhir.core/files/4719564/maven-bundle-contents.txt)

**Comment by jamesagnew** [comment]
That file contains the following contents:

https://searchassist.verizon.com/main?ParticipantID=euekiz39ksg8nwp7iqj2fp5wzfwi5q

Assuming you are on Verizon internet, I am betting it's your ISP that is
mangling the response unfortunately.. All you can do is delete the affected
JAR and try again until you get a success

**Comment by debashish-github** [comment]
Found the root cause .. This doesn't happen to all downloads since some of my colleagues were able to successfully download and run mvn install. For my download for some reasons the first pom downloaded C:\m2repo\ca\uhn\hapi\fhir\hapi-fhir\4.2.0\hapi-fhir-4.2.0.pom was refering to incorrect plugin repository 

		<pluginRepository>
			<id>maven2</id>
			<name>Maven2</name>
			<url>http://central.maven.org/maven2/</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</pluginRepository>

It took a while for me to manually fix this to point to repo https://repo.maven.apache.org/maven2/ to make this work. Can this be fixed so that others don't end up  with the same issue I had ?

**Comment by markiantorno** [comment]
@debashish-github this should not still be an issue since the automated build process was put in place.
