### ISSUE TITLE
Running the tool Validator.java doesn't yield results when trying to convert from stu3 to R4

### ISSUE THREAD

**Issue by debashish-github** [hapifhir/org.hl7.fhir.core#221]
Hi,
   Currently we are looking for Fhir -> Fhir convertor as well as Fhir -> Native(proprietory formats) convertors . We want to host the Fhir server and are currently in process of evaluating different options preferably in java to solve this . We did explore the experimental version of Hapi Fhir convertors .
But this option using stucturedModels and Maps ( using Fhir mapping language) looks more promising  since it allows conversion using maps ( which I think can be customized but most of them are out of the box available ) .

I followed the instructions mentioned in the confluence page  https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator#UsingtheFHIRValidator-VersionConversion
While trying to convert from version 3.0 to 4.0 version it keeps giving me the attached error .
[Stu3_to_R4_Conversion_Error_using_Maps.txt](https://github.com/hapifhir/org.hl7.fhir.core/files/4736694/Stu3_to_R4_Conversion_Error_using_Maps.txt)

The input to the file is also attached..
[fhir_condition_epic_stu3_searched.txt](https://github.com/hapifhir/org.hl7.fhir.core/files/4736730/fhir_condition_epic_stu3_searched.txt)

Also I see that while running the tool I see it tries to connect to the server http://tx.fhir.org to download the version definitions . Is this a one time thing ? I am assuming when it is actually used as a server this call happens only the first time and then cached ? Is my assumption correct ?

Any help on these topics is greatly appreciated !

Thanks..

**Comment by markiantorno** [comment]
This isn't really an issue with the library or codebase, and is more asking for assistance and guidance.

Please join the Zulip chat group here: https://chat.fhir.org/

There you can ask for assistance from the community with your issue. Or post on stackoverflow for details and advice on how to set up a solution that will suit your needs.

If you have an explicit error you think is not valid, please post the error you are encountering, the expected output/behaviour, and the steps to reproduce. I'll be happy to assist. 

Keep issues limited to one topic/post if possible.
