### ISSUE TITLE
Converting from R3 to R4 version using custom maps

### ISSUE THREAD

**Issue by debashish-github** [hapifhir/org.hl7.fhir.core#224]
Hi,
   I am using the Validator.java to convert between the two versions R3 and R4 . 
I use the following command line arguments and it works fine
c:\fhirmessages\fhir_condition_epic_stu3_searched.json -version 3.0 -to-version 4.0 -output c:\fhirmessages\fhir_condition_epic_r4_searched_output.json -do-native

Now what if the conversion doesn't support few extension parameters that were added .. Or may be the map doesn't do some of the conversions as expected . Hence I was trying to explore if we can ask the tool to use a custom Map edited by me to do the conversion instead of the default .
So I tried the command 

c:\fhirmessages\fhir_condition_epic_stu3_searched.json -version 3.0 -to-version 4.0 -output c:\fhirmessages\fhir_condition_epic_r4_searched_output.json -do-native -ig C:\fhirmessages\maps

In the maps folder I downloaded the Condition.map from https://raw.githubusercontent.com/FHIR/packages/master/interversion/r4/R3toR4/Condition.map and edited the contents to change the mapping of src.assertedDate -> tgt.recordedDate; to src.assertedDate -> tgt.tempDate;

I didn't convert the assertedDate to tempDate neither did it give any error  and generated the output using default map . 

Is there something that I am missing here ?

Thanks

**Comment by markiantorno** [comment]
Alright, so we've done some major changes to the conversion libraries that will be in the next release.

Details are here: https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.convertors/CONVERTORS.md

Specifically for your issue, you can create a custom conversion advisor that handles extensions for resources in the way you need for your specific usecase.

I'll make this as closed for now. Once we release 5.4.10. please read the instructions and try your custom conversion.
