### ISSUE TITLE
Need sequence diagrams for the Validator tool

### ISSUE THREAD

**Issue by debashish-github** [hapifhir/org.hl7.fhir.core#229]
Hi, 
   I am trying to evaluate this tool to realize some fhir -> fhir and fhir -> native converstions. We really like this concept of being able to do this through maps written in fhir mapping langauge .
We are trying to evalute this tool in terms of its performance hence it would be great if we could get hold of some sequence digrams on the flow when the tool is run.
On running locally I see it tries to connect to server http://tx.fhir.org for some code validation. Need to understand this and the completely flow that will give us confidence in going forward with this tool for our fhir conversion.

Any help on this is greatly appreciated !

Thanks

**Comment by grahamegrieve** [comment]
I'm sure what you have in mind by 'sequence' diagrams. Got any examples to illustrate?

It does depend on a terminology server. You can run a local terminology server if you want, and then just specify it's location by -tx parameter
