### ISSUE TITLE
Validator web client has wrong web port :8080 instead of default 8081

### ISSUE THREAD

**Issue by Yididya** [hapifhir/org.hl7.fhir.core#231]
Port 8081 is used as a `GUI_FRONT_END_PORT` inside ValidatorGui class 
https://github.com/hapifhir/org.hl7.fhir.core/blob/77d2cc394db91f5fd7275c20b4d08dbe7526540b/org.hl7.fhir.validation/src/main/java/org/hl7/fhir/validation/cli/ValidatorGui.java#L16

Where the client specifies 8080 in the address for the validator REST endpoint

https://github.com/hapifhir/org.hl7.fhir.core/blob/77d2cc394db91f5fd7275c20b4d08dbe7526540b/org.hl7.fhir.validation/src/main/resources/public/main.js#L141

hence, rendering all API hits unreachable. 

Is there a way to configurate the port?

**Comment by grahamegrieve** [comment]
@markiantorno

**Comment by markiantorno** [comment]
This is no longer an issue, as the validator has been moved to a new project.
