### ISSUE TITLE
EnableWhenEvaluator.java handles path-evaluation extensions as normal extensions, not modifiers

### ISSUE THREAD

**Issue by eevaturkka** [hapifhir/org.hl7.fhir.core#234]
In the EnableWhenEvaluator at line 157 fwd:

``  private boolean hasExpressionExtension(QuestionnaireItemComponent qitem) {
    return qitem.hasExtension("http://phr.kanta.fi/StructureDefinition/fiphr-ext-questionnaire-enablewhen") || // finnish extension 
      qitem.hasExtension("http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-enableWhenExpression"); // sdc extension
  }

  private String getExpression(QuestionnaireItemComponent qitem) {
    if (qitem.hasExtension("http://phr.kanta.fi/StructureDefinition/fiphr-ext-questionnaire-enablewhen"))
      return qitem.getExtensionString("http://phr.kanta.fi/StructureDefinition/fiphr-ext-questionnaire-enablewhen");
    if (qitem.hasExtension("http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-enableWhenExpression")) {
``

The extension http://phr.kanta.fi/StructureDefinition/fiphr-ext-questionnaire-enablewhen is modifierExtension and should be checked with hasModifierExtension (as the reference to it should be in the item's "modifierExtension" -field) - and shouldn't the other one as well since their existence changes behaviour?

**Comment by grahamegrieve** [comment]
the definition of modifierExtensions is that they change the meaning of the containing element, not that they change the behavior. (else what isn't a modifier?). But this was clarified in R4 and was still not clear in R3. See this PR: https://github.com/hapifhir/org.hl7.fhir.core/pull/237

**Comment by grahamegrieve** [comment]
Fixed by checking modifierExtensions when looking for the enableWhen extension

**Comment by eevaturkka** [comment]
Thank you for the quick fix!
