### ISSUE TITLE
Version converter for ExplanationOfBenefit from r3 to r4  

### ISSUE THREAD

**Issue by rohithZE** [hapifhir/org.hl7.fhir.core#244]
Hi @jamesagnew 
We are looking for a converter from version r3 to r4 for resource ExplanantionOfBenefit.
There are converters for many other resources for version r3 to r4 and there is also a converter for ExplanationOfBenefit from r4 to r5. 
Any plans of adding converters for ExplanationOfBenefit r3 to r4 converters?
Let me know if I've overlooked something.
Thanks!

**Comment by ccorley** [comment]
I also am looking for the same converter.  Any guidance on this would be appreciated.

**Comment by ItayGoren** [comment]
Hey @rohithZE @ccorley,
I can add support for it in one of the next days but can you first attach one entry for example? I'll write the tests based on it and compare the results. The comparing is a manual process, thus you should take a look at couple of them as well to make sure no rule was missed.

**Comment by ccorley** [comment]
This is great news.  I should be able to post a sample tomorrow from the CMS Blue Button 2.0 sample data.

**Comment by ccorley** [comment]
Sample EOB json from CMS Blue Button 2.0 sandbox environment: 
[SampleEOB.json.txt](https://github.com/hapifhir/org.hl7.fhir.core/files/5157513/SampleEOB.json.txt)

**Comment by grahamegrieve** [comment]
@ItayGoren I don't recall whether I saw a PR for this? Is it still on your todo?
