### ISSUE TITLE
Overly zealous validation of CodeSystem.valueSet definition

### ISSUE THREAD

**Issue by lawley** [hapifhir/org.hl7.fhir.core#25]
The InstanceValidator imposes the following rules on the default "all codes in the system" ValueSet of a CodeSystem:

`vs.hasCompose() && !vs.hasExpansion(), "CodeSystem "+url+" has a 'all system' value set of "+vsu+", but it is an expansion"`
Why is no expansion allowed? We stumbled across this because we include the valueset-unclosed extension by default, and this extension goes on the expansion element.

`vs.getCompose().getInclude().size() == 1, "CodeSystem "+url+" has a 'all system' value set of "+vsu+", but doesn't have a single include"`
This might be a problem in case the CodeSystem is some kind of composite as is commonly seen with OWL-based terminologies. Granted a canonical "all codes" ValueSet definition should only require a single include that specifies the system URI (and possibly the version as well), but there may be other semantically equivalent definitions that convey useful information to a person.

`vs.getCompose().getInclude().get(0).getSystem().equals(url), "CodeSystem "+url+" has a 'all system' value set of "+vsu+", but doesn't have a matching system ("+vs.getCompose().getInclude().get(0).getSystem()+")"`
See point above.

`!vs.getCompose().getInclude().get(0).hasValueSet() && !vs.getCompose().getInclude().get(0).hasConcept() && !vs.getCompose().getInclude().get(0).hasFilter(), "CodeSystem "+url+" has a 'all system' value set of "+vsu+", but the include has extra details"`
Again, we ran into this because we included an explicit filter condition with the SNOMED ECL expression "*". Why should validation exclude this possibility?

**Comment by grahamegrieve** [comment]
fixed
