### ISSUE TITLE
Validator CLI Release 5.0.7 is for the 5.0.8 Version

### ISSUE THREAD

**Issue by radamson** [hapifhir/org.hl7.fhir.core#275]
# Problem

The 5.0.7 Release `validator_cli.jar` release asset downloads version 5.0.8 of the jar.

## Steps to reproduce

- Download the 5.0.7 validation CLI Jar: https://github.com/hapifhir/org.hl7.fhir.core/releases/download/5.0.7/validator_cli.jar
- In the directory of the download run `java -jar validator_cli.jar -version`

What I see: `FHIR Validation tool Version 5.0.8-SNAPSHOT (Git# 49c35b1de2bd). Built 2020-06-16T14:06:55.319-04:00 (29 days old)`

## Notes

I'm not sure if this can be easily fixed, but just wanted to make sure you were aware of it.

Also, I love the new release system!  Being able to test old versions and see what changed easily is awesome.

**Comment by markiantorno** [comment]
Oh, this is just a labelling issue. The release is correct, the version label internally is just wrong. I'll fix this tomorrow. Sorry about that.

**Comment by radamson** [comment]
No problem at all.  Just trying to help out (in a very, very, very small way).

**Comment by markiantorno** [comment]
There was a pipeline fix that went in about a week or so ago to better order jobs during a release. It should address this issue. Let's see if this is still present in the next release.

**Comment by grahamegrieve** [comment]
Resolved now?

**Comment by radamson** [comment]
Looks good for the 5.0.15 Release:

`FHIR Validation tool Version 5.0.15 (Git# c55982c47b56). Built 2020-07-27T15:33:35.839Z (5 hours old)`

@markiantorno Is there a PR we can link to this issue?  It would be helpful as I try and get more familiar with the codebase.

Either way I'll close this issue because it seems to have been resolved for the latest releases.

**Comment by markiantorno** [comment]
Unfortunately, there's no pull request that can be associated with this. The changes that caused the naming to be corrected exist in the build pipelines themselves, which are hosted on Azure.

**Comment by markiantorno** [comment]
If you are interested in learning more about the pipelines and how they work, I would be more than happy to walk you through it. Just set up a time with me, markiantorno@gmail.com.

**Comment by radamson** [comment]
Ahh gotcha, I was imagining something similar to Travis or Circle CI where the changes are mostly confined to a configuration file in the repo.
