### ISSUE TITLE
Validator should have option to expose "Slicing Information"

### ISSUE THREAD

**Issue by lmckenzi** [hapifhir/org.hl7.fhir.core#283]
When we run the publisher and there's a slicing issue, we get a handy-dandy 'Slicing Information' entry to help figure out what's going on. It would be nice if there was a configuration option (perhaps on by default) that would spit out the same information when validating an instance. (We wouldn't want it all the time - at runtime, that would be unnecessary noise. But when debugging, it's super-helpful.

**Comment by grahamegrieve** [comment]
ok. added parameter -html-output
