### ISSUE TITLE
Validator isn't checking right profiles for contained, Parameters resources

### ISSUE THREAD

**Issue by lmckenzi** [hapifhir/org.hl7.fhir.core#288]
Example: https://build.fhir.org/ig/HL7/davinci-ehrx/qa.html#_scratch_ig-build-temp-9XQOHN_repo_input_examples_parameters-member-match-in

The profile declared for the example in the IG is http://hl7.org/fhir/us/davinci-hrex/StructureDefinition/hrex-parameters-member-match-in.  That profile clearly declares a 'profile' for 'oldCoverage' and 'newCoverage' of http://hl7.org/fhir/us/davinci-hrex/StructureDefinition/hrex-coverage.  And that profile, in turn, declares that beneficiary must be http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient.  However, according to the info messages, it's only being validated against http://hl7.org/fhir/StructureDefinition/Patient.

As well, the hrex-coverage profile declares that Coverage.payor is to be http://hl7.org/fhir/us/davinci-hrex/StructureDefinition/hrex-organization.  However, the contained Organization within the oldCoverage and newCoverage occurrences which are both referenced by Coverage.payor are, according to the comments, only being validated against http://hl7.org/fhir/StructureDefinition/Organization, not http://hl7.org/fhir/us/davinci-hrex/StructureDefinition/hrex-organization.

**Comment by grahamegrieve** [comment]
ok fixed next release
