### ISSUE TITLE
NPE while parsing array typed primitive elements with extensions but no value

### ISSUE THREAD

**Issue by vtumuluri** [hapifhir/org.hl7.fhir.core#297]
The STU3 `JsonParser` is unable to parse null values within arrays and throws a NullPointerException. This occurs when reading back resources that have been written using RI/HAPI when the resource contains a repeating/array-typed primitive element with no value but has extension(s). For example, timingTiming.event in http://hl7.org/fhir/stu3/activitydefinition-example.json.html. This is fixed in R5 parser but is not back ported to R3/R4. It would be really appreciated if it could be back ported to STU3 (and also R4).

**Comment by grahamegrieve** [comment]
the test in the PR https://github.com/hapifhir/org.hl7.fhir.core/pull/298 parses that example as found in https://github.com/FHIR/fhir-test-cases/blob/master/r3/ActivityDefinition-referralPrimaryCareMentalHealth.json just fine. If you think there's a problem, make a PR to the tests case code or the test case source to demonstrate the problem

**Comment by vtumuluri** [comment]
The test resource has a typo at `timingTiming1. It had `timingTiming.ëvent` instead of `timingTiming.event`. Once that is changed the issue occurs. Let me send both the PRs.

**Comment by vtumuluri** [comment]
@grahamegrieve : Submitted PR #301  in this repo and [PR #66](https://github.com/FHIR/fhir-test-cases/pull/66) in the FHIR-test-cases repo.

**Comment by grahamegrieve** [comment]
thanks. fixed in https://github.com/hapifhir/org.hl7.fhir.core/pull/303
