### ISSUE TITLE
Loading the same IG multiple times into the ValidationEngine class causes heap size increase

### ISSUE THREAD

**Issue by okeefm** [hapifhir/org.hl7.fhir.core#302]
Hello,

While working with the `org.hl7.fhir.validation.ValidationEngine` class, we noticed that loading the same IG multiple times, using the `loadIg(String src, boolean recursive)` function, causes the used heap space to grow quite a bit each time. We were expecting the `loadIg` method to be idempotent.

We've created a small repo to demonstrate what we were seeing, it's available at https://github.com/inferno-community/test_load_ig. If you download that repository and run `./gradlew run`, you'll see the results of calling `loadIg` 10 times on the same ValidationEngine. 

A run on my machine looks like this.
<img width="543" alt="Screen Shot 2020-08-11 at 12 43 18 PM" src="https://user-images.githubusercontent.com/49001/89926949-99044e00-dbd3-11ea-8826-a19b9ffc3c59.png">

**Comment by grahamegrieve** [comment]
fixed in https://github.com/hapifhir/org.hl7.fhir.core/pull/304
