### ISSUE TITLE
Changing data types to markdown approved during FHIR-I

### ISSUE THREAD

**Issue by seanmcilvenna** [hapifhir/org.hl7.fhir.core#310]
Please see the following two tickets:
https://jira.hl7.org/browse/FHIR-28141
https://jira.hl7.org/browse/FHIR-28140
These two issues describe a number of properties that will be converted to "markdown" in R5.
However, the HL7 C-CDA Web Publishing project could benefit from having the tooling updated to render these properties as markdown prior to R5 being released.

**Comment by lmckenzi** [comment]
Please submit a Git issue against the base publishing template rather than the publisher.
