### ISSUE TITLE
Fault in snapshotgeneration

### ISSUE THREAD

**Issue by mmreith** [hapifhir/org.hl7.fhir.core#317]
author is generally 1..* in a Composition, but a slice could have a cardinality of 0..1 (0..*). The minimum cardinality in the snapshot is always 1, which is faulty

CLI Validator 5.1.5

![image](https://user-images.githubusercontent.com/48082455/91202422-18c90700-e702-11ea-8dd8-ff30722d57da.png)

    <element id="Composition.author:PRF">
      <path value="Composition.author"/>
      <sliceName value="PRF"/>
      <short value="Who and/or what authored the composition"/>
      <definition value="Identifies who is responsible for the information in the composition, not necessarily who typed it in."/>
      <requirements value="Identifies who is responsible for the content."/>
      **<min value="1"/>**
      <max value="*"/>

**Comment by grahamegrieve** [comment]
I fixed this as part of another. reopen with a test case if there's s still a problem
