### ISSUE TITLE
FHIRPath slice() function

### ISSUE THREAD

**Issue by jason-crowley** [hapifhir/org.hl7.fhir.core#323]
I found out about the FHIRPath slice() function from [this webpage](https://www.hl7.org/fhir/fhirpath.html), but when I tried to use it by evaluating the path
```
slice('http://hl7.org/fhir/us/core/StructureDefinition/us-core-provenance','Provenance.agent:ProvenanceAuthor')
```
using the `FHIRPathEngine`, I got an error saying
```
org.hl7.fhir.r4.utils.FHIRLexer$FHIRLexerException: Error in ?? at 1, 1: The name slice is not a valid function name
```
Are there any plans to support the slice() function in the future? Thanks!

**Comment by grahamegrieve** [comment]
yes I need to implement it. Do you have a test case for it?
