### ISSUE TITLE
Fault in Validation of meta.profile 

### ISSUE THREAD

**Issue by mmreith** [hapifhir/org.hl7.fhir.core#335]
we are profiling the meta.profile element directly (yes it is not very usual, but should not lead to a problem)

CLI-Validator 5.1.6
    
`<element id="Encounter.meta.profile">
      <path value="Encounter.meta.profile" />
      <min value="1" />
      <max value="1" />
      <type>
        <code value="canonical" />
        <targetProfile value="https://fhir.kbv.de/StructureDefinition/KBV_PR_AW_Begegnung|1.2.0" />
      </type>
   </element>`

this leads to a validationproblem:

Exception in thread "main" org.hl7.fhir.exceptions.FHIRException: Fehler bei https://fhir.kbv.de/StructureDefinition/KBV_PR_AW_Begegnung#Encounter.meta.profile: Das Zielprofil null ist keine gültiges constrain auf die Basis ([CanonicalType[http://hl7.org/fhir/StructureDefinition/StructureDefinition]])
        at org.hl7.fhir.r5.conformance.ProfileUtilities.checkTypeDerivation(ProfileUtilities.java:2789)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.updateFromDefinition(ProfileUtilities.java:2655)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.processPaths(ProfileUtilities.java:978)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.processPaths(ProfileUtilities.java:1035)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.generateSnapshot(ProfileUtilities.java:539)
        at org.hl7.fhir.validation.ValidationEngine.snapshot(ValidationEngine.java:1530)
        at org.hl7.fhir.validation.cli.services.ValidationService.generateSnapshot(ValidationService.java:123)
        at org.hl7.fhir.validation.Validator.main(Validator.java:192)

Exception in https://fhir.kbv.de/StructureDefinition/KBV_PR_AW_Begegnung#Encounter.meta.profile:  targetprofile null has no valid constrain on base ([CanonicalType[http://hl7.org/fhir/StructureDefinition/StructureDefinition]]) (free translation from german to english)

**Comment by grahamegrieve** [comment]
I'm not sure I follow this. What are you trying to do? Why profile it? I think you've made a mistake because I think that the validator is correct here. What goes in meta.profile is a profile reference. You're trying to change it to a reference to an encounter

**Comment by mmreith** [comment]
Hey,

we are trying to make things more clear to an implementer, so we are profiling the meta.profile. By analysing the profile he knows which things he should write into an instance. And we want him to use the | symbol, since we have to reference to a specific version of a profile without having any package reference/information in the context of usage.

This worked without any problems up to now (STU3/R4) and the firely validator is having no problem also.

Url of profile = https://fhir.kbv.de/StructureDefinition/KBV_PR_AW_Begegnung
type of profile = Encounter
version of profile = 1.2.0
meta.profile = https://fhir.kbv.de/StructureDefinition/KBV_PR_AW_Begegnung|1.2.0

I think the validator is resolving this meta.profile reference, but in my opinion it is just a "string"...



`<StructureDefinition xmlns="http://hl7.org/fhir">
  <url value="https://fhir.kbv.de/StructureDefinition/KBV_PR_AW_Begegnung" />
  <version value="1.2.0" />
  <name value="KBV_PR_AW_Begegnung" />
...
  <kind value="resource" />
  <abstract value="false" />
  <type value="Encounter" />
  <baseDefinition value="http://hl7.org/fhir/StructureDefinition/Encounter" />
  <derivation value="constraint" />
  <differential>
    <element id="Encounter">
      <path value="Encounter" />
    </element>
    <element id="Encounter.id">
      <path value="Encounter.id" />
      <min value="1" />
    </element>
    <element id="Encounter.meta">
      <path value="Encounter.meta" />
      <min value="1" />
    </element>
    <element id="Encounter.meta.versionId">
      <path value="Encounter.meta.versionId" />
      <min value="1" />
    </element>
    <element id="Encounter.meta.lastUpdated">
      <path value="Encounter.meta.lastUpdated" />
      <min value="1" />
    </element>
    <element id="Encounter.meta.profile">
      <path value="Encounter.meta.profile" />
      <min value="1" />
      <max value="1" />
      <type>
        <code value="canonical" />
        <targetProfile value="https://fhir.kbv.de/StructureDefinition/KBV_PR_AW_Begegnung|1.2.0" />
      </type>
    </element>
    <element id="Encounter.text">
      <path value="Encounter.text" />
      <min value="1" />
    </element>`

**Comment by mmreith** [comment]
In 5.1.12 it seems to work properly

**Comment by mmreith** [comment]
In 5.1.12 it seems to work properly

**Comment by mmreith** [comment]
Sorry it is not working properly all the time. 

 Get set... Unable to generate snapshot for KBV_PR_AW_Krebsfrueherkennung_Befund_Rektum_Kolon from Observation because Profil KBV_PR_AW_Krebsfrueherkennung_Befund_Rektum_Kolon (https://fhir.kbv.de/StructureDefinition/KBV_PR_AW_Krebsfrueherkennung_Befund_Rektum_Kolon). Fehler bei der Erstellung des Snapshots
org.hl7.fhir.exceptions.DefinitionException: Profil KBV_PR_AW_Krebsfrueherkennung_Befund_Rektum_Kolon (https://fhir.kbv.de/StructureDefinition/KBV_PR_AW_Krebsfrueherkennung_Befund_Rektum_Kolon). Fehler bei der Erstellung des Snapshots
        at org.hl7.fhir.r5.context.SimpleWorkerContext.generateSnapshot(SimpleWorkerContext.java:781)
        at org.hl7.fhir.r5.context.SimpleWorkerContext.generateSnapshot(SimpleWorkerContext.java:752)
        at org.hl7.fhir.r5.context.SimpleWorkerContext.allStructures(SimpleWorkerContext.java:635)
        at org.hl7.fhir.validation.ValidationEngine.prepare(ValidationEngine.java:1606)
        at org.hl7.fhir.validation.cli.services.ValidationService.getValidator(ValidationService.java:221)
        at org.hl7.fhir.validation.Validator.main(Validator.java:186)
 go (00:00.0515)

Profile =Test1 Example=Test1_Example
[Test1.txt](https://github.com/hapifhir/org.hl7.fhir.core/files/5259302/Test1.txt)
[Test1_Example.txt](https://github.com/hapifhir/org.hl7.fhir.core/files/5259304/Test1_Example.txt)

**Comment by grahamegrieve** [comment]
I think it is working properly at this time. See discussion on https://chat.fhir.org/#narrow/stream/179177-conformance/topic/Profiling.20.2Emeta.2Eprofile

**Comment by mmreith** [comment]
I found the error: Forge was doing things like this...

    <element id="Observation.meta.profile">
      <path value="Observation.meta.profile" />
      <min value="1" />
      <max value="1" />
     <type>
        <code value="canonical" />
        <targetProfile value="https://fhir.kbv.de/StructureDefinition/KBV_PR_AW_Krebsfrueherkennung_Befund_Rektum_Kolon|1.2.0" />
      </type>
    </element>

but correct is:

`<fixedCanonical` value="https://fhir.kbv.de/StructureDefinition/KBV_PR_AW_Krebsfrueherkennung_Befund_Rektum_Kolon|1.2.0" />
