### ISSUE TITLE
org.hl7.fhir.r4.utils.FHIRLexer needs to handle comments better

### ISSUE THREAD

**Issue by keithboone** [hapifhir/org.hl7.fhir.core#344]
If I start an expression with a multiline comment like this:

```
  // This is a multi line comment using // that
  //  will fail during parsing
```

Or include a comment after a ( like this
```
  .where( // Another failure case
```

The parser complains about the comments.

Looking through FHIRLexer, it handles comments and whitespace separately.

It should:
1.  skip whitespace
2.  if there's any sort of comment
    * skip the comment and go back to step 1
3.  look for other tokens

I also so NO handling for /* comments */ in FHIRLexer.

**Comment by grahamegrieve** [comment]
I added several tests around this, and fixed the code, so I think this is all fine now.
