### ISSUE TITLE
Validator unexpectedly erroring when terminology is disabled

### ISSUE THREAD

**Issue by lxbrown** [hapifhir/org.hl7.fhir.core#352]
## The issue
Consider the case where a profile uses a ValueSet which includes a code system not defined in the ImplementationGuide (for example, LOINC).

[Here's an instance](https://www.hl7.org/fhir/us/core/ValueSet-us-core-diagnosticreport-lab-codes.html) in USCore where this is done, within [this profile](https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-diagnosticreport-lab.html).

Trying to validate a resource against this profile will result in a terminology error/warning, even if terminology is disabled:
```Warning @ DiagnosticReport.code (line 26, col16) : None of the codes provided are in the value set http://hl7.org/fhir/us/core/ValueSet/us-core-diagnosticreport-lab-codes (http://hl7.org/fhir/us/core/ValueSet/us-core-diagnosticreport-lab-codes), and a code should come from this value set unless it has no suitable code) (codes = http://loinc.org#58410-2)```

In the case of this profile, the ValueSet is listed as Extensible, which means this is only flagged as a *warning*. I found this testing out a custom profile which has the ValueSet listed as Required, and I can confirm this manifests as an *error* in that case. That's my real concern. :)

## To reproduce
Run this command:
```java -jar validator_cli.jar DiagnosticReport-cbc.json -ig hl7.fhir.us.core#3.1.0 -version 4.0 -tx n/a```
Using this file: https://www.hl7.org/fhir/us/core/DiagnosticReport-cbc.json

## Expected behavior
I would expect to see no error reported if a CodeSystem from a ValueSet is not found in the ValidationEngine. An informational message could be included, saying the code could not be validated against the CodeSystem, since it couldn't be found.

**Comment by grahamegrieve** [comment]
fair enough. I changed it to just a hint when running without a terminology server
