### ISSUE TITLE
Guidance on using Validator

### ISSUE THREAD

**Issue by timharsch** [hapifhir/org.hl7.fhir.core#354]
Is there a way to use the validator in a high throughput way locally?  I'm looking at org.hl7.fhir.validation.cli, but there is no README and trying to answer the question by reading the code is taking a bit of effort.

I guess what I would like to do is to run it as a service of some kind.  Perhaps just a simple web server that accepts the FHIR resource on HTTPS and returns a JSON result of the FHIR conformance of the supplied resource?   Obviously, if it were accepting patient data it would have to be secured but assuming that it were, is it possible?

**Comment by grahamegrieve** [comment]
We're working on this - check https://github.com/hapifhir/org.hl7.fhir.validator-wrapper.
