### ISSUE TITLE
Missing conversion for CarePlan in FHIR specification

### ISSUE THREAD

**Issue by ItayGoren** [hapifhir/org.hl7.fhir.core#367]
While trying to convert a resource `CarePlan` from `DSTU2` to `R4` an assertion was raised in my code: "missing value for intent". Indeed, `intent` is specified by FHIR to contain exactly 1 value (1..1).
Yet, looking at the conversion from `DSTU2` to `STU3`, there is no specification about default value for `intent` in the `STU3` resource.
Moreover, looking at the official conversion page:
http://hl7.org/fhir/stu3/careplan-version-maps.html
we can see that under the "R3 Validation Error" section, the same error is raised.

What is the official solution to convert this resource?
Although the specification doesn't promise backward compatible for the draft versions, DSTU2 is still wildly in use. Providers would want to convert all of their code to R4 and we should be prepare for it.

**Comment by markiantorno** [comment]
Thanks for taking the time to include details for the issue.

I've reviewed what you've sent, and from what I see, you're trying to convert between a version that has no intent field (DSTU2), to a version that both has an intent field, and the field is mandatory (R4).

What you're asking would involve assigning some pre-determined value to a field that was not populated in the original resource? I don't think that would be the correct approach here, as then we would be introducing data where no such original data exists. If this is a requirement for your current project, I would suggest you handle this case within your application, and assign the intent manually during conversion.

From what I can tell the conversion is working as intended in the specification. I would not mark this as an issue.

**Comment by markiantorno** [comment]
@ItayGoren Also, I forgot to mention, if you want to further discuss the actual underlying issue with the spec, and not the java implementation, feel free to post in the implementers channel on Zulip: https://chat.fhir.org/#narrow/stream/179166-implementers
