### ISSUE TITLE
NPE when AdministrativeGender is Enumeration[null]

### ISSUE THREAD

**Issue by kristof-taveirne** [hapifhir/org.hl7.fhir.core#373]
Hi,

When converting from dSTU2 to STU3, I'm getting an NPE on a missing AdministrativeGender.

The resource causing the issue (coming from the Cerner Ignite sandbox) is:
` {
            "fullUrl": "https://fhir-ehr-code.cerner.com/dstu2/ec2458f2-1e24-41c8-b71b-0e701af7583d/Patient/12743884",
            "resource": {
                "resourceType": "Patient",
                "id": "12743884",
                "meta": {
                    "versionId": "0",
                    "lastUpdated": "2020-09-15T06:35:01.000Z"
                },
                "text": {
                    "status": "generated",
                    "div": "<div><p><b>Patient</b></p><p><b>Name</b>: Dawg, Joel</p><p><b>DOB</b>: Nov 11, 1991</p><p><b>Status</b>: Active</p></div>"
                },
                "identifier": [
                    {
                        "use": "usual",
                        "type": {
                            "coding": [
                                {
                                    "system": "http://hl7.org/fhir/v2/0203",
                                    "code": "MR",
                                    "display": "Medical record number",
                                    "userSelected": false
                                }
                            ],
                            "text": "MRN"
                        },
                        "system": "urn:oid:2.16.840.1.113883.6.1000",
                        "value": "7690",
                        "_value": {
                            "extension": [
                                {
                                    "url": "http://hl7.org/fhir/StructureDefinition/rendered-value",
                                    "valueString": "00000007690"
                                }
                            ]
                        },
                        "period": {
                            "start": "2020-09-15T06:35:01.000Z"
                        }
                    },
                    {
                        "use": "usual",
                        "type": {
                            "text": "Military Id"
                        },
                        "system": "urn:oid:2.16.840.1.113883.3.42.10001.100001.12",
                        "value": "10050007740",
                        "_value": {
                            "extension": [
                                {
                                    "url": "http://hl7.org/fhir/StructureDefinition/rendered-value",
                                    "valueString": "10050007740"
                                }
                            ]
                        },
                        "period": {
                            "start": "2020-09-15T06:35:01.000Z"
                        }
                    }
                ],
                "active": true,
                "name": [
                    {
                        "use": "official",
                        "text": "Dawg, Joel",
                        "family": [
                            "Dawg"
                        ],
                        "given": [
                            "Joel"
                        ]
                    }
                ],
                "telecom": [
                    {
                        "system": "phone",
                        "value": "3075557575",
                        "use": "home"
                    },
                    {
                        "system": "email",
                        "value": "amitabhp@mindfiresolutions.com",
                        "use": "work"
                    }
                ],
                "_gender": {
                    "extension": [
                        {
                            "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
                            "valueCode": "unknown"
                        }
                    ]
                },
                "birthDate": "1991-11-11"
            }
        },`

The bug appears to be in VersionConverter_10_30 on line 3869 (org.hl7.fhir.convertors-5.1.0.jar).
`            switch((org.hl7.fhir.dstu2.model.Enumerations.AdministrativeGender)src.getValue()) {
`
where src is Enumeration[null].

**Expected behavior**
The conversersion should map this to AdministrativeGender.NULL (which is the default in the switch statement).

**Screenshots**

![Screenshot 2020-11-02 153450](https://user-images.githubusercontent.com/3511273/97880113-0b8f5080-1d21-11eb-849a-367b6b291f44.png)

**Environment (please complete the following information):**
 - HAPI FHIR Version: 5.1.0
 - OS: Ubuntu

**Additional context**
N/A

**Comment by tadgh** [comment]
for reference, this _should_ work according to the version map: https://hl7.org/fhir/2018Jan/patient-version-maps.html

**Comment by grahamegrieve** [comment]
can you retry with the current code? the position you referenced - line 3869 - is long out of date

**Comment by kristof-taveirne** [comment]
Hi Graham,

In version 5.1.20 the problem is on line 2560.
`switch (src.getValue())  `

src.getValue() returns null causing the issue.

The reason is that on line 2556 
`if (src == null || src.isEmpty())`
isEmpty() here returns false, because in the sample case there is an extension defined, but no value. 
So the isEmpty() check doesn't guarantee that the switch will work because of the extension.

![image](https://user-images.githubusercontent.com/3511273/98245655-8babf500-1f71-11eb-8f32-7f38e6134d18.png)
In Element.class on line 248 it only return true if there is no extension, so this causes an NPE on the switch statement.

Kind regards
Kristof.

**Comment by grahamegrieve** [comment]
@markiantorno this is indeed a problem. Does your previous work with the converters make it possible to solve this in a whole sale fashion? This is actually a problem for all the enum conversions in all the versions

**Comment by kristof-taveirne** [comment]
Hi @markiantorno and @grahamegrieve,

Just wanted to let you know, that if we can agree on a strategy on how to fix it, I'm willing to make a contribution here.

For now for our application, I will just strip the extension from the resource when the value is null. We don't actually have a use-case for it. 

Kind regards,
Kristof.

**Comment by markiantorno** [comment]
I can look into this.

I'm currently working on another issue, and will make this next in my list.

**Comment by markiantorno** [comment]
Fixed in 5.2.1
https://github.com/hapifhir/org.hl7.fhir.core/releases/tag/5.2.1

**Comment by kristof-taveirne** [comment]
Looking great @markiantorno
Thank you!

Will test first thing tomorrow.

**Comment by kristof-taveirne** [comment]
Hi @markiantorno,

I've been testing 5.2.1 to see if the issue is resolved, but I'm stumbling against something closely related and I'm not sure how to handle this.

In the case I describe above NULL is a valid enumeration for Administrative Gender when it has just the extension with the absent-reason but no value. However, it's not a valid option in the valueset. 

Now, when this is then serialized to JSON for example, I see that this NULL value is serialized as "?" 

![image](https://user-images.githubusercontent.com/3511273/105733816-3ceb7700-5f32-11eb-958e-814230f06804.png)

Since "?" is not a valid code, the client doesn't know how to handle this and fails validation.

What's the reasoning behind this question-mark in the toCode() methods? Why not just return null?

**Comment by markiantorno** [comment]
So, this is a separate issue. While it's closely related, could you please open a new issue for this? I will look into it when time permits.
