### ISSUE TITLE
Release 5.2.0 Missing validator_cli.jar

### ISSUE THREAD

**Issue by radamson** [hapifhir/org.hl7.fhir.core#381]
Recent releases of this library have included a `validator_cli.jar`.  The [most recent release](https://github.com/hapifhir/org.hl7.fhir.core/releases), 5.2.0, is missing this artifact.  Was this intentional and were there any changes to the validator in this release?

**Comment by radamson** [comment]
Note that this breaks the validator download link on [HL7 Confluence Instructions for Using the FHIR Validator](https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator#UsingtheFHIRValidator-Downloadingthevalidator)

**Comment by markiantorno** [comment]
5.2.0 release was done manually instead of using the pipelines so a validator jar was not generated. I will run the pipeline now to generate a 5.2.1 release which will also update the validation jar. The link will work again after.

**Comment by radamson** [comment]
I figured 😉 .  Just figured I'd post an issue in case no one else noticed.

Feel free to close this issue once the updated release is out!

**Comment by markiantorno** [comment]
Fixed in 5.2.1.
https://github.com/hapifhir/org.hl7.fhir.core/releases/tag/5.2.1
