### ISSUE TITLE
5.2.9 cardinality errors are shown without cardinalities

### ISSUE THREAD

**Issue by mmreith** [hapifhir/org.hl7.fhir.core#399]
caridinality errors are shown without cardinalities:

  Error @ Observation (line 1, col42) : https://fhir.kbv.de/StructureDefinition/KBV_PR_AW_Observation_Blutdruck: mindestens erforderlich = **Observation.subject**, aber nur gefunden **Observation.subject** (min  = observation.subject, but found observation.subject)

**Comment by grahamegrieve** [comment]
fixed in 5.2.11+
