### ISSUE TITLE
Getting Error in AllergyIntolerance resource validation even if correct code is present for clinicalStatus

### ISSUE THREAD

**Issue by dagarhimanshi** [hapifhir/org.hl7.fhir.core#406]
Getting below error while validating AllergyIntolerance resource JSON:
None of the codes provided are in the value set http://hl7.org/fhir/ValueSet/allergyintolerance-clinical|4.0.1 (http://hl7.org/fhir/ValueSet/allergyintolerance-clinical), and a code from this value set is required) (codes = null#active)

This is the clinicalStatus populated:
"clinicalStatus": {
                    "coding": [
                        {
                            "code": "active"
                        }
                    ],
                    "text": "Active"
                }
As per FHIR https://www.hl7.org/fhir/allergyintolerance-definitions.html#AllergyIntolerance.clinicalStatus documentation, this is valid code populated.

**Comment by grahamegrieve** [comment]
a system is required for a CodeableConcept. That will also have been an issue noted
