### ISSUE TITLE
Snapshot generation failed

### ISSUE THREAD

**Issue by mmreith** [hapifhir/org.hl7.fhir.core#407]
By editing more than 1 Extension-Element  in a derived profile snapshot generation failed:

Unable to generate snapshot for KBV_PR_EAU_Condition_ICD from KBV_PR_Base_Diagnosis because Profil KBV_PR_EAU_Condition_ICD (https://fhir.kbv.de/StructureDefinition/KBV_PR_EAU_Condition_ICD). Fehler bei der Erstellung des Snapshots
org.hl7.fhir.exceptions.DefinitionException: Profil KBV_PR_EAU_Condition_ICD (https://fhir.kbv.de/StructureDefinition/KBV_PR_EAU_Condition_ICD). Fehler bei der Erstellung des Snapshots
        at org.hl7.fhir.r5.context.SimpleWorkerContext.generateSnapshot(SimpleWorkerContext.java:785)
        at org.hl7.fhir.r5.context.SimpleWorkerContext.generateSnapshot(SimpleWorkerContext.java:752)
        at org.hl7.fhir.r5.context.SimpleWorkerContext.allStructures(SimpleWorkerContext.java:635)
        at org.hl7.fhir.validation.ValidationEngine.prepare(ValidationEngine.java:1437)
        at org.hl7.fhir.validation.cli.services.ValidationService.getValidator(ValidationService.java:240)
        at org.hl7.fhir.validation.ValidatorCli.doValidation(ValidatorCli.java:203)
        at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:159)

After reducing the number of edited elements the failure will disappear. It does not depend on the edited element itself:
**KBV_PR_EAU_Condition_ICD** 
**not okay:**
```
    <element id="Condition.code.coding:ICD-10-GM.extension:Diagnosesicherheit.value[x]">
      <path value="Condition.code.coding.extension.value[x]" />
      <mustSupport value="true" />
    </element>
	<element id="Condition.code.coding:ICD-10-GM.extension:Diagnosesicherheit.value[x].system">
      <path value="Condition.code.coding.extension.value[x].system" />
      <min value="1" />
      <mustSupport value="true" />
    </element>
	<element id="Condition.code.coding:ICD-10-GM.extension:Diagnosesicherheit.value[x].code">
      <path value="Condition.code.coding.extension.value[x].code" />
      <min value="1" />
      <mustSupport value="true" />
    </element>
```

**okay:**
```
    <element id="Condition.code.coding:ICD-10-GM.extension:Diagnosesicherheit.value[x]">
      <path value="Condition.code.coding.extension.value[x]" />
      <mustSupport value="true" />
    </element>
	<element id="Condition.code.coding:ICD-10-GM.extension:Diagnosesicherheit.value[x].code">
      <path value="Condition.code.coding.extension.value[x].code" />
      <min value="1" />
      <mustSupport value="true" />
    </element>
```

See here 
[test.zip](https://github.com/hapifhir/org.hl7.fhir.core/files/5733957/test.zip)

**Comment by grahamegrieve** [comment]
well , it's not a valid differential; at no point does the differential assign a type to the extension, so the error is naturally: Differential contains path Condition.code.coding.extension.value[x].code which is actually Element.code, which is not found in the in base https://fhir.kbv.de/StructureDefinition/KBV_PR_EAU_Condition_ICD

**Comment by mmreith** [comment]
Hey @grahamegrieve 
okay i forgot to mention, that you need to include the hl7 base definitions (de.basisprofil.r4#0.9.12). The definition of this extension including the type is in that package.
java -jar validator_cli.jar -ig profiles -ig de.basisprofil.r4#0.9.12 -version 4.0.1 cond.xml

but anyway my problem is that it works (even in the setting you probably tested), when only one element of an extension is edited.

[test2.zip](https://github.com/hapifhir/org.hl7.fhir.core/files/6477106/test2.zip)

i made it more explicit: I created 3 directories in this test.zip

java -jar validator_cli.jar -ig profilesNOTWORKING -ig de.basisprofil.r4#0.9.12 -version 4.0.1 cond.xml
java -jar validator_cli.jar -ig profilesWORKING1 -ig de.basisprofil.r4#0.9.12 -version 4.0.1 cond.xml
java -jar validator_cli.jar -ig profilesWORKING2 -ig de.basisprofil.r4#0.9.12 -version 4.0.1 cond.xml

and afterwards please make a diff between KBV_PR_EAU_Condition_ICD_WORKING2, KBV_PR_EAU_Condition_ICD_WORKING1 and KBV_PR_EAU_Condition_ICD_NOT_WORKING

**Comment by mmreith** [comment]
Hey @grahamegrieve could please have another look on this topic? Since it is a problem in my eyes...

thanks Max
