### ISSUE TITLE
Incorrect messages.properties file is loaded when there is another such file on the classpath

### ISSUE THREAD

**Issue by kristof-taveirne** [hapifhir/org.hl7.fhir.core#416]
Hi,

In my code I'm using @PropertySource("classpath:messages.properties") to load a couple of log messages.

However, when I'm using a validator to validate resources against a profile, no translations are found for the validation messages.
When I debug I see that `this.i18nMessages` in `I18nBase` contains the keys of my own messages.properties file

When I rename messages.properties in my package to something else, all is fine.

Kristof.

**Comment by kristof-taveirne** [comment]
@markiantorno just wanted to tag you since I can't assign anyone to the ticket

**Comment by markiantorno** [comment]
@patrick-werner 

James, Grahame, and I were thinking that a possible solution for this would be to rename the file to something more unique like `fhir.messages.properties`. Do you see any issue with that as a solution?

**Comment by markiantorno** [comment]
@kristof-taveirne can you provide me with simple steps to reproduce this locally on my machine, and I will look into it.
