### ISSUE TITLE
AdministrativeGender.NULL enumeration is being serialized to "?"

### ISSUE THREAD

**Issue by kristof-taveirne** [hapifhir/org.hl7.fhir.core#426]
Hi,

When AdministrativeGender (and probably other enumerations as well) have an AdministrativeGender.NULL value, the string representation is "?".

The questionmark is therefor used in the serialized form of the resource but it is not a valid option in the valueset causing validation issue on the client. 

![image](https://user-images.githubusercontent.com/3511273/105733816-3ceb7700-5f32-11eb-958e-814230f06804.png)

Why is the toCode() method returning "?" instead of null? 

![image](https://user-images.githubusercontent.com/3511273/105734361-d581f700-5f32-11eb-9c89-ac02111273ef.png)

_Originally posted by @kristof-taveirne in https://github.com/hapifhir/org.hl7.fhir.core/issues/373#issuecomment-766938517_

**Comment by grahamegrieve** [comment]
fixed
