### ISSUE TITLE
Validator throws errors on data-absent-reason stubs

### ISSUE THREAD

**Issue by msklvsk** [hapifhir/org.hl7.fhir.core#428]
Suppose the upstream system doesn’t have `MedicationRequest.authoredOn` field. According to US Core [rules](http://hl7.org/fhir/us/core/general-guidance.html#missing-data) I have to use the data-absent-reason extension:
```json
"authoredOn": {
    "extension": [
      {
        "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
        "valueCode": "unsupported"
      }
    ]
  },
```
But it seems the validator doesn’t handle it well:
```
Error @ MedicationRequest.authoredOn (line 30, col19) : This property must be an simple value, not an object (authoredOn at MedicationRequest.authoredOn)
```
Is this expected or am I missing something?

**Comment by grahamegrieve** [comment]
yep. Needs to be _authoredOn. see http://hl7.org/fhir/json.html#primitive

**Comment by msklvsk** [comment]
Thank you! I somehow missed that. Thanks.
