### ISSUE TITLE
No obvious way to provide Questionnaire for QuestionnaireResponse validation

### ISSUE THREAD

**Issue by ilyash-b** [hapifhir/org.hl7.fhir.core#431]
Background: trying to validate QuestionnaireResponse using the CLI JAR https://github.com/hapifhir/org.hl7.fhir.core/releases/latest/download/validator_cli.jar (downloaded few days ago).

The help says

```
-questionnaire [file|url}: the location of a questionnaire. If provided, then the validator will validate
     any QuestionnaireResponse that claims to match the Questionnaire against it
     no default value. This parameter can appear any number of times
```

This is incorrect. The expected `-questionnaire` argument is one of the values from `org.hl7.fhir.validation.cli.utils.QuestionnaireMode` enum:

```
$ java -jar ../bin/validator_cli.jar -questionnaire xyz
FHIR Validation tool Version 5.2.20 (Git# af05868a82bf). Built 2021-01-25T15:02:44.742Z (6 days old)
  Java:   1.8.0_242 from /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre on x86_64 (64bit). 3641MB available
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant org.hl7.fhir.validation.cli.utils.QuestionnaireMode.xyz
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.hl7.fhir.validation.cli.utils.QuestionnaireMode.valueOf(QuestionnaireMode.java:3)
	at org.hl7.fhir.validation.cli.utils.Params.loadCliContext(Params.java:135)
	at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:147)
```

(also, there is no error about this when running with ` -questionnaire REQUIRED` for example)

**Comment by grahamegrieve** [comment]
As of next, release, the documentation will be updated to say 

-questionnaire mode: what to do with when validating QuestionnaireResponse resources
     none (default): just ignore the questionnaire reference
     required: check that the QuestionnaireResponse has a questionnaire and validate against it 
     check: if the QuestionnaireResponse has a questionnaire, validate against it
     The questionnaire must be loaded using the -ig parameter
