### ISSUE TITLE
Error on code when running -tx n/a

### ISSUE THREAD

**Issue by RobinGroepT** [hapifhir/org.hl7.fhir.core#433]
When I run the validator jar with -tx n/a it does not connect to the terminology server and I have for example SNOMED-CT codes in my instance it gives me a clear warning -> that I can understand and I think is OK.
However: I noticed when I refer to a MIME type in an instance, for example when validating a Claim and I have
[...]
"supportingInfo": [
[...]
"valueAttachment": {
"contentType": "application/pdf",
"data": "QW5uZXhlIGlubGluZSwgYmFzZTY0ZWQ=",
"title": "nom/description de l'annexe"
}
[...]
-> the validator throws an error:
Error @ Bundle.entry[9].resource.ofType(Claim).supportingInfo[0].value.ofType(Attachment).contentType (line 343, col48) : The value provided ('application/pdf') is not in the value set http://hl7.org/fhir/ValueSet/mimetypes|4.0.1 (http://hl7.org/fhir/ValueSet/mimetypes), and a code is required from this value set) (error message = Attempt to use Terminology server when no Terminology server is available)
-> I guess in cases like this, this should be an error
(originally posted on https://chat.fhir.org/#narrow/stream/179166-implementers/topic/error.20when.20running.20validator.20without.20tx )

**Comment by grahamegrieve** [comment]
fixed
