### ISSUE TITLE
Publishing a new version

### ISSUE THREAD

**Issue by ItayGoren** [hapifhir/org.hl7.fhir.core#435]
Hey,
When is a new version with the changes in the CHANGE LOG would be published?
The new version would help me a lot.
Thank you for the help and your time

**Comment by jamesagnew** [comment]
The next HAPI FHIR release is next Thursday. Note, please don't use the GitHub issues area to ask questions, this wiki page has info on where to ask questions about HAPI FHIR: https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help
