### ISSUE TITLE
Support M and F for patient gender in dstu2

### ISSUE THREAD

**Issue by ItayGoren** [hapifhir/org.hl7.fhir.core#437]
Hey,
I see in the spec that the values "F" and "M" are permitted for the gender enum in dstu2: https://www.hl7.org/fhir/DSTU2/valueset-administrative-gender.html
Yet, the enum in the code doesn't support them:
![image](https://user-images.githubusercontent.com/67951567/107960205-0216b500-6fad-11eb-9dc7-bbe4decc5540.png)
Did I understand it correctly?

**Comment by markiantorno** [comment]
@ItayGoren 

I don't see where the documentation says that `M` and `F` are valid values for gender? I only see that the core display and definition values are `male`, `female`, `other`, and `unknown`. The `M` and `F` seem to refer to maps from v2 and v3. 

Let me know if I am not interpreting this correctly.
