### ISSUE TITLE
Validator: Throws Error on non-resolvable fixed uris

### ISSUE THREAD

**Issue by patrick-werner** [hapifhir/org.hl7.fhir.core#440]
The Java Validator throws an error when canonical urls aren't resolvable, e.g.: 
`Error @ StructureDefinition.differential.element[2].fixed.ofType(uri) (line 42, col64) : URL value "http://hl7.org/fhir/sid/passport-DEU" does not resolve`

This should be converted to a warning, as it isn't an error of the profile which is checked.

**Comment by grahamegrieve** [comment]
well, there's a reason why it does this; the validator is supposed to know about all URIs in the hl7.org/fhir space. How to reproduce this?

**Comment by patrick-werner** [comment]
resolved through https://github.com/hapifhir/org.hl7.fhir.core/pull/512
