### ISSUE TITLE
Incorrect missing code errors when validating against Questionnaire

### ISSUE THREAD

**Issue by me-d4l** [hapifhir/org.hl7.fhir.core#441]
### Description

Using the validator JAR, I have been seeing incorrect errors when validating QuestionnaireResponses against Questionnaires, with the validator wrongly claiming that an answer code is not in the appropriate value set. The error message is this:

```
  Error @ QuestionnaireResponse.item[0].answer[0] (line 10, col68) : The value provided (http://loinc.org::LA32-8) is not in the options value set in the questionnaire
```

Below, I pasted in a minimal set of resources that reproduces the problem. To get the error, put the Questionnaire & the ValueSet in the same folder, load them in the validator with the `-ig` parameter pointing to the folder, and validate the QuestionnaireResponse.

Curiously, the error only appears if the two questions are answered with *different codes* - if I modify the example to use the *same* code in both answers, it validates OK. 

Further background in [this FHIR Zulip thread](https://chat.fhir.org/#narrow/stream/179239-tooling/topic/False.20JAR.20validator.20errors.20for.20certain.20questionnaire.20answers).

### Questionnaire example

```json
{
    "resourceType": "Questionnaire",
    "url": "http://example.com/q",
    "status": "draft",
    "item": [{
        "type": "choice",
        "linkId": "A",
        "answerValueSet": "http://example.com/yesno"
    }, {
        "type": "choice",
        "linkId": "B",
        "answerValueSet": "http://example.com/yesno"
    }]
}
```

### Answer ValueSet

```json
{
    "resourceType": "ValueSet",
    "url": "http://example.com/yesno",
    "status": "active",
    "compose": {
        "include": [
            {
                "system": "http://loinc.org",
                "concept": [
                    {"code": "LA33-6"},
                    {"code": "LA32-8"}
                ]
            }
        ]
    }
}
```

### QuestionnaireResponse provoking the error

Note that we modify this resource so that the _same_ code is used in both question A and B, the error disappears.

```json
{
    "resourceType": "QuestionnaireResponse",
    "questionnaire": "http://example.com/q",
    "status": "completed",
    "item": [{
        "linkId": "A",
        "answer": [{ "valueCoding": { "system": "http://loinc.org", "code": "LA33-6" } }]
    }, {
        "linkId": "B",
        "answer": [{ "valueCoding": { "system": "http://loinc.org", "code": "LA32-8" } }]
    }]
}
```

**Comment by grahamegrieve** [comment]
This was an error with the terminology caching algorithm. fixed in PR 44
