### ISSUE TITLE
HTTP 422 Unprocessable Entity: The syntax of the reference '#1' looks incorrect, and it should be checked

### ISSUE THREAD

**Issue by tyfoni** [hapifhir/org.hl7.fhir.core#445]
The checkReference issues a warning for internal references because of this line:
https://github.com/hapifhir/org.hl7.fhir.core/blob/82edacbde431f5639c9535ef60d8414605039c17/org.hl7.fhir.validation/src/main/java/org/hl7/fhir/validation/instance/InstanceValidator.java#L2544

But there is nothing wrong with an internal reference if the resource is contained.

**Comment by grahamegrieve** [comment]
fixed
