### ISSUE TITLE
resources in Bundle gets validated against base profile even when the resource have a custom profile

### ISSUE THREAD

**Issue by tyfoni** [hapifhir/org.hl7.fhir.core#446]
https://github.com/hapifhir/org.hl7.fhir.core/blob/82edacbde431f5639c9535ef60d8414605039c17/org.hl7.fhir.validation/src/main/java/org/hl7/fhir/validation/instance/InstanceValidator.java#L4165

We have upgraded to hapi-fhir 5.3.0 and see validation errors with transaction bundles, eg: 
HTTP 422 Unprocessable Entity: None of the codes provided are in the value set http://hl7.org/fhir/ValueSet/devicemetric-type (http://hl7.org/fhir/ValueSet/devicemetric-type), and a code is recommended to come from this value set) (codes = urn:oid:1.2.208.176.2.1#NPU03011)

The Bundle:
```
<Parameters
	xmlns="http://hl7.org/fhir">
	<parameter>
		<name value="bundle"/>
		<resource>
			<Bundle
				xmlns="http://hl7.org/fhir">
				<type value="transaction"/>
				<entry>
					<fullUrl value="829a3eaf-dac7-4b95-b0f8-a629404d042d"/>
					<resource>
						<Device
							xmlns="http://hl7.org/fhir">
							<meta>
								<profile value="http://ehealth.sundhed.dk/fhir/StructureDefinition/ehealth-device"/>
							</meta>
							<extension url="http://ehealth.sundhed.dk/fhir/StructureDefinition/ehealth-device-privatelyOwned">
								<valueBoolean value="true"/>
							</extension>
							<status value="active"/>
						</Device>
					</resource>
					<request>
						<method value="POST"/>
						<url value="Device"/>
					</request>
				</entry>
			</Bundle>
		</resource>
	</parameter>
	<parameter>
		<name value="withoutRequestDetails"/>
		<valueBoolean value="false"/>
	</parameter>
</Parameters>
```
The DSTU3 DeviceMetric defines type: 
```
    <element id="DeviceMetric.type">
      <path value="DeviceMetric.type"/> 
      <short value="Identity of metric, for example Heart Rate or PEEP Setting"/> 
      <definition value="Describes the type of the metric. For example: Heart Rate, PEEP Setting, etc."/> 
      <comment value="DeviceMetric.type can be referred to either IEEE 11073-10101 or LOINC."/> 
      <min value="1"/> 
      <max value="1"/> 
      <type> 
        <code value="CodeableConcept"/> 
      </type> 
      <isSummary value="true"/> 
      <binding> 
        <extension url="http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName">
          <valueString value="MetricType"/> 
        </extension> 
        <strength value="preferred"/> 
        <description value="Describes the metric type."/> 
        <valueSetReference> 
          <reference value="http://hl7.org/fhir/ValueSet/devicemetric-type"/> 
        </valueSetReference> 
      </binding> 
      <mapping> 
        <identity value="w5"/> 
        <map value="class"/> 
      </mapping> 
    </element> 

```
But we have profiled:
```

    <element id="DeviceMetric.type">
      <path value="DeviceMetric.type" />
      <binding>
        <extension url="http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName">
          <valueString value="MetricType" />
        </extension>
        <strength value="required" />
        <valueSetReference>
          <reference value="http://ehealth.sundhed.dk/vs/device-measurement-unit" />
        </valueSetReference>
      </binding>
    </element>
```

The resource should be validated against the custom profile if present.

**Comment by grahamegrieve** [comment]
You'll need to provide more information - why does a warning create a 422? Does this get a warning if you use the current standalone validator?

**Comment by tyfoni** [comment]
In our setup the warning causes a 422. But the problem is that the warning is issued. With our profiling we require that DeviceMetric.type must take a value from our valueset "http://ehealth.sundhed.dk/vs/device-measurement-unit" which contains the code urn:oid:1.2.208.176.2.1#NPU03011.
But the validation still validates against the base profile which has the valueset "http://hl7.org/fhir/ValueSet/devicemetric-type".

Where do I find the standalone validator ?

**Comment by tyfoni-systematic** [comment]
We have upgraded to hapi-fhir 5.4.0 and still require a local modification in InstanceValidator:

`        // FUT1-4847 workaround problem with bundle resource being validated against base profile even if profile is present
        String profileUri = "http://hl7.org/fhir/StructureDefinition/" + resourceName;
        Element meta = element.getNamedChild(META);
        if (meta != null) {
          List<Element> profiles = new ArrayList<Element>();
          meta.getNamedChildren("profile", profiles);
          if (!profiles.isEmpty()) {
            profileUri = profiles.get(0).primitiveValue();
          }
        }
        StructureDefinition profile = this.context.fetchResource(StructureDefinition.class, profileUri);
`
We are in the process of moving from STU3 to R4 and later we will upgrade to hapi-fhir 5.5.0. Then we will revisit this issue.
