### ISSUE TITLE
FHIRLexer.isConstant() throws NullPointerException when current == null

### ISSUE THREAD

**Issue by keithboone** [hapifhir/org.hl7.fhir.core#447]
public boolean isConstant() {
    return current != null && (current.charAt(0) == '\'' || current.charAt(0) == '"') || current.charAt(0) == '@' || current.charAt(0) == '%' || 
        current.charAt(0) == '-' || current.charAt(0) == '+' || (current.charAt(0) >= '0' && current.charAt(0) <= '9') || 
        current.equals("true") || current.equals("false") || current.equals("{}");
  }

Should be: 

  public boolean isConstant() {
    return current != null && (current.charAt(0) == '\'' || current.charAt(0) == '"') || current.charAt(0) == '@' || current.charAt(0) == '%' || 
        current.charAt(0) == '-' || current.charAt(0) == '+' || (current.charAt(0) >= '0' && current.charAt(0) <= '9') || 
        "true".equals(current) || "false".equals(current) || "{}".equals(current);
  }

**Comment by markiantorno** [comment]
This appears to have been already fixed in a previous commit. I added a test to verify in [PR-576](https://github.com/hapifhir/org.hl7.fhir.core/pull/576).
