### ISSUE TITLE
NullPointerException when code validation reports an error

### ISSUE THREAD

**Issue by lawley** [hapifhir/org.hl7.fhir.core#46]
The line below will trigger an NPE because `s.getErrorClass()` always returns `null`.
This is because the call to `context.validateCode(...)` creates the `ValidationResult` object with this constructor `public ValidationResult(IssueSeverity severity, String message, ConceptDefinitionComponent definition)` and this does not initialise the `errorClass` field.

https://github.com/hapifhir/org.hl7.fhir.core/blob/9a344b251c77d04bc24c9b33401346fcdd5b0a30/org.hl7.fhir.validation/src/main/java/org/hl7/fhir/r4/validation/InstanceValidator.java#L819

The upshot of this is that the validator produces the message:
`Error null validating Coding`

**Comment by grahamegrieve** [comment]
this is fixed in the R5 validator. The R4 validator is no longer maintained and I'll be deleting it as soon as I get around to hunting down it's dependencies
