### ISSUE TITLE
XMLParser.compose should allow passing a schema location

### ISSUE THREAD

**Issue by lmckenzi** [hapifhir/org.hl7.fhir.core#468]
When the core publisher is turning spreadsheets into resources, we want the resulting XML files to have schema references to the local schema path to allow easier editing/validating.  While schema declarations are not permitted when *exchanging* FHIR resources for security reasons, we've long used them as part of the authoring process.  Obviously the schema declaration can't be found in the resource.  The logical way to handle this is to define a new variation on the `compose()` function that can take an additional argument - the schema location to declare.  (In my use-case, this would always be a relative path, but the method should be fine with any path and can probably handle it as just a string.)

**Comment by grahamegrieve** [comment]
done
