### ISSUE TITLE
Validation incorrectly applies Bundle invariants when validating instance of R4 Parameters

### ISSUE THREAD

**Issue by azatadha** [hapifhir/org.hl7.fhir.core#47]
The following execution of the java validator incorrectly applied Bundle invarients (when the Bundle.type was "collection". See attached zip.

FHIR Validation tool Version 3.8.0-SNAPSHOT - Built 2019-02-11T12:49:16.829-05:00 - Git 7a8671008476
Arguments: -ig test\text-binary.xml -ig test\param-profile.xml test\example-params-1.xml
  .. connect to tx server @ http://tx.fhir.org
  .. definitions from hl7.fhir.core#4.0.0
    (v4.0.0)
+  .. load IG from test\text-binary.xml
+  .. load IG from test\param-profile.xml
  .. validate [test\example-params-1.xml]
*FAILURE* validating test\example-params-1.xml:  error:2 warn:0 info:0
  Error @ Parameters.parameter.resource (line 7, col19) : entry.request mandatory for batch/transaction/history, otherwise prohibited [entry.all(request.exists() = ((.type = 'batch') or (.type = 'transaction') or (.type = 'history')))]
  Error @ Parameters.parameter.resource (line 7, col19) : entry.response mandatory for batch-response/transaction-response/history, otherwise prohibited [entry.all(response.exists() = ((.type = 'batch-response') or (.type = 'transaction-response') or (.type = 'history')))]

[test.zip](https://github.com/hapifhir/org.hl7.fhir.core/files/3295444/test.zip)

**Comment by grahamegrieve** [comment]
Fix with 3.8.6
