### ISSUE TITLE
Converters dropping practitioner.practitionerRole data when converting DSTU2 to R4

### ISSUE THREAD

**Issue by miguelC** [hapifhir/org.hl7.fhir.core#470]
In DSTU2 the practitioner resource has a practitionerRole property that is not being translated into a R4 PractitionerRole resource. 
The difficulty in this transformation is that a DSTU2 practitioner resource when sent into the convertResource method must yield 2 R4 resources, a PractitionerRole and a Practitioner, but the method signature does not allow for this type of behavior.

Is there a recommendation on how one can preserve the practitioner.practitionerRole when converting DSTU2 to R4?
Maybe add the role as a contained resource in the Practitioner resource?

Thanks,

Miguel.

**Comment by markiantorno** [comment]
Alright, so we've done some major changes to the conversion libraries that will be in the next release.

Details are here: https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.convertors/CONVERTORS.md

These changes allow users to control conversion of ValueSet, CodeSystem, and Extensions, if they need to.

Conversions are an inherently lossy operation. In your case, you appear to want to do a custom Resource conversion that is not supported by the current libraries. You will need to write your own specific convertor for this case.

I would suggest you:
1. Look at [the current practitioner conversion class](https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.convertors/src/main/java/org/hl7/fhir/convertors/conv10_40/resources10_40/Practitioner10_40.java) to see how we approach the conversion.
2. Write your own custom convertor based on that.
3. Include a special case in your program logic that calls your custom convertor class.

Please feel free to reach out on Zulip with any questions about this.
