### ISSUE TITLE
Server Exception when converting an R4 Expression to STU3

### ISSUE THREAD

**Issue by hdconradi** [hapifhir/org.hl7.fhir.core#473]
Hi,

I have encountered an server exception when trying to convert resources which contain a `R4` (or `R5`) `Expression` into a `STU3` resource.
E.g.:
```
{
  "resourceType": "Questionnaire",
  "status": "draft",
  "extension": [
    {
      "url": "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-enableWhenExpression",
      "valueExpression": {
        "language": "text/cql",
        "expression": "%resource.item I where (I.linkId = 'a1' and I.answer[0].value <> 0) or (I.linkId = 'a2' and I.answer[0].value in { 1, 2 })"
      }
    }
  ]
}

```
This will end up in:
```
org.hl7.fhir.exceptions.FHIRException: Unknown type Expression
	at org.hl7.fhir.convertors.VersionConvertor_30_40.convertType(VersionConvertor_30_40.java:3133)
	at org.hl7.fhir.convertors.VersionConvertor_30_40.convertExtension(VersionConvertor_30_40.java:337)
```
since no conversion for an Expression is defined in `VersionConvertor_30_40` (or `VersionConvertor_30_50`).
I have prepared a simple test for this - runs (i.e. fails) on the current version (and at least 5.3.0 to 5.3.8):
```
package org.hl7.fhir.convertors;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class VersionConvertorExpressionTest {

  @Test
  public void testConvertExtension40_30() {
    org.hl7.fhir.r4.model.Expression expression = new org.hl7.fhir.r4.model.Expression().setLanguage("text/cql").setExpression("(a1  <> 0) and (a2 = 1 or a2 = 3)");
    org.hl7.fhir.r4.model.Extension extension = new org.hl7.fhir.r4.model.Extension("http://example.com", expression);

    VersionConvertor_30_40.convertExtension(extension);
  }

  @Test
  public void testConvertExtension50_30() {
    org.hl7.fhir.r5.model.Expression expression = new org.hl7.fhir.r5.model.Expression().setLanguage("text/cql").setExpression("(a1  <> 0) and (a2 = 1 or a2 = 3)");
    org.hl7.fhir.r5.model.Extension extension = new org.hl7.fhir.r5.model.Extension("http://example.com", expression);

    VersionConvertor_30_50.convertExtension(extension);
  }
}

```
There are obviously several ways to handle this case, starting with just dropping the extension from the resource (which would happen btw if a STU3 parser would read the R4 json), or convert the `Expression` into a `StringType` (maybe even with a warning attached), or ...
Since I do not know how to handle it, I have just called the converter to see the exception, but did not examine the result, and did not try to create a patch.

Is there any official policy regarding this kind of conversion?

**Comment by markiantorno** [comment]
So, with `value[x]` of type `Expression` existing in R4+ and not existing in DSTU3 or lower, based on how we handle conversions, I would treat this as a lossy operation. 

We do this with a number of other conversions between FHIR versions. If the field exists in one version, and no such equivalent field exists in the target version, the data is lost. I do not believe that converting the field into a String, or some other representation in the target resource would be consistent with how this is handled throughout the other version converters.

Right now, as you've seen, the converter throws an exception and dies...this is not ideal. I'll put a fix in to complete the conversion without throwing the error. 

Thank you for the detailed issue write up, as well as providing a test. I will include it in the fix.

**Comment by markiantorno** [comment]
Alright, so we've done some major changes to the conversion libraries that will be in the next release.

Details are here: https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.convertors/CONVERTORS.md

Specifically for your issue, you can create a custom conversion advisor that handles extensions for resources in the way you need for your specific usecase.

I'll make this as closed for now. Once we release 5.4.10. please read the instructions and try your custom conversion.
