### ISSUE TITLE
R2R3ConversionManager Error 

### ISSUE THREAD

**Issue by RokshanJ** [hapifhir/org.hl7.fhir.core#478]
Hi @markiantorno 
I am trying this - 

		R2R3ConversionManager conversionMgr = new R2R3ConversionManager();
		 org.hl7.fhir.dstu2.model.Resource rs = new org.hl7.fhir.dstu2.model.Condition();
		 rs.setId("1");
		String  map = loadFile("classpath:R2toR3_maps.zip");
	    InputStream r2D = new FileInputStream("/Users/resources/r2-defs.zip");
		InputStream r3D = new FileInputStream("/Users/resources/r3-defs.zip");

		conversionMgr.setR3Definitions(r3D);
		conversionMgr.setMappingLibrary(map);
		Resource con3 = conversionMgr.convert(rs);

I am getting this error :

org.hl7.fhir.exceptions.FHIRFormatError: Error parsing profiles-types.xml:Stream closed

**Comment by markiantorno** [comment]
It appears your trying to do conversions with your own definitions/mappings. Correct?

Could you please provide:

1. Description of what you are trying to do.
2. Copies of the files used in the example you gave.
3. A description of the expected output.

Once provided I will debug.

**Comment by markiantorno** [comment]
I am closing this, as you have not provided any additional information. Please reopen if you wish to continue this discussion.
