### ISSUE TITLE
StructureMap parser sets rule name with double quotes

### ISSUE THREAD

**Issue by oliveregger** [hapifhir/org.hl7.fhir.core#48]
Parsing Rule names keeps the double quotes for the rule names which is not valid for a rule name: StructureMap/ActivityDefinition3to4: 

```
group ActivityDefinitionDynamicValue(source src, target tgt) extends BackboneElement {
  src.path -> tgt.path;
  src as vs where vs.type.exists().not() -> tgt.expression = create('Expression') as vt then {
    vs.description -> vt.description;
    vs.language -> vt.language;
    vs.expression -> vt.expression;
  } "expression";
}
````
lets to a validation error after parsing:
StructureMap.group[3].rule[2].name error id value '"expression"' is not valid. 

will provide a pull request / testcase

**Comment by grahamegrieve** [comment]
Merged
