### ISSUE TITLE
Quantity subclasses copy() functions not all transferring values

### ISSUE THREAD

**Issue by XcrigX** [hapifhir/org.hl7.fhir.core#483]
Several of the org.hl7.fhir.r4.model.Quantity subclasses (Age, Duration, Count, Distance) do not copy their base Quantity values when copy() is called. SimpleQuantity and MoneyQuantity appear to have extra code to copy their values. 
I have not checked the non-R4 packages, but will guess the problem is the same for those versions as well.

**Comment by grahamegrieve** [comment]
This is wrong. the R4 classes are all OK, except for  SimpleQuantity and MoneyQuantity which were double copying. Fixed that, and also some R3 ones weren't right. fixed them as well

**Comment by XcrigX** [comment]
My apologies - I was working from a prior version where this didn't work (4.2). I did look at the latest code where it appeared unchanged, but didn't run it - so my mistake. It must have been corrected in the super-class. Thanks.
