### ISSUE TITLE
IntegerType.copy() throws a NullPointerException when called for an object with a null value. 

### ISSUE THREAD

**Issue by XcrigX** [hapifhir/org.hl7.fhir.core#484]
```
	public IntegerType(int theInteger) {
		setValue(theInteger);
	}

	@Override
	public IntegerType copy() {
		IntegerType ret = new IntegerType(getValue());
    copyValues(ret);
    return ret;
	}
```

getValue() can return a null Integer - when this is passed to the constructor it tries to auto-unbox a null which throws a NPE. I think it would be mitigated if the constructor used a Integer instead of the primitive int.

**Comment by markiantorno** [comment]
Looking at the other primitive classes like `BooleanType` and `StringType`, other primitive types accept the wrapper classes as constructor arguments. I do not see a reason that IntegerType should be different.

I will make the change.
