### ISSUE TITLE
Off-by-one error in location fhirpath from validator + wrong line #'s

### ISSUE THREAD

**Issue by vadi2** [hapifhir/org.hl7.fhir.core#50]
In the given ImplementationGuide resource, when validated as STU3:

java -jar org.hl7.fhir.validator.jar -version 3.0 'swedishnationalmedicationlist.json' 

[swedishnationalmedicationlist.zip](https://github.com/hapifhir/org.hl7.fhir.core/files/3307559/swedishnationalmedicationlist.zip)

The following warnings are returned:

```
  Warning @ ImplementationGuide.page.page[1].format (line 199, col16) : ValueSet http://hl7.org/fhir/ValueSet/mimetypes not found
  Warning @ ImplementationGuide.page.page[2].format (line 199, col16) : ValueSet http://hl7.org/fhir/ValueSet/mimetypes not found
  Warning @ ImplementationGuide.page.page[3].format (line 199, col16) : ValueSet http://hl7.org/fhir/ValueSet/mimetypes not found
  Warning @ ImplementationGuide.page.page[4].format (line 199, col16) : ValueSet http://hl7.org/fhir/ValueSet/mimetypes not f
```

The page numbers are off by one - it should be `page`, `page[1]`, `page[2]` and `page[3]`

The line numbers are also wrong - they're all at line `199`.

This is using 3.8.7.

**Comment by grahamegrieve** [comment]
fixed

**Comment by vadi2** [comment]
@grahamegrieve the off-by-one error is still there :(
