### ISSUE TITLE
5.4.0 missing validator_cli.jar

### ISSUE THREAD

**Issue by radamson** [hapifhir/org.hl7.fhir.core#505]
@jamesagnew most recent release (5.4.0) is missing the `validator_cli.jar` asset.

This breaks anyone trying to download the validator from the docs: https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator#UsingtheFHIRValidator-TerminologyServer

**Comment by markiantorno** [comment]
I'm am aware and am actively working to get the new version out.

**Comment by radamson** [comment]
No problem - we've all been there. I see you put out a new release which fixes the issue.
