### ISSUE TITLE
IG Publisher mangles html for R4 StructureDefinition detailed definition page

### ISSUE THREAD

**Issue by azatadha** [hapifhir/org.hl7.fhir.core#51]
The detailed definition page for a R4 profile of a Resource has lost the closing </table> tag.
This has the bizarre effect of inserting the page footer before the table of definitions!

The generated fragment is fine and when i run Jekyll directly against the temp directory all is fine!

Curiously this only occurs for StructureDefinitions that constrain Resources.
A StructureDefinitions that constrains a DataType works just fine.
[agency-fhir-ig-template.zip](https://github.com/hapifhir/org.hl7.fhir.core/files/3308284/agency-fhir-ig-template.zip)

**Comment by azatadha** [comment]
The closing tag that is missing is the table tag (from the fragment included by Jekyll)

**Comment by grahamegrieve** [comment]
fixed.
