### ISSUE TITLE
Validator shouldn't ignore example.org, acme.org, etc. extensions

### ISSUE THREAD

**Issue by lmckenzi** [hapifhir/org.hl7.fhir.core#521]
(from https://jira.hl7.org/browse/FHIR-17560)

The validator currently treats "example.org" extensions as valid. It shouldn't. (Only the IG and core publication tools should do that.)

Tried on 2021-05-27 with Telus and no warning was raised when an example.org extension was embedded

**Comment by grahamegrieve** [comment]
fixed next release
