### ISSUE TITLE
IEvaluationContext "resolveConstant" doesn't support collections

### ISSUE THREAD

**Issue by JPercival** [hapifhir/org.hl7.fhir.core#535]
The FHIRPath spec allows environment variables to be collections. The IEvaluationContext interface only returns a single "Base" object. This prevents the use of the FhirPathEngine when implementing certain IGs that require collection environment variables. I've linked the R5 definition here, but it applies to all versions of FHIR:

https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.r5/src/main/java/org/hl7/fhir/r5/utils/FHIRPathEngine.java#L254

Relevant spec:
http://hl7.org/fhir/fhirpath.html#vars
> Note that these tokens are not restricted to simple types

http://hl7.org/fhirpath/#collections
> Collections are fundamental to FHIRPath, in that the result of every expression is a collection

**Comment by grahamegrieve** [comment]
@jamesagnew this is a design mistake on my part, i think. The most logical way to fix it is simply to make a breaking change to the interface. Thoughts?

**Comment by grahamegrieve** [comment]
ok change made. Will make PR soon
