### ISSUE TITLE
Certain Medication Codes (icd9cm) are not supported

### ISSUE THREAD

**Issue by alexchirayath** [hapifhir/org.hl7.fhir.core#536]
While running the validator, I notice that some codes are not being recognized and thrown as error by the validator.

For example
`  Error @ Procedure.code.coding[0] (line 1, col157) : The code "9915" is not valid in the system http://hl7.org/fhir/sid/icd-9-cm; The code provided (http://hl7.org/fhir/sid/icd-9-cm#9915) is not valid in the value set 'All codes known to the system' (from http://tx.fhir.org/r3) for 'http://hl7.org/fhir/sid/icd-9-cm#9915'`
However, it does seem that this is a [valid code](https://www.hipaaspace.com/medical_billing/coding/icd-9/procedure/9915) 

This is just one of the examples and there are other icd9cm codes that are raising errors. Is there a reason why these are not being recognized?

Here is the file input I was trying to validate

```
{
   "resourceType":"Procedure",
   "identifier":[
      {
         "system":"http://www.test-redacted.de/procs",
         "value":"984123_1"
      }
   ],
   "status":"completed",
   "code":{
      "coding":[
         {
            "system":"http://hl7.org/fhir/sid/icd-9-cm",
            "code":"9915",
            "display":"Parenteral infusion of concentrated nutritional substances"
         }
      ]
   },
   "subject":{
      "reference":"2dd1b3ce-d0d0-4b4a-a85b-6e8f5b234e3c"
   },
   "id":"af9b45b4-b636-444e-9dea-3c0dfa1c48c9"
}
```

**Comment by grahamegrieve** [comment]
Closing this issue, since it's actually sourced from elsewhere. Raise the issue on https://chat.fhir.org/#narrow/stream/179202-terminology
