### ISSUE TITLE
validator enforces the coding.system to be absolute reference

### ISSUE THREAD

**Issue by chaoshen-1984** [hapifhir/org.hl7.fhir.core#545]
For below extension, we got error `"diagnostics": "Coding.system must be an absolute reference, not a local reference"`

```
        {
          "url": "detailed",
          "valueCoding": {
            "system": "2.16.840.1.113883.6.238",
            "code": "2108-9",
            "display": "European"
          }
```

From FHIR https://www.hl7.org/fhir/datatypes.html#Coding, we do not see anywhere it mention the Coding.system must be an absolute reference. 
We believe the rule should not be enforced.

**Comment by grahamegrieve** [comment]
Well, if you really want to argue the point, you can do so at https://chat.fhir.org/#narrow/stream/179177-conformance. But in this case, your system should be urn:oid:2.16.840.1.113883.6.238, for which the validator would not create an error

**Comment by chaoshen-1984** [comment]
OK. One reason we ask is the resource seems passing the validator provided in FHIR https://www.hl7.org/fhir/validation.html. But failed in HAPI validator. And as we dig through the FHIR spec, we cannot find where this rule is being declared in FHIR. 

I think HAPI must have a reason to enforce this rule. If you can point to where this spec is defined in FHIR or why HAPI wants to enforce the rule, it will help a lot!

**Comment by chaoshen-1984** [comment]
Got the detail from here: 
https://chat.fhir.org/#narrow/stream/179177-conformance/topic/validation.3A.20coding.2Esystem.20to.20be.20absolute.20reference

Thank you very much!

**Comment by markiantorno** [comment]
If this is still an issue with the HAPI validator, please open the issue in that project.
