### ISSUE TITLE
Handling minValue/maxValue in generate snapshot process

### ISSUE THREAD

**Issue by LouisRolland78** [hapifhir/org.hl7.fhir.core#555]
**Describe the bug**
The fields minValue/maxValue are ignored when generating a snapshot from a differential (class ProfileUtilities, method updateFromDefinition).

For example for the field maxLength, we have this piece of code:
![image](https://user-images.githubusercontent.com/28785069/124455194-92516d00-dd89-11eb-9d65-0fd799ac3d29.png)

I think that we should have the same type of code for minValue and maxValue.

@grahamegrieve : Could you help me with this bug please? What is the Issues/Pull requests process?

Thank you.

**Comment by LouisRolland78** [comment]
I tried to push the fix but I have 403 access denied. The piece of code to add is: (in all ProfileUtilities, just after the piece of code on derived.hasMaxLengthElement() (see image))


      if (derived.hasMaxValue()) {
        if (!Base.compareDeep(derived.getMaxValue(), base.getMaxValue(), false))
          base.setMaxValue(derived.getMaxValue().copy());
        else if (trimDifferential)
          derived.setMaxValue(null);
        else
          derived.getMaxValue().setUserData(DERIVATION_EQUALS, true);
      }
  
      if (derived.hasMinValue()) {
        if (!Base.compareDeep(derived.getMinValue(), base.getMinValue(), false))
          base.setMinValue(derived.getMinValue().copy());
        else if (trimDifferential)
          derived.setMinValue(null);
        else
          derived.getMinValue().setUserData(DERIVATION_EQUALS, true);
      }

**Comment by markiantorno** [comment]
Please fork the repo into your own copy. Make the changes on the fork, and then open a PR from your fork to the main repo. 

I will review once you do this.

**Comment by LouisRolland78** [comment]
Ok Thank you! I'm doing that.
