### ISSUE TITLE
Validator: Not giving correct index number in error message for Questionnaire Response error

### ISSUE THREAD

**Issue by GitHubUNCStudent** [hapifhir/org.hl7.fhir.core#565]
For the QuestionnaireResponse error message "If text exists, it must match the questionnaire definition for linkId ...", 
the error log lists the nesting levels correctly but the index numbers are not correct.  The index numbers are displaying as all zeros such as  QuestionnaireResponse.item[0].item[0].item[0].item[0].

**Comment by markiantorno** [comment]
Please provide the steps, with examples you used, to reproduce this issue.
