### ISSUE TITLE
Lack of fhirpkg.lock.json crashes validator

### ISSUE THREAD

**Issue by vadi2** [hapifhir/org.hl7.fhir.core#57]
The Java validator is now crashing if the `-ig <directory>` file doesn't have a `fhirpkg.lock.json` file.

**Comment by grahamegrieve** [comment]
I've never heard of this file, don't see any references in the code, can't reproduce the issue, and don't understand what it could be

**Comment by vadi2** [comment]
Doesn't seem to happen anymore - should've posted the stack trace.
