### ISSUE TITLE
TerminologyCache.hashNWS is terribly slow

### ISSUE THREAD

**Issue by jnmeijer** [hapifhir/org.hl7.fhir.core#570]
https://github.com/hapifhir/org.hl7.fhir.core/blob/99fcac64ac35ca7dc3a4aa9922684ac7fdb0ee7b/org.hl7.fhir.r5/src/main/java/org/hl7/fhir/r5/context/TerminologyCache.java#L406

When running some examples a few times, TerminologyCache.hashNWS is very slow due to String.replace(...) using Pattern.match(...).  Better to use StringUtils.remove(...).

By using the following instead, I reduced time spent by 56% when running in Eclipse:
  private String hashNWS(String s) {
    s = StringUtils.remove(s, '\r');
    s = StringUtils.remove(s, '\n');
    s = StringUtils.remove(s, ' ');
    return String.valueOf(s.hashCode());
  }

**Comment by grahamegrieve** [comment]
fixed
