### ISSUE TITLE
Create Interface to pass to TerminologyClient for HTTP calls

### ISSUE THREAD

**Issue by markiantorno** [hapifhir/org.hl7.fhir.core#588]
Modify the TerminologyClient to take an interface as a parameter.

That interface would allow an implementation to add any header far making HTTP calls.

**Comment by david-simons** [comment]
Thanks @markiantorno and @grahamegrieve :

I noticed https://github.com/hapifhir/org.hl7.fhir.core/commit/e5a05f5562c81cf4c135acfc40ccbe6cfed1d81b is included and  released as part of https://github.com/hapifhir/org.hl7.fhir.core/releases/tag/5.5.3
adding class ClientHeaders for stu3/r4/r5.

A great step!

But how do I ingest my custom clientheaders into the validator_cli.jar?
Do I need to fork the source code, and build my own version?

**Comment by grahamegrieve** [comment]
well, we wanted to get the infrastructure in place before we talked about the design of the interface. so that's what comes next. Make a new issue where we can talk about that. I think my idea was to pass in a file with headers in it, but Mark my have a different idea

**Comment by david-simons** [comment]
> I think my idea was to pass in a file with headers in it

Thank you!  Similar to my thoughts - some of these parameters may change per call, such as Bearer token values.

As I wrote earlier:
> a generic -httpHeaders <file> parameter, allowing anyone to ingest one or more custom HTTP parameters, be it basic auth, be it an bearer auth, be it an api-version, etc. 
> These would be in the content of the <file>, on separate lines, for example:
```
Authorization: Bearer TOKEN, or Basic USER:PWD
Proxy-Authorization: Basic USER:PWD
api-version: 1
etc.
```

**Comment by david-simons** [comment]
> Make a new issue where we can talk about that.

Created #603

This one can probably be closed.

**Comment by markiantorno** [comment]
This issue was closed as part of https://github.com/hapifhir/org.hl7.fhir.core/pull/599

@david-simons please test and see if it fits your use case. You should be able to pass headers and basic auth in with no issue now

**Comment by david-simons** [comment]
> @david-simons please test and see if it fits your use case. You should be able to pass headers and basic auth in with no issue now

Thank you @markiantorno - my need is to do this as CLI parameter, not from within Java. Hence I had created #603.
