### ISSUE TITLE
Validator:  marking valid ICD-10 codes as Errors

### ISSUE THREAD

**Issue by cragun47** [hapifhir/org.hl7.fhir.core#593]
See attached file:  FailingOvarian.json.

It references the following condition:
```json
        "code": {
          "coding": [ {
            "system": "http://hl7.org/fhir/sid/icd-10",
            "code": "C56.9",
            "display": "Ovarian Cancer"
          } ],
          "text": "Ovarian Cancer"
        },
```

Which produces the following error when running the validator:
```
Error @ Bundle.entry[3].resource.ofType(Condition).code.coding[0] (line 258, col24) : The code "C56.9" is not valid in the system http://hl7.org/fhir/sid/icd-10; The code provided (http://hl7.org/fhir/sid/icd-10#C56.9) is not valid in the value set 'All codes known to the system' (from http://tx.fhir.org/r4) for 'http://hl7.org/fhir/sid/icd-10#C56.9'
```

Using the following CLI: `java -jar validator_cli.jar FailingOvarian.json -version 4.0.1 -ig https://alvearie.io/alvearie-fhir-ig`

*However, C56.9  should be a valid code for icd-10*

The code is found in ICD-10-cm

If the input is changed to the following, there is no error.
```json
        "code": {
          "coding": [ {
            "system": "http://hl7.org/fhir/sid/icd-10-cm",
            "code": "C56.9",
            "display": "Ovarian Cancer"
          } ],
          "text": "Ovarian Cancer"
        },
```

In the same file, the following J21.8 validates without problem, so it is not the `http://hl7.org/fhir/sid/icd-10` of itself.

```json
        "code": {
          "coding": [ {
            "system": "http://hl7.org/fhir/sid/icd-10",
            "code": "J21.8",
            "display": "Staph aureus bronchiolitis"
          } ],
          "text": "Staph aureus bronchiolitis"
        },
```

Thus an error for C56.9 seems an omission .

_Thanks for your patience with a newcomer.  Thanks also for ignoring other warnings in my sample file._

System: MacBook Pro running macOS 11.5.1
- FHIR Validation tool Version 5.4.11 (Git# 1b4c675c19f6). Built 2021-08-25T23:38:40.103Z (47 hours old)
- Java:   11.0.9.1 from /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home on x86_64 (64bit). 4096MB available
-  Paths:  Current = /Users/cragun/Downloads, Package Cache = /Users/cragun/.fhir/packages
-  Params: FailingOvarian.json -version 4.0.1 -ig https://alvearie.io/alvearie-fhir-ig

**Comment by grahamegrieve** [comment]
is this still a problem?

**Comment by cragun47** [comment]
@grahamegrieve Yes. This still fails.  I just checked with the latest .jar `FHIR Validation tool Version 5.6.1 (Git# 9717d321b4b4). Built 2021-11-26T15:21:45.67Z (4 days old)` using the `FailingOvarian.json` and got this Error:

```
Error @ Bundle.entry[3].resource.ofType(Condition).code.coding[0] (line 258, col24): The code "C56.9" is not valid in the system http://hl7.org/fhir/sid/icd-10; The code provided (http://hl7.org/fhir/sid/icd-10#C56.9) is not valid in the value set 'All codes known to the system' (from http://tx.fhir.org/r4) for 'http://hl7.org/fhir/sid/icd-10#C56.9'
```
