### ISSUE TITLE
List profile url is incorrect.

### ISSUE THREAD

**Issue by markiantorno** [hapifhir/org.hl7.fhir.core#611]
In r4, ListResource has a profile url of `profile="http://hl7.org/fhir/StructureDefinition/ListResource"`, however, touchstone validation throws an warning when validating the server metadata, if the ListResource profile url is not `profile="http://hl7.org/fhir/StructureDefinition/List"`.

Looking at R5, it appears this issue was resolved and the correct url was used.

Can we switch the R4 ListResource `@ResourceDef` tag to use the proper url.

**Comment by markiantorno** [comment]
@katiesmilecdr once the next release of HAPI/Smile goes out, please confirm this solves the issue.

**Comment by tanvishah9696** [comment]
Generally HL7 version bump updates only occur at a certain release time but this issue needs an update to be moved earlier.
