### ISSUE TITLE
Feature request: Validator option to display resource id

### ISSUE THREAD

**Issue by christiangentges** [hapifhir/org.hl7.fhir.core#619]
We use the Validator to retrospectively validate bundles of FHIR resources. 
Regarding the validation output: Is there an option to get the respective resource id instead of (or in addition to) the entry number of the incorrect resource within the bundle?

**Comment by grahamegrieve** [comment]
which particular output is this?

**Comment by christiangentges** [comment]
We are running the standalone validator in Windows Powershell with calls like this. My question is about the output of both of the following calls, but mostly about the first one:
1)
`java -jar validator_cli.jar {base}/Patient?_sort=-_lastUpdated"&"_count=10"&"_skip=0 -version 4.0.1 -ig IG_Packets/de.medizininformatikinitiative.kerndatensatz.person-2.0.0-alpha3.tgz -tx n/a -strictExtensions -hintAboutNonMustSupport`
or
2)
`java -jar validator_cli.jar {base}/Patient?_sort=-_lastUpdated"&"_count=10"&"_skip=0 -version 4.0.1 -ig IG_Packets/de.medizininformatikinitiative.kerndatensatz.person-2.0.0-alpha3.tgz -tx n/a -strictExtensions -hintAboutNonMustSupport -output test.txt`

This is an excerpt of the output of the first call:
`  Warning @ Bundle.entry[0].resource.ofType(Patient).contact[0].extension[0].value.ofType(CodeableConcept).coding[0] (line 42, col22) : A code with no system has no defined meaning. A system should be provided     
  Warning @ Bundle.entry[0].resource.ofType(Patient).extension[2].value.ofType(CodeableConcept).coding[0] (line 91, col18) : A code with no system has no defined meaning. A system should be provided
  Warning @ Bundle.entry[0].resource.ofType(Patient).extension[5].value.ofType(CodeableConcept).coding[0] (line 113, col18) : A code with no system has no defined meaning. A system should be provided
  Warning @ Bundle.entry[1].resource.ofType(Patient).contact[0].extension[0].value.ofType(CodeableConcept).coding[0] (line 217, col22) : A code with no system has no defined meaning. A system should be provided    
  Warning @ Bundle.entry[1].resource.ofType(Patient).extension[0].extension[0].value.ofType(CodeableConcept).coding[0] (line 245, col22) : A code with no system has no defined meaning. A system should be provided  
  Warning @ Bundle.entry[1].resource.ofType(Patient).extension[2].value.ofType(CodeableConcept).coding[0] (line 263, col18) : A code with no system has no defined meaning. A system should be provided
  Warning @ Bundle.entry[1].resource.ofType(Patient).extension[3].value.ofType(CodeableConcept).coding[0] (line 274, col18) : A code with no system has no defined meaning. A system should be provided
  Warning @ Bundle.entry[2].resource.ofType(Patient).contact[0].extension[0].value.ofType(CodeableConcept).coding[0] (line 385, col22) : A code with no system has no defined meaning. A system should be provided    
  Warning @ Bundle.entry[2].resource.ofType(Patient).contact[1].extension[0].value.ofType(CodeableConcept).coding[0] (line 414, col22) : A code with no system has no defined meaning. A system should be provided    
  Warning @ Bundle.entry[2].resource.ofType(Patient).extension[0].extension[0].value.ofType(CodeableConcept).coding[0] (line 442, col22) : A code with no system has no defined meaning. A system should be provided  
  Warning @ Bundle.entry[2].resource.ofType(Patient).extension[2].value.ofType(CodeableConcept).coding[0] (line 460, col18) : A code with no system has no defined meaning. A system should be provided
  Warning @ Bundle.entry[2].resource.ofType(Patient).extension[3].value.ofType(CodeableConcept).coding[0] (line 471, col18) : A code with no system has no defined meaning. A system should be provided`

The number in Brackets after "entry" gives a hint, which resource this refers to, but this needs some data wrangling with another call of the FHIR search query itself. This could even be impossible to retrace, if the data on the FHIR Server has changed since the HAPI validator call.

So I think it could be useful, to have an option to get the resource id directly in the output.
