### ISSUE TITLE
Validator: tx server SSL/TLS client certificate authentication possible?

### ISSUE THREAD

**Issue by glichtner** [hapifhir/org.hl7.fhir.core#625]
Hi,

is it possible to use a client certificate when running the validator (validator_cli.jar) for authentication at the terminology server?

I have tried the following syntax using the javax.net.ssl.* parameters (validator_cli.jar version 5.5.7), but it does not seem to work and I can't find any information in the documentation or the the source code:
```shell
java -jar validator_cli.jar \
 -version 4.0.1 \
 -txLog txlog.html \
 -verbose \
 -Djavax.net.ssl.keyStoreType=pkcs12 \
 -Djavax.net.ssl.trustStoreType=jks \
 -Djavax.net.ssl.keyStore=<my-certificate-file>.p12 \
 -tx https://<custom-tx-server> \
  [...]
```
Thanks!

**Comment by david-simons** [comment]
see #603 :)
