### ISSUE TITLE
Remove hapi dependencies

### ISSUE THREAD

**Issue by patrick-werner** [hapifhir/org.hl7.fhir.core#63]
### Remove hapi dependencies
fhir core validation and cli validation are depending on:
```xml
<dependency>
    <groupId>ca.uhn.hapi.fhir</groupId>
    <artifactId>hapi-fhir-structures-r4</artifactId>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>ca.uhn.hapi.fhir</groupId>
    <artifactId>hapi-fhir-validation-resources-r4</artifactId>
    <scope>test</scope>
</dependency>
```
- removing the structures dependency causes https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.validation/src/test/java/org/hl7/fhir/validation/tests/InstanceValidatorR4Test.java to fail. As this is an hapi specific test this could/should be moved to the hapi repo.
- fhir validation-resources should be part of core.

**Comment by grahamegrieve** [comment]
@jamesagnew are you ok with this?

**Comment by jamesagnew** [comment]
Yeah, those were added only for unit tests and I'm not opposed to removing them given that the unit test doesn't work currently.

**Comment by grahamegrieve** [comment]
already sorted.
