### ISSUE TITLE
FormatUtilities firstIndexOf throws ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by alexanderkiel** [hapifhir/org.hl7.fhir.core#64]
For example in `org.hl7.fhir.r5.formats.FormatUtilities` line 143 in method `firstIndexOf` will show a `ArrayIndexOutOfBoundsException` if char not found and input less than 1000 bytes long.

Fix: `Math.max` has to be replaced by `Math.min`.

I first wanted to create a pull request, but will better not touch the code without proper test execution.

Got the  `ArrayIndexOutOfBoundsException` using validator JAR with a profile hosted by redirect. Problem is that `ValidationEngine.loadProfileFromUrl` will not follow redirects.

**Comment by grahamegrieve** [comment]
fixed

**Comment by alexanderkiel** [comment]
Thanks!
