### ISSUE TITLE
PlanDefinition search param "definition" should traverse action hierarchy using path: PlanDefinition.repeat(action).definition

### ISSUE THREAD

**Issue by tyfoni-systematic** [hapifhir/org.hl7.fhir.core#651]
The search param definition:
https://github.com/hapifhir/org.hl7.fhir.core/blob/f695023d6fbf5c94d3b227e551416c68250095b7/org.hl7.fhir.r4/src/main/java/org/hl7/fhir/r4/model/PlanDefinition.java#L8061

But according to FHIR R4 (http://hl7.org/fhir/R4/plandefinition.html) the action element can be nested.

With the existing search param definition, doing a search with INCLUDE_DEFINITION, only the top level action resources are included.

If instead using a path,  PlanDefinition.repeat(action).definition, then INCLUDE_DEFINITION search will return all action resources.

**Comment by grahamegrieve** [comment]
This is an issue with the underlying spec. To do: figure out all the cases where this happens
