### ISSUE TITLE
Next FHIR release date

### ISSUE THREAD

**Issue by andrewxian** [hapifhir/org.hl7.fhir.core#657]
Hi,

The latest FHIR release is 5.5.3 from https://github.com/hapifhir/hapi-fhir/releases . Is it possible for me to know the next release date for release 5.5.4 or release 5.6? 

It would be great to have a FHIR roadmap doc but I do not find it anywhere.

**Comment by vassilpeytchev** [comment]
Hello @andrewxian,

Your question is better raised at https://github.com/hapifhir/hapi-fhir/issues, this is a different repository.

**Comment by andrewxian** [comment]
@vassilpeytchev , Thanks. I will close this ticket.

**Comment by jamesagnew** [comment]
@andrewxian technically the google group would be the place to ask: https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

GitHub issues are for reporting bugs and requesting enhancements, not for asking questions please.

**Comment by jamesagnew** [comment]
Incidentally, HAPI FHIR 5.6.0 will be released this week.
