### ISSUE TITLE
Validate Search parameter combinations

### ISSUE THREAD

**Issue by vassilpeytchev** [hapifhir/org.hl7.fhir.core#665]
When using the [search parameter combination extension](http://hl7.org/fhir/R4/extension-capabilitystatement-search-parameter-combination.html), there is no validation that the constituent parameters listed inside are actual parameters. My understanding is that for a combination to be valid, the individual components each needs to exist as a parameter.

Here is an example of a parameter combination, where one of the components doesn't exist as a search parameter:
```
"resource" : [
        { "extension": [
            {
              "extension": [
                {
                  "url": "required",
                  "valueString": "patient"
                },
                {
                  "url": "required",
                  "valueString": "random"
                }
              ],
              "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-search-parameter-combination"
            }
          ],
          "type" : "AllergyIntolerance",
          [...]
```

**Comment by grahamegrieve** [comment]
the spec doesn't say that the parameters have to be defined. So it probably can't be an error - just a warning, or maybe a best practice. Will consult Zulip

**Comment by vassilpeytchev** [comment]
Zulip topic: https://chat.fhir.org/#narrow/stream/179177-conformance/topic/Search.20Parameter.20Combination.20Extension
