### ISSUE TITLE
Exception of R3R4 conversion

### ISSUE THREAD

**Issue by sowu880** [hapifhir/org.hl7.fhir.core#667]
Hi team,

When I run validation cli as :
```
java -jar validator_cli.jar Stu3ChargeItem.json -version 3.0 -to-version 4.0 -output output.json
```
It throw exceptions:

![image](https://user-images.githubusercontent.com/57981365/142574446-3b19d3b1-7719-4344-9e22-22d016d2d5da.png)

I also try this command line on other stu3 resources, most of them will throw exceptions.

Do I use the validation tool in the right way? 

Besides, can I use my .map files as input?

**Comment by markiantorno** [comment]
Hi, to better help resolve this issue, please provide an example file you are attempting to convert so we can replicate the issue you are experiencing.

**Comment by sowu880** [comment]
[Stu3ChargeItem.zip](https://github.com/hapifhir/org.hl7.fhir.core/files/7630705/Stu3ChargeItem.zip)

Here is a example stu3 resource.
