### ISSUE TITLE
CLI Validator doesn't Exit with Non-Zero Code on Errors

### ISSUE THREAD

**Issue by alexanderkiel** [hapifhir/org.hl7.fhir.core#69]
We like to use the Validator Jar on command line in CI to validate our profiles against examples. For CI it would be very helpful, if the validator wouldn't exit with code zero on errors so the CI errors also.

**Comment by grahamegrieve** [comment]
ok done next release - will now exit with error code == number of errors found

**Comment by alexanderkiel** [comment]
Thanks @grahamegrieve. Unfortunately using the number of errors as exit code isn't the way exit codes are used normally (at least in POSIX - not sure about Windows). The concrete exit code should describe the class of error occurred. Just using 1 for all error cases is good enough. Here is a good read: https://shapeshed.com/unix-exit-codes/
