### ISSUE TITLE
URI support for ldap:

### ISSUE THREAD

**Issue by JohnMoehrke** [hapifhir/org.hl7.fhir.core#692]
request that "ldap:" be added as a legitimate URI prefix for uri datatype.

I have a need for recording .system elements that are X.500 names. I have determined that the proper way to convert X.500 names into a URL is to use "ldap://". (also legitimate URI for ldap directories)
[ldap](https://datatracker.ietf.org/doc/html/rfc4516)

The ldap: method has an additional wrinkle in that it is used when the x.500 directory has no ldap endpoint, thus there would be no hostname in the ldap://{hostname}/{path}. Thus the convention is to use "ldap:///{path}"

see [IG creation chat](https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/uri.20rules.3F)

I looked for a URN solution for X.500; but did not find one. Would be glad to switch to that solution.

I have a use-case where an identifier (user identifier) is an X.500, made up of an X.500 path for the issuer (system) ( "CN=John Miller,OU=Harris,O=HITS,L=Melbourne,ST=FL,C=US" ), and an X.500 for the user ("UID=kskagerb"). The user is just a value string.  I converted the X.500 of the system to an "ldap://" url; which included url encoding, but the builder complains
```
      "who" : {
        "identifier" : {
          "system" : "ldap:///CN%3DSAML%20User%2COU%3DHarris%2CO%3DHITS%2CL%3DMelbourne%2CST%3DFL%2CC%3DUS",
          "value" : "UID=kskagerb"
        }
      },
```

the validation error is
```
Identifier.system must be an absolute reference, not a local reference
```

Note same error if I add a hostname to the url.

**Comment by grahamegrieve** [comment]
Is this still a problem? want to submit a test case (just attach a failing resource to the issue)

**Comment by JohnMoehrke** [comment]
confirmed that ldap is working. It also works for ldap:/// which is the form for ldap with no hostname.
