### ISSUE TITLE
ConceptMap translate method has an always true condition

### ISSUE THREAD

**Issue by paul-robson-validic** [hapifhir/org.hl7.fhir.core#698]
**Describe the bug**
When translating Codes via the ConceptMapEngine, there is a loop condition that is always true. The wrong variable is being checked against null when determining whether the source Code is present multiple times in the ConceptMap.

**To Reproduce**
1. Call the translate method on a ConceptMapEngine with a valid ConceptMap and a Coding (don't include a system since that method is not implemented yet)
2. Stop debugger on [this line](https://github.com/hapifhir/org.hl7.fhir.core/blob/f967c088795f3214cd5470880194f68e7eb8f417/org.hl7.fhir.r4/src/main/java/org/hl7/fhir/r4/terminologies/ConceptMapEngine.java#L74)
3. The `ct` variable will always be null.

**Expected behavior**
Check that the code hasn't been seen in the loop before by doing a null check against the `ct` variable on L:67 instead of against the `e` (current loop iteration) variable.

**Screenshots**
![image](https://user-images.githubusercontent.com/87040393/147123653-6a2d6b7b-a6d3-4b2f-9566-d867c2c68607.png)

**Environment (please complete the following information):**
 - HAPI FHIR Version r4
 - OS: MacOS Big Sur 11.6.1
 - Browser: N/A

**Additional context**
Checking the code hasn't been seen already in the loop appears to be implemented correctly further down in the method on L:79. It's just in the first loop that the wrong variable is being checked.

**Comment by paul-robson-validic** [comment]
Pull request to resolve [here](https://github.com/hapifhir/org.hl7.fhir.core/pull/699)

**Comment by dotasek** [comment]
Fixed in #699
