### ISSUE TITLE
FHIRPathEngine does not guess System for `code`, `string`, and `uri` when validating memberOf as operation

### ISSUE THREAD

**Issue by nigtrifork** [hapifhir/org.hl7.fhir.core#703]
Hi

I stumbled upon this today, because I had a problem getting Hapi to validate an identifier which has a required binding on `identifier.system` to some ValueSet. After some digging, I discovered that the issue was that the validator did not infer the system, i. e. `ca.uhn.fhir.context.support.ConceptValidationOptions#isInferSystem` returned `false`.

Then I found these two similar methods in the FHIRPathEngine class: `opMemberOf` and `funcMemberOf`. They follow the same pattern more or less, except they differ on these lines: [FHIRPathEngine.java#L2368](https://github.com/hapifhir/org.hl7.fhir.core/blob/8706b3c4a4715ba4d8e53bd5a0b384e02fd2db54/org.hl7.fhir.r5/src/main/java/org/hl7/fhir/r5/utils/FHIRPathEngine.java#L2368) and [FHIRPathEngine.java#L4020](https://github.com/hapifhir/org.hl7.fhir.core/blob/8706b3c4a4715ba4d8e53bd5a0b384e02fd2db54/org.hl7.fhir.r5/src/main/java/org/hl7/fhir/r5/utils/FHIRPathEngine.java#L4020), where `funcMemberOf` specifies that system should be inferred when validating "code", "string", and "uri", but `opMemberOf` does not.

Is this a mistake, or is it intentional?

The ValueSet: https://hl7.dk/fhir/core/ValueSet-dk-core-cpr-identifier-system.html
The StructureDefinition for the identifier: https://hl7.dk/fhir/core/StructureDefinition-dk-core-cpr-identifier.html
The profile for the Patient resource for which validation fails: https://hl7.dk/fhir/core/StructureDefinition-dk-core-patient.html

**Comment by jkiddo** [comment]
@lmckenzi would you happen to know that?

**Comment by lmckenzi** [comment]
This *seems* like a mistake to me.  @grahamegrieve?

**Comment by jvitrifork** [comment]
@grahamegrieve ?

**Comment by jvitrifork** [comment]
@lmckenzi what can be done to draw more attention to this issue?

**Comment by lmckenzi** [comment]
@markiantorno?
(Grahame's on holiday for the next little bit)

**Comment by grahamegrieve** [comment]
yes I agree

**Comment by grahamegrieve** [comment]
fixed
