### ISSUE TITLE
ValueSet PlanDefinition search param "reference" should also work for include.valueSet

### ISSUE THREAD

**Issue by tyfoni-systematic** [hapifhir/org.hl7.fhir.core#736]
The definition description says that the reference can be to a code system **or an imported value set**:
`
@SearchParamDefinition(name="reference", path="ValueSet.compose.include.system", description="A code system included or excluded in the value set or an imported value set", type="uri" )
`

But the path is only concerned with code system. 

I think the path should be:
`
@SearchParamDefinition(name="reference", path="ValueSet.compose.include.system | ValueSet.compose.include.valueSet", description="A code system included or excluded in the value set or an imported value set", type="uri" )
`

I need this when I try to find value sets for invalidation of preexpansion after changes to underlying code system or value set.

**Comment by grahamegrieve** [comment]
Where is this? but most likely, your issue is with the specification, not the java code, and should be taken up on chat.fhir.org
