### ISSUE TITLE
FHIR R5 validator is not validating structure definition regex expression inside ElementDefinition.type

### ISSUE THREAD

**Issue by Shob-dev** [hapifhir/org.hl7.fhir.core#737]
Added below ElementDefinition inside custom structure definition to validate SSN field to be specific regex pattern which validator is not doing any validation on ssn value format.

 {
        "id": "Patient.identifier:ssn.value",
        "path": "Patient.identifier.value",
        "short": "The value that is unique within the system.",
        "definition": "The portion of the identifier typically relevant to the user and which is unique within the context of the system.",
        "comment": "If the value is a full URI, then the system SHALL be urn:ietf:rfc:3986.  The value's primary purpose is computational mapping.  As a result, it may be normalized for comparison purposes (e.g. removing non-significant whitespace, dashes, etc.)  A value formatted for human display can be conveyed using the [Rendered Value extension](http://hl7.org/fhir/R4/extension-rendered-value.html). Identifier.value is to be treated as case sensitive unless knowledge of the Identifier.system allows the processer to be confident that non-case-sensitive processing is safe.",
        "min": 1,
        "max": "1",     
        "base": {
          "path": "Identifier.value",
          "min": 0,
          "max": "1"
        },
        **_"type": [
          {
  "extension": [
          {
            "url": "http://hl7.org/fhir/StructureDefinition/regex",
            "valueString": "(\\d{3}-\\d{2}-\\d{4})"
          }
        ],
            "code": "string"
          }
        ],_**
        "example": [
          {
            "label": "General",
            "valueString": "123456"
          }
        ],
        "constraint": [
          {
            "key": "ele-1",
            "severity": "error",
            "human": "All FHIR elements must have a @value or children",
            "expression": "hasValue() or (children().count() > id.count())",
            "xpath": "@value|f:*|h:div",
            "source": "http://hl7.org/fhir/StructureDefinition/Element"
          }
        ],
        "mustSupport": true,
        "isModifier": false,
        "isSummary": true
      }

However if we add the extension field under ElementDefinition directly FHIR R5 validator is validating ssn value format. But as per FHIR structure definition https://www.hl7.org/fhir/extension-regex.html  for regex the **Context of Use: Use on Element ID Questionnaire.item or Element ID ElementDefinition**
 {
        "id": "Patient.identifier:ssn.value",
        "path": "Patient.identifier.value",
        "short": "The value that is unique within the system.",
        "definition": "The portion of the identifier typically relevant to the user and which is unique within the context of the system.",
        "comment": "If the value is a full URI, then the system SHALL be urn:ietf:rfc:3986.  The value's primary purpose is computational mapping.  As a result, it may be normalized for comparison purposes (e.g. removing non-significant whitespace, dashes, etc.)  A value formatted for human display can be conveyed using the [Rendered Value extension](http://hl7.org/fhir/R4/extension-rendered-value.html). Identifier.value is to be treated as case sensitive unless knowledge of the Identifier.system allows the processer to be confident that non-case-sensitive processing is safe.",
        "min": 1,
        "max": "1",
        **_"extension": [
          {
            "url": "http://hl7.org/fhir/StructureDefinition/regex",
            "valueString": "(\\d{3}-\\d{2}-\\d{4})"
          }
        ],_**
        "base": {
          "path": "Identifier.value",
          "min": 0,
          "max": "1"
        },
        "type": [
          {
            "code": "string"
          }
        ],
        "example": [
          {
            "label": "General",
            "valueString": "123456"
          }
        ],
        "constraint": [
          {
            "key": "ele-1",
            "severity": "error",
            "human": "All FHIR elements must have a @value or children",
            "expression": "hasValue() or (children().count() > id.count())",
            "xpath": "@value|f:*|h:div",
            "source": "http://hl7.org/fhir/StructureDefinition/Element"
          }
        ],
        "mustSupport": true,
        "isModifier": false,
        "isSummary": true
      },

**Comment by Shob-dev** [comment]
I see this issue is due to InstanceValidator.java checkPrimitive() method is looking for regex extension url under ElementDefinition rather than looking under ElementDefinition.type attribute as per https://www.hl7.org/fhir/extension-regex.html

**Comment by Shob-dev** [comment]
Thank you for the quick fix and great work. However is the fix available only in 5.6.X? we are using HAPI 5.5.1 version and when I pull the code I am not seeing this fix available in this version.

**Comment by grahamegrieve** [comment]
@jamesagnew decides stuff like that, not me.

**Comment by Shob-dev** [comment]
Thank you for the quick reply. @jamesagnew  is there anyway we can get this fix in 5.5.1 instead of upgrading to 5.6.X?
