### ISSUE TITLE
Version convertors should understand version Extensions

### ISSUE THREAD

**Issue by lawley** [hapifhir/org.hl7.fhir.core#765]
We've started to pre-adopt a number of R5 elements into our R4 implementation using version Extensions:

http://hl7.org/fhir/[version]/StructureDefinition/extension-[Path]

Recent testing with the VersionConvertorFactory_40_50 indicates that such extensions are ignored which was a surprise.
I had hoped that, at least, converting an R4 resource with such extensions to an R5 resource would at least populate the R5 resource elements appropriately.

I then hoped that I could use the BaseAdvisor_40_50 to do this myself, but all it provides is the Extension and not the corresponding R5 element (to the R4 element that the Extension was attached to).

Has any thought been given to either implementing this generically, or providing more hooks for custom implementation?  (e.g., creating the relevant Extensions when going from newer (R5) to older (R4) resources)

**Comment by grahamegrieve** [comment]
General scheme for doing this:

* if an extension is found in the source that has this kind of path 
* if the path corresponds to this + a property that this has 
* don't convert the extension, set the property with the converted value
* blow up if that doesn't work as expected
