### ISSUE TITLE
New Error Running FHIR Validator (without existing .fhir cache)

### ISSUE THREAD

**Issue by ljoy913** [hapifhir/org.hl7.fhir.core#789]
Follow the instructions at [Using the FHIR Validator](https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator)

1. Download the validator [validator_cli.jar](https://github.com/hapifhir/org.hl7.fhir.core/releases/latest/download/validator_cli.jar)
2. Run the validator `java -jar validator_cli.jar <fhirBundle.json>`

```
Load FHIR vcurrent from hl7.fhir.r5.core#5.0.02022-04-18 14:17:56.100 [main] 
INFO  o.h.f.u.npm.BasePackageCacheManager [BasePackageCacheManager.java:80] 
Failed to resolve package hl7.fhir.r5.core#5.0.0 from server: http://packages.fhir.org 
(Invalid HTTP response 404 from http://packages.fhir.org/hl7.fhir.r5.core/5.0.0 
(Not Found) (content in /tmp/fhir-http-2.log))
```

This is a new error as this was working last week.

**Comment by grahamegrieve** [comment]
This was a transient error with the package server, not an error in the code.
