### ISSUE TITLE
Exception in evaluate when transforming StructureMap

### ISSUE THREAD

**Issue by mklumpen** [hapifhir/org.hl7.fhir.core#802]
org.hl7.fhir.r5.utils.structuremap.StructureMapUtilities#runTransform() is not correctly processing EVALUTE transform.

In the following transform:

group tutorial(source src : TLeft, target tgt : TRight) {
    src -> tgt.a = evaluate(src, src.is(TLeft)) "eval";
}

The following exception is thrown:
Exception in thread "main" org.hl7.fhir.exceptions.FHIRException: Exception executing transform tgt.a = evaluate(srcsrc.is(TLeft)) on Rule "eval": Found a value for src, but it has a type of TLeft and cannot be treated as a string. Context: tgt.a = evaluate(srcsrc.is(TLeft))Exception in thread "main" org.hl7.fhir.exceptions.FHIRException: Exception executing transform tgt.a = evaluate(srcsrc.is(TLeft)) on Rule "eval": Found a value for src, but it has a type of TLeft and cannot be treated as a string. Context: tgt.a = evaluate(srcsrc.is(TLeft))

This looks like a problem in the following code in runTransform:

          if (expr == null) {
            expr = fpe.parse(getParamStringNoNull(vars, tgt.getParameter().get(0), tgt.toString()));
            tgt.setUserData(MAP_WHERE_EXPRESSION, expr);
          }

This is mostly correct in analyzeTransform, but both methods set the resulting expression under MAP_WHERE_EXPRESSION instead of MAP_EXPRESSION. The correct implementation in both methods should be:

            expr = fpe.parse(getParamString(vars, tgt.getParameter().get(tgt.getParameter().size() - 1)));
            tgt.setUserData(MAP_EXPRESSION, expr);

**Comment by dotasek** [comment]
I've included a test case that provides a working example, however, it appears to work as intended for me:

https://github.com/FHIR/fhir-test-cases/pull/107

@mklumpen does this test case look like what you were attempting? If not, could you provide something similar to illustrate the issue?

**Comment by mklumpen** [comment]
The test will only fail when the original source is a StructureMap parsed from JSON/XML. Converting from a .map initializes the structure with the correct FHIRPath expressions. I have converted your .map to .json, but don't have permissions to add it to the branch and not sure how to include it into the test case.

**Comment by mklumpen** [comment]
@dotasek Thanks for providing the instructions. I have pushed my changes to my branch in https://github.com/mklumpen/fhir-test-cases. Apologize in advance, that I'm not very familiar with this project and don't know how to run the actual tests to reproduce the issue.

**Comment by dotasek** [comment]
@mklumpen not a problem, thank you for taking time to help us reproduce what you're experiencing. I will take a look at what you've added, and see if that gets me any further.

**Comment by dotasek** [comment]
@mklumpen I needed to make some changes in order to run it, but your test replicated the bug. There are now two PRs related to it. When they merge, I will let you know.

https://github.com/hapifhir/org.hl7.fhir.core/pull/807
https://github.com/FHIR/fhir-test-cases/pull/108

**Comment by mklumpen** [comment]
Looks like quite a few changes! I still see in StructureMapUtilities that it is looking to see if there is an existing expression using the  MAP_EXPRESSION key, but then setting it using MAP_WHERE_EXPRESSION. I don't think this will cause an error, since it will just rebuild the expression every time, but not sure if this is what is intended.

**Comment by dotasek** [comment]
@mklumpen Thanks for the reminder about MAP_EXPRESSION, I put in a subsequent pull to address it. 

There wasn't much runtime code changed here, just the two lines you specified. The testing code had to be made more general to actually test for the error you reported; that's what the bulk of the work was.

**Comment by dotasek** [comment]
MAP_EXPRESSION is now used as of #811
