### ISSUE TITLE
Validation error but only in Java-based validator

### ISSUE THREAD

**Issue by camelx** [hapifhir/org.hl7.fhir.core#816]
Hi!

I have a profile of QuestionnaireResponse resource. I'm validating a Structure Definition of that profile and I'm getting an error like this:
`Error generating Snapshot: QuestionnaireResponse.item.item.item has no children (QuestionnaireResponse.item.item.item) and no types in profile Kwestionariusz bilansowy.item.item (this usually arises from a problem in the differential)`

I have no idea what causes the problem. I've uploaded the profile to Simplifier (https://simplifier.net/nfz-test/plnfzcchealthbalancequestionnaireresponse-duplicate-2) and to me it looks fine. What is important, it validates positive (with Simplifier validator).

I need to use IG publisher but the publishing process stops at that error. 

Could you please help me with this issue? Is it really problem with the profile or maybe I've found a bug in the validator? ;)

I could provide any additional information, if needed..

Regards,
Marcin

**Comment by grahamegrieve** [comment]
so you are validating a questionnaire response against this profile when you get the error?

**Comment by dotasek** [comment]
Closed due to inactivity.
