### ISSUE TITLE
CLI: relative references (e.g. 'List/1') should be always be treated as per '-assumeValidRestReferences'

### ISSUE THREAD

**Issue by DarthGizka** [hapifhir/org.hl7.fhir.core#819]
The CLI option `-assumeValidRestReferences` exists to allow the validator to assume that REST-format URLs follow the rules (i.e. end in `/{type}/{id})`, which in turn allows the validator to verify that the target of a reference is one of the allowed types. Thus it can reject an author reference like 'http://fhir.example/Invoice/666' out of hand, even if the target resource is not available (i.e. not bodily included in the outer resource being validated). This works like a charm.

However, the validator also applies the `assumeValidRestReferences` setting if a relative reference is used (e.g. 'Patient/42'). More precisely, the resource type given in such a reference is **not** checked against the allowable types **unless** the `assumeValidRestReferences` option is specified, even though a relative reference must per definitionem have the form `{type}/{id}`. In contrast to absolute RESTiform URLs there is no leeway here; any matching resource - whether present to be looked at or not - must perforce have the resource type given in the relative reference.

Example:

```xml
<Bundle xmlns="http://hl7.org/fhir">
	<type value="collection"/>
	<entry>
		<fullUrl value="http://zrbj.example/Composition/1"/>
		<resource>
			<Composition>
				<id value="2"/>
				<status value="final"/>
				<type>
					<coding>
						<system value="http://loinc.org"/>
						<code value="11502-2"/>
					</coding>
				</type>
				<date value="2022-05-25"/>
				<author>
					<reference value="Invoice/1"/>
				</author>				
				<title value="reference implies the wrong resource type"/>
			</Composition>
		</resource>
	</entry>
</Bundle>
```

The validator CLI (version 5.6.46) finds the resource type mismatch in the author reference only if `assumeValidRestReferences` is specified. This is not logical.

Moreover, with `assumeValidRestReferences` the validator should flag the mismatch between the logical id specified in `entry.fullUrl` (1) and the one in `entry.resource.id` (2), but it doesn't. Nor does it flag a mismatch in resource type if `entry.fullUrl` is changed to 'http://zrbj.example/List/1' or whatever.

This blind spot should at the very least be documented, because it allows resources to pass validation even if they fail to comply with fundamental rules defined by the standard. The flip side of a mandatory rule is an assumed guarantee (in the eyes of the consumer of a validated resource) - an assumption that happens to be mistaken in this case.

**Comment by grahamegrieve** [comment]
> even though a relative reference must per definitionem have the form {type}/{id}

why? Where does it say that?

**Comment by grahamegrieve** [comment]
Actually, there is. If there's a capability statement and the capability statement says that the system supports the CapabilityStatement endpoint, then anything at http://foo.example/CapabilityStatement/{valid-id} must be a CapabilityStatement. But it's presently out of scope for the validator to know about the CapabilityStatement.
