### ISSUE TITLE
CLI: asterisk as wildcard for -extensions unusable under Windows and prone to globbing elsewhere

### ISSUE THREAD

**Issue by DarthGizka** [hapifhir/org.hl7.fhir.core#824]
Suppressing the extension check - i.e. the opposite of the behaviour of the old `-strictExtensions` parameter - is supposed to be done by passing the parameter [`-extensions *`][8.5]. However, under Windows the JVM globs this (presumably in order to emulate the behaviour of ancient shells for some inexplicable reason), replacing the asterisk with a long list of files present in the current working directory. The validator interprets the first one of these as an extension specification and the rest as a list of files to validate. 

Suppressing the globbing by enclosing the asterisk in double quotes does not work because the globbing is done by java.exe and not by the shell, and java.exe has no clue. 

Suppressing the globbing by enclosing the asterisk in single quotes (*nix style) suppresses the globbing but java.exe fails to remove the quotes, which results in the validator receiving the quoted asterisk and treating it as an extension specification instead of as the 'allow all' wildcard.

One way around this would be to accept `all` and/or `ALL` as a self-explanatory synonym for `*`. 

Another would be to treat `'*'` as a synonym for the asterisk. However, the asterisk is bound to create problems on all supported platforms and will always have to be made non-globbable in some way or other (because Java will glob if the platform shells don't). Requiring the use of single quotes could foul things up for the user in various wonderful ways, since pretty much all shells known to man are fairly bizarre and tend to make even INTERCAL or T-SQL look almost sane in comparison. 

Incidentally, the validator and its documentation (section [8.5 Extensions][8.5] of [Using the FHIR Validator][manual]) disagree on the spelling of the parameter. The former expects `-extensions` but the latter specifies `-extension`.

[8.5]: https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator#UsingtheFHIRValidator-Extensions
[manual]: https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator

**Comment by dotasek** [comment]
@grahamegrieve I concur with @DarthGizka: managing all the special cases around using * as a parameter is messy. Since allowed extensions are URLs, `any` doesn't overlap with possible values, is consistent with most cli language (none, any, all, etc) and should be appropriate.

I'd go as far as to drop support for * and replace it with any.

This is a blocker for completing PR #829, which documents this feature in the help text.

**Comment by grahamegrieve** [comment]
I'm ok with any though I would generally prefer $any to be explicit that it's a special value

**Comment by DarthGizka** [comment]
*nix-style shells like bash will interpret `$any` as an environment variable ...

**Comment by grahamegrieve** [comment]
ahh damm

**Comment by grahamegrieve** [comment]
any it is then
