### ISSUE TITLE
Reference Regex in R4 appears to be ignored in Validation

### ISSUE THREAD

**Issue by dotasek** [hapifhir/org.hl7.fhir.core#826]
When validating a resource in R4, the following reference should be invalid:

```json
{
   "patient": {
      "reference": "Patient/A$1"
   }
}
```

~~According to the R4 spec [here](http://hl7.org/fhir/R4/references.html#literal), the `$` character should not be permitted, but the included resource below is OK according to the validator.~~ This previous was incorrect; see comments below.

```shell
java -jar validator_cli.jar invalid-char-reference.json
```

```json
{
  "resourceType": "ExplanationOfBenefit",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">A human-readable rendering of the ExplanationOfBenefit</div>"
  },
  "identifier": [
    {
      "system": "http://www.example.com",
      "value": "1"
    }
  ],
  "use": "claim",
  "created": "2014-08-16",
  "status": "active",
  "insurer": {
    "reference": "Organization/3"
  },
  "outcome": "complete",
  "insurance": [
    {
      "focal": true,
      "coverage": {
        "reference": "Coverage/NCC1701D"
      }
    }
  ],
  "provider": {
    "reference": "Practitioner/1"
  },
  "type": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/claim-type",
        "code": "oral"
      }
    ]
  },
	"patient": {
		"reference": "Patient/A$1"
	}
}

```

**Comment by grahamegrieve** [comment]
Is it allowed if -assumeValidRestReferences is switched on?

**Comment by dotasek** [comment]
When -assumeValidRestReferences, it shows a warning:

```shell
Warning @ ExplanationOfBenefit.patient (line 41, col3): The syntax of the reference 'Patient/A$1' looks incorrect, and it should be checked
```

Upon re-rereading the spec, the URL does not need to be formatted as a FHIR RESTful server URL at all. The regex provided will evaluate the URL to see if it conforms, but is not a requirement (which is why it's in the notes).

Since the warning is provided with the option above, I think there is nothing to fix, and will mark it as such.
