### ISSUE TITLE
Add support for application/fhir+json

### ISSUE THREAD

**Issue by imadeit** [hapifhir/org.hl7.fhir.core#830]
I am using validator_cli.jar to validate my Terminology Server, which has only implemented application/fhir+json format.
But validator_cli.jar seems only request for application/fhir+xml. 
So when I use validator_cli.jar to validate my Terminology Server with -tx option, by requesting the capability statement, errors are always returned.
By reading the source code, it seems the validator throw an parse exception from JSON, which it is expecting a XML response.
So, would it be possible to specify the data format when requesting for capability statement?
like:
java -jar ./validator_cli.jar data.json -version 4.0.1 -tx http://<my-terminology-server> -contentType application/fhir+json

**Comment by grahamegrieve** [comment]
This should be seamless and automatic - try json first, and if that fails, fall back to json. I thought it worked that way, but apparently not

**Comment by imadeit** [comment]
@grahamegrieve 
Yes, I thought exactly as you do. But unfortunately, it does only request for XML only.
Maybe there is hidden option to set the preferredResourceFormat by calling setPreferredResourceFormat() or something, I was just not able to figure out.

**Comment by grahamegrieve** [comment]
that was a note for when @dotasek looks at this, as he will
