### ISSUE TITLE
`Load profiles-folder* load file: ... - ignored due to error: Unsupported version 4.3.0`

### ISSUE THREAD

**Issue by david-simons** [hapifhir/org.hl7.fhir.core#857]
Getting validator exceptions with validating with _local file_ dependencies in 4.3.0. @grahamegrieve @dotasek 

HLValidator using fhirVersion = 4.3.0

`Load profiles-folder* load file: StructureDefinition-vitalsigns.json - ignored due to error: Unsupported version 4.3.0`

1) traced back to exception in `public Resource loadResourceByVersion` in IgLoader.java, which misses a `4.3` IF clause.
2) `\org.hl7.fhir.core\org.hl7.fhir.r4b\src\main\java\org\hl7\fhir\r4b\model\Constants.java`
    line 42: `public final static String VERSION = "4.3.0-snapshot1";`, change to `"4.3.0"` (without snapshot1)

**Comment by david-simons** [comment]
plus this 4.3.0 IF clause seems to be missing, in IgLoader.java:

```
} else if (fhirVersion.startsWith("4.3")) {
      org.hl7.fhir.r4b.model.Resource res;
      if (fn.endsWith(".xml") && !fn.endsWith("template.xml"))
        res = new org.hl7.fhir.r4b.formats.XmlParser().parse(new ByteArrayInputStream(content));
      else if (fn.endsWith(".json") && !fn.endsWith("template.json"))
        res = new org.hl7.fhir.r4b.formats.JsonParser().parse(new ByteArrayInputStream(content));
      else if (fn.endsWith(".txt") || fn.endsWith(".map"))
        res = new org.hl7.fhir.r4b.utils.StructureMapUtilities(null).parse(new String(content), fn);
      else
        throw new FHIRException("Unsupported format for " + fn);
      r = VersionConvertorFactory_43_50.convertResource(res);
    }
```

**Comment by david-simons** [comment]
I should have linked https://github.com/hapifhir/org.hl7.fhir.core/pull/866 to this Issue, @dotasek .

**Comment by david-simons** [comment]
Would like this to be reopened, @grahamegrieve @dotasek 

while PR #873 helps we're still getting errors like `load file: uv-4.0-common-resource-general-bundle-v1-ILSBundle.structuredefinition.xml - ignored due to error: Unsupported version 4.3.0`.

PR #866 offered a quick hack - temporarily using r4 for missing r4b classes - but requires more work.

![image](https://user-images.githubusercontent.com/6153327/180420507-dbdfed86-fa53-413a-87b9-dc810fa22d01.png)

**Comment by grahamegrieve** [comment]
How do you make the problem happen?

**Comment by cdejonge** [comment]
By just having having an ig pointing to a local folder with profiles needed as dependencies.
> java -jar validator-5.6.52.jar -version 4.3.0 -ig profiles-folder StructureDefinition-Observation.json

This will produce an error line for each file to load from the "profiles-folder":
> load file: ********** - ignored due to error: Unsupported version 4.3.0
