### ISSUE TITLE
Potential Typo in InstanceValidator L2756

### ISSUE THREAD

**Issue by hhund** [hapifhir/org.hl7.fhir.core#858]
There might be a typo in line 2756 of InstanceValidator. 
https://github.com/hapifhir/org.hl7.fhir.core/blob/2aef63e4fb699dee5b54041d87262929063a2384/org.hl7.fhir.validation/src/main/java/org/hl7/fhir/validation/instance/InstanceValidator.java#L2753-L2759
Since the path value in lines 2754, 2755, 2757 and 2758 corresponds to a field in the data type [Quantity](http://hl7.org/fhir/datatypes.html#quantity), I'm assuming that the line 2756 should be (two 's' characters removed):
```
checkFixedValue(errors, path + ".unit", focus.getNamedChild("unit"), fixed.getUnitElement(), fixedSource, "unit", focus, pattern);
```

**Comment by grahamegrieve** [comment]
fixed
