### ISSUE TITLE
uuid not handled as primitive type

### ISSUE THREAD

**Issue by dhufnagel** [hapifhir/org.hl7.fhir.core#862]
When trying to validate a Parameters resource with a valueUuid in parameter, the validator throws an exception: 

> Unable to find type Uuid for element valueUuid with path Parameters.parameter.value[x]

This is because of uuid does not exists in the list of primitives in TypesUtilities: https://github.com/hapifhir/org.hl7.fhir.core/blob/2aef63e4fb699dee5b54041d87262929063a2384/org.hl7.fhir.r5/src/main/java/org/hl7/fhir/r5/utils/TypesUtilities.java#L173

**Comment by grahamegrieve** [comment]
done
