### ISSUE TITLE
CDA To FHIR

### ISSUE THREAD

**Issue by jdeloscobos** [hapifhir/org.hl7.fhir.core#87]
I am trying to transform a CDA to XML with the Validator using the attached command, and after solve different issues previously at this moment i am in this situation, and i don't know how can i fix this issue

Any help will be welcome

Thank you

Juan Antonio

**Comment by jdeloscobos** [comment]
the error is when i am trying to load hl7.fhir.core

**Comment by jdeloscobos** [comment]
the output is
C:\temp> java -jar org.hl7.fhir.validator.jar c:\temp\P1.xml -transform http://h
l7.org/fhir/cda/mapping/ccdaDocumentToFhir -ig hl7.fhir.cda -ig hl7.fhir.core -o
utput c:\temp\bp1.xml
FHIR Validation tool Version 4.0.23-SNAPSHOT - Built 2019-10-02T15:02:10.634+10:
00 - Git 17e7333bcab7
Detected Java version: 1.8.0_221 from C:\Program Files\Java\jre1.8.0_221 on amd6
4 (64bit). 1746MB available
Arguments: c:\temp\P1.xml -transform http://hl7.org/fhir/cda/mapping/ccdaDocumen
tToFhir -ig hl7.fhir.cda -ig hl7.fhir.core -output c:\temp\bp1.xml
Directories: Current = C:\temp, Package Cache = C:\Users\44011322V\.fhir\package
s
  .. connect to tx server @ http://tx.fhir.org
  .. definitions from hl7.fhir.core#current
    (v4.1.0)
+  .. load IG from hl7.fhir.cda
   ... Using version 0.0.1
+  .. load IG from hl7.fhir.core
   ... Using version 4.1.0
 ...Failure: null
java.lang.NullPointerException
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.PrintWriter.<init>(Unknown Source)
        at org.hl7.fhir.r5.validation.ValidationEngine.setMapLog(ValidationEngin
e.java:1293)
        at org.hl7.fhir.r5.validation.Validator.main(Validator.java:504)

**Comment by oliveregger** [comment]
I think the error comes from not setting the log parameter:
-log test.txt

I'm currently working also on transforming cda to fhir, see https://github.com/ahdis/cda-core-2.0/tree/develop to use an updated validator/package to run the transform.
