### ISSUE TITLE
Null keys in map storing FHIR resources by uniqueID 

### ISSUE THREAD

**Issue by sanjan2** [hapifhir/org.hl7.fhir.core#877]
I'm getting null keys for FHIR resources stored in a hash map that should store resources by their canonical URL. Other resources are stored by their id-tag, not their uniqueID-tag, f.e. NamingSytems, ConceptMaps. This slows down the validator considerably, it also means that some resources aren't cached because an existing resource stored with a null key is overwritten by another one with null key.

To reproduce: 
in class r5.context.BaseWorkerContext, method cacheResourceFromPackage, add the line System.out.println(r.getID) to the method after...
if (map == null) {
map = new HashMap<String, ResourceProxy>();
allResourcesById.put(r.fhirType(), map);
}

My setup:
I am running the main method in class org.hl7.fhir.validation.ValidatorCli in Eclipse debug with the following arguments:
./Example_1.xml -version 4.0 -ig ./Profile/ -recurse -show-times -tx n/a

**Comment by grahamegrieve** [comment]
This doesn't make sense. That code has a condition:

 if (r.getId() != null) 

Why do you have resources without ids? 
Why does it matter? 
What does it slow the validator down?

**Comment by sanjan2** [comment]
My question is out of date! My instances that took 5 seconds each to validate with the April version are now down to 1 second. Much obliged, issue closed
