### ISSUE TITLE
Validator: support FHIR version in canonical URL

### ISSUE THREAD

**Issue by ArdonToonstra** [hapifhir/org.hl7.fhir.core#88]
The FHIR spec describes at a few places the use of a FHIR version inside the canonical URL. (http://hl7.org/fhir/versioning.html#mp-version and http://hl7.org/fhir/versions.html#extensions.) This is about providing FHIR versioning inside instances when there is no wrapping envelope to carry a mime-type version parameter.

Although the spec mentioned this as last resort, it is part of the FHIR spec. Therefore, it would be nice if the validator can handle this.

A possible concern may be which FHIR version should be chosen by the validator, the FHIR version in the canonical or the version given in the context?

https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Version.20specifc.20profile.20-.20validation

**Comment by grahamegrieve** [comment]
Needs a rewrite of how the validator engine works to delay loading the correct version. 

What happens if the user specifies a version, and the instance specifies a different version?

**Comment by grahamegrieve** [comment]
what would a test case look like?
