### ISSUE TITLE
R4 FHIRPathEngine resolveConstant of EvaluationContext doesn't support returning multiple values

### ISSUE THREAD

**Issue by shoaibmushtaq25** [hapifhir/org.hl7.fhir.core#881]
In the context of a [conversation](https://chat.fhir.org/#narrow/stream/179266-fhirpath/topic/variables/near/290859425) with @grahamegrieve over zulip chat, 

R4 FHIRPathEngine [public Base resolveConstant(Object appContext, String name, boolean beforeContext) method](https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.r4/src/main/java/org/hl7/fhir/r4/utils/FHIRPathEngine.java#L202) of EvaluationContext Interface doesn't support returning multiple values.

cc: @grahamegrieve

**Comment by grahamegrieve** [comment]
This is already done in the R5 version

**Comment by grahamegrieve** [comment]
This is already done in R5 - just have to copy the same code across
