### ISSUE TITLE
Relax warning to information message when resource conforms to multiple targetProfiles

### ISSUE THREAD

**Issue by rettema** [hapifhir/org.hl7.fhir.core#912]
https://hl7.org/fhir/r4/elementdefinition-definitions.html#ElementDefinition.type.targetProfile states: "If any profiles are specified, then the content must conform to at least one of them." The resource does conform to 'at least one', so we feel this warning should be 'information' in severity at best.

See HL7 FHIR JIRA issue [FHIR-37534](https://jira.hl7.org/browse/FHIR-37534)
See attachments
- custom validation package **multitarget-package.tgz** - **_RENAMED due to unsupported 'tgz' extension upload in issue interface_**
[multitarget-package.gz](https://github.com/hapifhir/org.hl7.fhir.core/files/9491192/multitarget-package.gz)
- test Bundle for validation against custom validation package **bundle-multitargetprofile.json** - **_RENAMED due to unsupported 'json' extension upload in issue interface_**
[bundle-multitargetprofile.txt](https://github.com/hapifhir/org.hl7.fhir.core/files/9491197/bundle-multitargetprofile.txt)

The attached files illustrate the generation of the validation warning message using the current validator_cli.jar version 5.6.58. The validator_cli.jar was downloaded and then executed with the following command and output:

```
PS D:\Projects\fhir\Validator> java -jar validator_cli.jar ./bundle-multitargetprofile.json -version 4.0 -ig ./multitarget-package.tgz                                              Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
FHIR Validation tool Version 5.6.58 (Git# 719f28dcd247). Built 2022-09-04T00:10:05.683Z (39 hours old)
  Java:   1.8.0_202 from C:\Program Files\Java\jdk1.8.0_202\jre on amd64 (64bit). 14384MB available
  Paths:  Current = D:\Projects\fhir\Validator, Package Cache = C:\Users\richard.ettema\.fhir\packages
  Params: ./bundle-multitargetprofile.json -version 4.0 -ig ./multitarget-package.tgz
  Jurisdiction: United States of America
Loading
  Load FHIR v4.0 from hl7.fhir.r4.core#4.0.1 - 4572 resources (00:02.752)
  Load hl7.terminology#3.1.0 - 4117 resources (00:00.743)
  Load R5 Extensions - 86 resources (00:03.848)
  Terminology server http://tx.fhir.org - Version 2.0.14 (00:00.508)
  Load ./multitarget-package.tgz - 4 resources (00:00.070)
  Get set...  go (00:00.004)
Validating
  Validate ./bundle-multitargetprofile.json
Validate Bundle against http://hl7.org/fhir/StructureDefinition/Bundle..........20..........40..........60..........80.........|
 00:00.234
Done. Times: Loading: 00:08.080, validation: 00:00.234. Memory = 1Gb

Success: 0 errors, 1 warnings, 0 notes
  Warning @ Bundle.entry[0].resource.ofType(MedicationDispense).medication.ofType(Reference) (line 33, col59): Found multiple matching profiles for Medication/medicationmultitarget among choices: http://example.com/fhir/multitarget/StructureDefinition/multitarget-medication, http://hl7.org/fhir/StructureDefinition/Medication
```

**Comment by rettema** [comment]
Please review at the next FHIR-I IG Authoring Tools call.

**Comment by grahamegrieve** [comment]
This is not in the purview of the FHIR-I Authoring tools call

**Comment by rettema** [comment]
Should I go ahead and create a branch, implement this change and submit a PR?

**Comment by grahamegrieve** [comment]
you should start by defining test cases and adding them to the test case repo in /validation
