### ISSUE TITLE
Publisher using wrong text for short and definition

### ISSUE THREAD

**Issue by lmckenzi** [hapifhir/org.hl7.fhir.core#914]
When a profile defines the types of an element, the IG Publisher replaces the short and definition of the element with values from the first mentioned type, rather than from the base definition.

See further details and specific test cases here: https://github.com/HL7/fhir-ig-publisher/issues/227

**Comment by dotasek** [comment]
There should be a snapshot test case replicating this. I'll look on the fhir-ig-publisher issue to see what can be done.

**Comment by dotasek** [comment]
The original issue has some broken links at this point. 

Is what I describe below a good example for replication @RichardTON?

The definition for http://hl7.org.au/fhir/StructureDefinition/au-location (full source: https://github.com/hl7au/au-fhir-base/blob/master/input/resources/au-location.xml) contains the comment "This is primarily used for the physical address..." for `Location.address`.

```xml
    <element id="Location.address">
      <path value="Location.address" />
      <comment value="This is primarily used for the physical address of the location. The Organization however uses the address property for administrative purposes."/>
      <type>
        <code value="Address" />
        <profile value="http://hl7.org/fhir/StructureDefinition/Address" />
        <profile value="http://hl7.org.au/fhir/StructureDefinition/au-address" />
      </type>
    </element>
```

The generated profile at http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-location.html doesn't contain this text, instead using the generic description "An address expressed using postal conventions (as opposed to GPS or other location definition formats)".

**Comment by RichardTON** [comment]
Links break. :( 

My revised description.

The definition for http://hl7.org.au/fhir/StructureDefinition/au-location ( **built at** : https://hl7.org.au/fhir/4.0.0/StructureDefinition-au-location.html **full source**: https://github.com/hl7au/au-fhir-base/blob/master/input/resources/au-location.xml) makes no changes to the short or definition for `Location.address`.
```
    <element id="Location.address">
      <path value="Location.address" />
      <comment value="This is primarily used for the physical address of the location. The Organization however uses the address property for administrative purposes."/>
      <type>
        <code value="Address" />
        <profile value="http://hl7.org/fhir/StructureDefinition/Address" />
        <profile value="http://hl7.org.au/fhir/StructureDefinition/au-address" />
      </type>
    </element>
```
The generated profile at http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-location.html contains the changed text for comment. However it ALSO changes the short and definition from the values in [`Location.address`](http://hl7.org/fhir/R4/location-definitions.html#Location.address)to those in [`Address`.](http://hl7.org/fhir/R4/datatypes.html#Address)

**Comment by grahamegrieve** [comment]
I think I fixed this, because the behaviour is different between elements and extensions

**Comment by lmckenzi** [comment]
Agree, this now seems to be fixed.
