### ISSUE TITLE
[BUG] HL7 Validator CLI -jurisdiction 

### ISSUE THREAD

**Issue by david-simons** [hapifhir/org.hl7.fhir.core#953]
The `-jurisdiction` parameter on the Validator CLI seems to be broken, recently.
For example, `uv` no longer is picked up, we always get `Jurisdiction: No Jurisdiction`

```
> java -jar org.hl7.fhir.validation.cli-5.6.72-SNAPSHOT.jar -jurisdiction uv
FHIR Validation tool Version 5.6.72-SNAPSHOT (Git# 05993e20eac4). Built 2022-10-17T12:59:47.127+02:00 (33 mins old)
<cut>
  Params: -jurisdiction uv
Scanning for versions (no -version parameter):
  No Version Info found: Using Default version '4.0'
  Jurisdiction: No Jurisdiction     <<<<<<<<<<<<<<<<<<<<<<
```

does it relate to this recent commit perhaps?
<https://github.com/hapifhir/org.hl7.fhir.core/commit/e73f79103cd5be03242175950a9066d0831090de#>

**Comment by dotasek** [comment]
The method used to report the jurisdiction was broken and would always report `No Jurisdiction` regardless of what value was present.
