### ISSUE TITLE
Cannot make fhirpath date operation with years or month

### ISSUE THREAD

**Issue by delcroip** [hapifhir/org.hl7.fhir.core#973]
I have a resource with 2 variables

one (named yol) that is set to the value of a quantity itemAnswer (unit 'a') or 0 years if the itemAnswer is not found 

the other is `today() -%yol`

on the questionnaire loading in the android-fhir sdk I am getting this error 
```
org.hl7.fhir.exceptions.PathEngineException: Error in date arithmetic: attempt to add a definite quantity duration time unit a (@char 5)
```
When trying to find the root cause I found the below linked code

https://github.com/hapifhir/org.hl7.fhir.core/blob/4be04173458c8f0ce7ec64237839e9e9554005ff/org.hl7.fhir.r4/src/main/java/org/hl7/fhir/r4/utils/FHIRPathEngine.java#L2017

Is there a reason why code 'a' (resp 'mo') is set to throw error instead of following the same behavior as 'year' (resp 'month')  ? 

best regards

**Comment by grahamegrieve** [comment]
because of subtle issues in the way mo is defined. This is discussed in the FHIRPath specification

**Comment by delcroip** [comment]
Hi @grahamegrieve ,

then how can I make a variable in a questionnaire that create a month quantity ? (it seems to add the 'mo' unit) ? 

for questionnaireItem of quantity type, is there a codesystem that have 'month' instead of 'mo' ? 

(same questions for a/years)

br

**Comment by grahamegrieve** [comment]
Question to ask on chat.fhir.org
