### ISSUE TITLE
ValidationEngine is not compatible with 4.X.X, 5.X.X(future) issue

### ISSUE THREAD

**Issue by NamGyu-Lee** [hapifhir/org.hl7.fhir.core#977]
thanks to contribute open source programming.
I'm writing that not fluent in English.

package org.hl7.fhir.validation.lgLoader.loadResourceByVersion function is not compatible with FHIR ver4.1 ~ 4.3
cause org.hl7.fhir.validation.lgLoader.loadResourceByVersion code in function is here.

public Resource loadResourceByVersion(String fhirVersion, byte[] content, String fn)
		throws IOException, FHIRException {
	Resource r;
	if (fhirVersion.startsWith("3.0")) {
		...
	} else if (fhirVersion.startsWith("4.0")) {
		...
	} else if (fhirVersion.startsWith("1.4")) {
		...
	} else if (fhirVersion.startsWith("1.0")) {
		...
	} else if (fhirVersion.equals(Constants.VERSION) || "current".equals(fhirVersion)) {
		// Constants.VERSION is 5.0.X(current server pom version)
		...	
	} else {
		throw new FHIRException("Unsupported version " + fhirVersion);
	}
	return r;
}

is that mean, what i want to using ValidationEngine Ver4.1~4.3, then ValidationEngine call StructureDefinition allways "Unsupported version" in initalizing using Igloader
like this in Console,

  Load FHIR v4.3.0 from hl7.fhir.r4b.core#4.3.0 - 3485 resources (00:11.0418)
  Load hl7.terminology#4.0.0 - 4164 resources (00:01.0855)
  Terminology server http://tx.fhir.org - Version 2.0.14 (00:02.0524)
  Load c:/tet/20220914/2_generateResourceToDocument/logical   ..Detect format for c:\tet\20220914\2_generateResourceToDocument\logical\structuredefinition-v1.json
   ..Detect format for c:\tet\20220914\2_generateResourceToDocument\logical\structuredefinition-v2.json
   ..Detect format for c:\tet\20220914\2_generateResourceToDocument\logical\structuredefinition-v3.json
* load file: structuredefinition-v1.json - ignored due to error: Unsupported version 4.3.0
* load file: structuredefinition-v2.json - ignored due to error: Unsupported version 4.3.0
* load file: structuredefinition-v3.json - ignored due to error: Unsupported version 4.3.0
 - 0 resources (00:00.0012)
* load file: maps.json - ignored due to error: Unsupported version 4.3.0
* load file: map2.json - ignored due to error: Unsupported version 4.3.0

this issue maybe occar in 5.1~ too.

**Comment by grahamegrieve** [comment]
fixed next release. 4.3.0 will be supported. Other versions won't be supported

**Comment by NamGyu-Lee** [comment]
thanks
