### ISSUE TITLE
Split packages problem in convertors module

### ISSUE THREAD

**Issue by johnpoth** [hapifhir/org.hl7.fhir.core#98]
Seems like the [convertors](https://github.com/hapifhir/org.hl7.fhir.core/tree/master/org.hl7.fhir.convertors/src/main/java/org/hl7/fhir/convertors) module share the same package 'org.hl7.fhir.convertors' as hapi-fhir's hapi-fhir-converter [module](https://github.com/jamesagnew/hapi-fhir/tree/master/hapi-fhir-converter/src/main/java/org/hl7/fhir/convertors).

This can cause problems in Java 9+ and OSGI. Thanks !

**Comment by jamesagnew** [comment]
@johnpoth - Just so I understand, if we merge the PR in the hapi-fhir repo that you linked to, does that resolve this issue or are there changes needed in this repo too? (Certainly I have no concerns at all with the linked PR)

**Comment by johnpoth** [comment]
@jamesagnew oops opened the issue in the wrong repo. The PR resolves this issue. Sorry for the trouble

**Comment by jamesagnew** [comment]
@johnpoth No worries at all. :)
