### ISSUE TITLE
[Bug?] Erroneous `Unknown CodeSystem` warning in `ValueSet.compose.include` validation

### ISSUE THREAD

**Issue by david-simons** [hapifhir/org.hl7.fhir.core#986]
As briefly discussed just now @dotasek :

Since recently (incl. upgrading to a newer HL7Validator CLI version) we're getting a warning that we did not get before:

`ValueSet.compose[*].include[*]*:
      - Unknown System 'http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl' specified, so Concepts and Filters cant be checked`

We supply the CodeSystem locally as a file, via an `-ig` dependency - since it is not on [tx.fhir.org](http://tx.fhir.org/).

Validation passes in other places - e.g. using codes from this CodeSystem in a Coding - the erroneous warning seems to be tied to the ValueSet.compose.include , specifcally.

I did see some commits around `getNameForSystem` enhancements, a potential culprit?

The codesystem from which entries are included in the valueset is specified via an -ig dependency, and it one of the files *.codesystem.xml under that -ig folder dependency

```
<compose>
        <include>
            <system value="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl" />
            <concept>
                <code value="C99942" />
                <display value="Coronary Artery Right Dominance" />
            </concept>
```

we have a local file \FHIR\uv\4.0\base\gov.nih.nci.ncicb\package\NCIt.codesystem.json included in the -ig \FHIR\uv\4.0\ dependency

```
{
  "resourceType": "CodeSystem",
  "meta": {
    "profile": [
      "http://hl7.org/fhir/StructureDefinition/shareablecodesystem"
    ]
  },
  "url": "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl",
  "version": "2.0.0",
  "name": "NCIthesaurus",
etc.
```

**Comment by dotasek** [comment]
Could we please get all the files involved in this particular case, plus the CLI arguments used to execute it?

**Comment by david-simons** [comment]
oh, looks like it worked in 5.6.70, and broke with 5.6.71:

```
PS \Downloads\issue986> java -jar .\validator_cli_5.6.70.jar .\CoronaryArteryDominanceValueSet.valueset.xml -ig .\gov.nih.nci.ncicb\package\xml\NCIt.codesystem.xml
FHIR Validation tool Version 5.6.70 (Git# 2fd44c420396). Built 2022-10-11T01:12:16.827Z (30 days old)
  Java:   17 from C:\Program Files\jdk-17 on amd64 (64bit). 2018MB available

WARNING: Default file encoding is windows-1252 which may cause unexpected results.
         To fix this issue, run this program with the parameter '-Dfile.encoding=UTF-8'
         Future releases may not be able to run at all with encoding windows-1252

  Paths:  Current = \Downloads\issue986, Package Cache = \.fhir\packages
  Params: .\CoronaryArteryDominanceValueSet.valueset.xml -ig .\gov.nih.nci.ncicb\package\xml\NCIt.codesystem.xml
Scanning for versions (no -version parameter):
  No Version Info found: Using Default version '4.0'
  Jurisdiction: No Jurisdiction
Loading
  Load FHIR v4.0.1 from hl7.fhir.r4.core#4.0.1 - 4575 resources (00:06.821)
  Load hl7.terminology#4.0.0 - 4164 resources (00:01.932)
  Load R5 Extensions - 85 resources (00:10.550)
  Terminology server http://tx.fhir.org - Version 2.0.14 (00:01.112)
  Load .\gov.nih.nci.ncicb\package\xml\NCIt.codesystem.xml - 1 resources (00:00.038)
  Get set...  go (00:00.010)
Validating
  Validate .\CoronaryArteryDominanceValueSet.valueset.xml
Validate ValueSet against http://hl7.org/fhir/StructureDefinition/ValueSet..........20..........40..........60..........80.........|
 00:00.240
Done. Times: Loading: 00:20.892, validation: 00:00.241. Memory = 739Mb

Success: 0 errors, 0 warnings, 1 notes
  Information: All OK



PS \Downloads\issue986> java -jar .\validator_cli_5.6.71.jar .\CoronaryArteryDominanceValueSet.valueset.xml -ig .\gov.nih.nci.ncicb\package\xml\NCIt.codesystem.xml
FHIR Validation tool Version 5.6.71 (Git# 64884ac66806). Built 2022-10-14T21:51:24.128Z (26 days old)
  Java:   17 from C:\Program Files\jdk-17 on amd64 (64bit). 2018MB available

WARNING: Default file encoding is windows-1252 which may cause unexpected results.
         To fix this issue, run this program with the parameter '-Dfile.encoding=UTF-8'
         Future releases may not be able to run at all with encoding windows-1252

  Paths:  Current = \Downloads\issue986, Package Cache = \.fhir\packages
  Params: .\CoronaryArteryDominanceValueSet.valueset.xml -ig .\gov.nih.nci.ncicb\package\xml\NCIt.codesystem.xml
Scanning for versions (no -version parameter):
  No Version Info found: Using Default version '4.0'
  Jurisdiction: No Jurisdiction
Loading
  Load FHIR v4.0.1 from hl7.fhir.r4.core#4.0.1  Load hl7.terminology.r4#5.0.0 - 4174 resources (00:09.264)
 - 7394 resources (00:00.002)
  Load hl7.terminology#4.0.0 - 4164 resources (00:01.924)
  Load R5 Extensions - 85 resources (00:10.340)
  Terminology server http://tx.fhir.org - Version 2.0.14 (00:01.201)
  Load .\gov.nih.nci.ncicb\package\xml\NCIt.codesystem.xml - 1 resources (00:00.038)
  Get set...  go (00:00.004)
Validating
  Validate .\CoronaryArteryDominanceValueSet.valueset.xml
Validate ValueSet against http://hl7.org/fhir/StructureDefinition/ValueSet..........20..........40..........60..........80.........|
 00:00.636
Done. Times: Loading: 00:23.254, validation: 00:00.637. Memory = 662Mb

Success: 0 errors, 1 warnings, 0 notes
  Warning @ ValueSet.compose[0].include[0]: Unknown System 'http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl' specified, so Concepts and Filters 
cant be checked
```

**Comment by grahamegrieve** [comment]
ok so how to reproduce?

**Comment by david-simons** [comment]
> ok so how to reproduce?

thanks Graham - I've sent David the files - out of band (in private)

**Comment by dotasek** [comment]
I can replicate with David's files. Will debug.

**Comment by david-simons** [comment]
Based on @dotasek suggestion - a potential dependency conflict in multiple versions of the same CodeSystem - trying the following

![image](https://user-images.githubusercontent.com/6153327/201393877-0fbc5ed1-076f-435a-8c6c-7dc54a7e2a47.png)

which resolves the warning, at least. Now that the versions are the same, my locally-provided dependency is used again.

Still the warning message "Unknown system" seems odd.

**Comment by david-simons** [comment]
Where did the `http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#3.0.0` CodeSystem conflict come from, @dotasek ?

I don't find it in `hl7.fhir.r4.core#4.0.1` nor `hl7.terminology.r4#5.0.0` (by that canonical , at least)

**Comment by david-simons** [comment]
PS: Note the discussion on the canonical url for this particular codesystem:
<https://confluence.hl7.org/display/TA/National+Cancer+Institute+-+Thesaurus?focusedCommentId=134942441#comment-134942441>

**Comment by david-simons** [comment]
@grahamegrieve 

Current error code is confusing:
`Warning @ ValueSet.compose[0].include[0]: Unknown System 'http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl' specified`

Perhaps, have it say `System 'http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl' specified, but its version '3.0.0' has 'content="not-present"'`

**Comment by grahamegrieve** [comment]
yes I have improved the error message. but that doesn't solve the problem - so not done yet

**Comment by david-simons** [comment]
Preferably I'd get the content from the hl7.terminology package, of course.
