### ISSUE TITLE
German translations of plural phrases required

### ISSUE THREAD

**Issue by dotasek** [hapifhir/org.hl7.fhir.core#990]
There are a number of phrases in Messages_de.properties that need to be corrected in order to manage plural cases.

At the moment, each of these is tagged with #REPARIERE MICH PLURAL, and the existing phrase has simply been copied. An appropriate singular phrase (`_one`) and plural phrase (`_other`) should be put in place.

```
#REPARIERE MICH PLURAL
Bundle_BUNDLE_Entry_Type3_one=Der type "{1}" ist nicht g\u00fcltig - muss einer von {2} sein
Bundle_BUNDLE_Entry_Type3_other=Der type "{1}" ist nicht g\u00fcltig - muss einer von {2} sein
```

https://github.com/hapifhir/org.hl7.fhir.core/blob/dbef06873089dfc1f3bbf4e97a8f7577c77925de/org.hl7.fhir.utilities/src/main/resources/Messages_de.properties#L18

Note that there are a number of phrases  where the singular case (`_one`) is left intentionally blank. The comment explaining why is in English. It would be more appropriate if these comments were in German as well.

```
#The following error cannot occur for a single item. _one case left intentionally blank.
#Profile_based_discriminators_must_have_only_one_type__in_profile_one=
Profile_based_discriminators_must_have_only_one_type__in_profile_other=Profilbasierte Diskriminatoren d\u00fcrfen nur einen Typ ({1} im Profil {2}) haben.
```

**Comment by patrick-werner** [comment]
currently on it. Will provide translations for all open  phrases
