### ISSUE TITLE
Dutch translations of plural phrases required

### ISSUE THREAD

**Issue by dotasek** [hapifhir/org.hl7.fhir.core#991]
There are a number of phrases in Messages_nl.properties that need to be corrected in order to manage plural cases.

At the moment, each of these is tagged with #REPAREER MIJ PLURAL, and the existing phrase has simply been copied. An appropriate singular phrase (`_one`) and plural phrase (`_other`) should be put in place.

```
#REPAREER MIJ PLURAL
Validation_VAL_Profile_Maximum_one = {3}: max toegestaan = {7}, maar gevonden {0} (uit {1})
Validation_VAL_Profile_Maximum_other = {3}: max toegestaan = {7}, maar gevonden {0} (uit {1})
```

https://github.com/hapifhir/org.hl7.fhir.core/blob/dbef06873089dfc1f3bbf4e97a8f7577c77925de/org.hl7.fhir.utilities/src/main/resources/Messages_nl.properties#L220

Note that there are a number of phrases  where the singular case (`_one`) is left intentionally blank. The comment explaining why is in English. It would be more appropriate if these comments were in Dutch as well.

```
#The following error cannot occur for a single item. _one case left intentionally blank.
Profile_based_discriminators_must_have_only_one_type__in_profile_one =
Profile_based_discriminators_must_have_only_one_type__in_profile_other = Profiel-gebaseerde discriminators moeten slechts een type bevatten ({1} in profile {2})
```

**Comment by vadi2** [comment]
@ahenket ?
