### ISSUE TITLE
compile can't finish, at the :utilities 

### ISSUE THREAD

**Issue by linxd** [hapifhir/org.hl7.fhir.core#996]
what's wrong with this? 

mvn -Dmaven.test.skip install   -rf :org.hl7.fhir.utilities
----------------
[INFO] Reactor Summary for org.hl7.fhir.utilities 5.6.79:
[INFO]
[INFO] org.hl7.fhir.utilities ............................. FAILURE [  0.900 s]
[INFO] org.hl7.fhir.dstu2 ................................. SKIPPED
[INFO] org.hl7.fhir.dstu2016may ........................... SKIPPED
[INFO] org.hl7.fhir.dstu3 ................................. SKIPPED
[INFO] org.hl7.fhir.r4 .................................... SKIPPED
[INFO] org.hl7.fhir.r4b ................................... SKIPPED
[INFO] org.hl7.fhir.r5 .................................... SKIPPED
[INFO] org.hl7.fhir.convertors ............................ SKIPPED
[INFO] org.hl7.fhir.validation ............................ SKIPPED
[INFO] org.hl7.fhir.validation.cli ........................ SKIPPED
[INFO] org.hl7.fhir.report ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.288 s
[INFO] Finished at: 2022-11-21T21:22:51+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create-metadata (downstream) on project org.hl7.fhir.utilities: Execution downstream of goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create-metadata failed.: NullPointerException -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]

**Comment by dotasek** [comment]
I haven't seen this in any of my builds, or the pipelines yet. 

Could you provide some more information?

What version of Java are you running?

What version of Maven are you running?

It looks like you tried to restart a previously failed build with `-rf`. Could you provide full logs of what happened in that previous build, as well as any logging that might be missing from this error report?

**Comment by jamesagnew** [comment]
Two quick thoughts:

* Do you have git installed? I think that plugin is calling the git executable to get the git revision number
* Can you add `-e` to your maven command? That gives a bit more info about the error

**Comment by linxd** [comment]
in windows :
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
----------
or in centos : 
Apache Maven 3.0.5 (Red Hat 3.0.5-17)
openjdk version "1.8.0_345"
OpenJDK Runtime Environment (build 1.8.0_345-b01)
OpenJDK 64-Bit Server VM (build 25.345-b01, mixed mode)

**Comment by jamesagnew** [comment]
Oh, next obvious question I suppose is: did you check the code out using git?

I don't think this plugin works if you use the "download sources" button in GitHub.. It would be nice if they did support that of course, but I have a feeling that this might be the issue.

I do notice that there's now a version 3.0.0 of the buildnumber plugin. I wonde if it addresses this limitation?
